espanol/torre/alarma/alarma.md, espanol/torre/alarma/asustado/asustado.md
=> agregando ciudadanos asustados

french/dessine/miel/forest/approcher.md, french/dessine/miel/manger-du-miel.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2073)
=> Manger du miel and arriver dans une foret

english/wake-up/wake-up-again/dream2/dream2.md, english/wake-up/wake-up-again/wake-up-again.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2022)
=> Add dream 2 in wake-up, wake-up-again.

english/swami-vivekananda/swami-vivekananda.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2063)
=> Wisdom added.

portugues_pt/colaborar.md, portugues_pt/praias/solemar.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2065)
=> add surf trip to solemar storyline

english/macgyver/macgyver.md
For bot @casey-collab
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2067)
=> Add another mullet comment to macgyver.md

english/water-dreams/fish-sanctuary/fish-sanctuary.md
Also fixed some spelling/grammar errors and tidied up the text.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2069)
=> Added a few lines to the fish sanctuary

english/light-fire/extinguish-fire/extinguish-fire.md
Added a few lines to this story line.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2076)
=> Add result of extinguishing fire with potential for a twist

english/polar-bear/polar-bear.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2080)
=> Pull the pin from your hand grenade.

espanol/canudos.md, espanol/ejercito/ejercito.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2053)
=> Anadir ejercito

english/guitar/guitar.md
Hi - I read a Life Hacker article on guitar players having stinky fingers. I tough that adding this to the story would add some authenticity to this project ;-)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2075)
=> Add stinky garlic fingers to guitar storyline

english/meditate/meditate.md
expanded the meditating.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2079)
=> added some lines to the meditate page

english/you-are-in-minecraft/dig_down/dig_down.md
=> Minecraft back surface

english/marshmallow.md, english/swami-vivekananda/swami-vivekananda.md
=> Add lines to main story and swami*.md

english/dance/dance.md, english/myStory/mayank.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2087)
=> A brief about myStory.

english/code/code.md, english/marshmallow.md
=> Add link to story "code" in "marshmallow.md"

english/marshmallow.md
=> Gordon changes

korean/marshmallow.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2089)
=> Add eat wall

espanol/angeles/angeles.md, espanol/canudos.md
Agregando a la historia: "Un ejercito de angeles para ayudar a los guerreros".
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2091)
=> Un ejercito de angeles para ayudar a los guerreros

english/marshmallow.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2094)
=> Add hyphen to vacant eyed

english/watch-alien/watch-alien.md
Added a couple lines to the end about a mysterious green liquid (the cause of the off putting odour) that strangely is glowing to your heartbeat, as if listening to you.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2096)
=> Add a couple lines about some mysterious liquid

english/appear-on-falkors-back/falkor.md, english/yearg/yearg.md
=> Added new option to 'appear-on-falcors-back'

vietnamese/kechuyen.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2119)
=> Add a funny story to the Vietnamese version

Italian/guardare/libri-francesi/prendere-il-libro/porta/porta.md, Italian/guardare/libri-francesi/prendere-il-libro/prendere-il-libro.md
=> See what's behind the secret door

german/Hilfeschrei/Vertrauen/insMaul/gloeckchen/gloeckchen.md, german/Hilfeschrei/Vertrauen/insMaul/ins_maul.md
=> add option gloeckchen to kobold arc

english/hammertime/hammertime.md
=> Add lyrics for when it is hammer time

english/hungry/hungry.md, english/marshmallow.md
=> Hunger story

english/batman/batman.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2150)
=> Batman is a hallucination

english/marshmallow.md, english/papa-louie/papa-louie.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2151)
=> Add a page to play papa-louie!

english/use-the-fork-luke/use-the-fork.md
=> Added the man-bear-pig story without deletions

english/marshmallow.md, english/pikachu/pokeball.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2161)
=> pikachu attack

english/use-the-fork-luke/use-the-fork.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2159)
=> Added the option of Man-Bear-Pig and hippy in mirror which leads to VR

english/bite-the-marshmallow/ricky/ricky.md, english/bite-the-marshmallow/tasty-marshmallow.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2165)
=> review new story options

turkce/catalla-kaz/catalla-kaz.md, turkce/catalla-kaz/kus/kus.md
@casey-collab
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2174)
=> Add new option for vomitting

french/sortie/tirer-porte/tirer-porte.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2175)
=> Added line

english/cry-out-for-daddy/oh_daddy.md
@casey-collab I hope the bot may still merge when the final line had to be edited with a newline to allow continuation of the story.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2176)
=> add a line to the oh_daddy storyline

english/fill-sock/fill-sock.md
=> Add link fill sock

romanian/nalba.md, romanian/potiune_fermecata/beau/beau.md, romanian/potiune_fermecata/nu_beau/nu_beau.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2182)
=> To Drink or Not to Drink

english/commit-suicide/suicide.md
Can't automerge because it sees a line change. Maybe because I had to add a carriage return to the end of the line?
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2163)
=> Add hotline information link

english/world-war-marshmallows/world-war-marshmallows.md
Minor rephrasing of existing story.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2168)
=> Edit to existing text

english/backinstraitjacket/backinstraitjacket.md, english/backinstraitjacket/takemeds/takemeds.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2169)
=> Added take meds option to 'get back in your straitjacket'

english/backinstraitjacket/takemeds/takemeds.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2154)
=> docs: Added 'take meds' option

dutch/check-mail/mail.md, dutch/welkom.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2172)
=> added new story branch

english/find-bird/bird.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2180)
=> Add marshmallow peep.

arabic/dream/dream.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2183)
=> Remove broken link

english/watch-barca/watch-barca.md
=> add line to watch-barca page

english/code/code.md
Please review story additions, @casey-collab
=> Add code to make pants stop glowing

english/glowing-pants/glowing-pants.md, english/investigate-glowing-pants/investigate-glowing-pants.md
=> Add option to investigate glowing pants

english/is-this-a-dream/is-this-a-dream.md, english/marshmallow.md, english/remember-you-are-superman/remember-you-are-superman.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2191)
=> Sa changes english

english/movie-ripoffs/fantasia/fantasia.md, english/movie-ripoffs/matrix/matrix.md
Include an extension of the Matrix story in which
you seduce witches, fight fires, and reign for many
years (actually hours).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2193)
=> feat: Add a fantasia/narnia-esque adventure

english/marshmallow.md
=> Added 'tuesday' line to base english story

english/tickle/tickle.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2195)
=> added to the tickle story

esperanto/komenci.md, language.md
I added a branch of the story in esperanto
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2192)
=> esperanto version

english/jumpsuit/jumpsuit-review.md
=> changes to jumpsuit

english/turing-test/siri/ask_siri.md
=> Added additional commentary about marshmallows and android.

english/apj/quotes/quotes.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2196)
=> Add APJ Kalam Quote

english/bounce/bounce.md, english/marshmallow.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2203)
=> Add bounce to story

english/water-dreams/pig-farm/love-bacon/love-bacon.md, english/water-dreams/pig-farm/love-bacon/pig-friend/pig-friend.md, english/water-dreams/pig-farm/love-bacon/pig-therapy/pig-therapy.md, english/water-dreams/pig-farm/love-bacon/spirit-quest/spirit-quest.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2204)
=> added new options after realizing you still love bacon

english/remember-you-are-superman/fly-away-home-to-lois/fly-away-home-to-lois.md, english/remember-you-are-superman/remember-you-are-superman.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2206)
=> Add fly away home to lois ending

portugues/colabora/comdiferencas/diff/pull/reenvio/watch/divulga/colaborador/colaborador.md, portugues/colabora/comdiferencas/diff/pull/reenvio/watch/divulga/divulga.md, portugues/colabora/comdiferencas/diff/pull/reenvio/watch/divulga/instrutor/instrutor.md
Thank you.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2207)
=> Minha parte da história

english/marshmallow.md, english/udacity/udacity.md
=> Add udacity option and file

romanian/nalba.md
=> Add "asta inseamna sa fii mafiot" meme into the story

espanol/noticias/anteojos/anteojos.md, espanol/noticias/noticias.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2211)
=> Mis Cambios a la historia

english/marshmallow.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2217)
=> Change Story: Leak

english/super-powers/practice-flying.md
=> Add to super-powers choice

english/go-back-to-sleep/go-back-to-sleep.md, english/marshmallow.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2219)
=> Add new entry about going back to sleep

dutch/check-mail/mail.md
Please review this, @casey-collab"
=> doc: added options after reading mail

french/appel-au-secours/appeler-au-secours.md, french/feu-de-camp.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2225)
=> Add call for help in french

espanol/noticias/burla-periodista/burla-periodista.md, espanol/noticias/burla-periodista/tropezar/tropezar.md
Continué la historia donde el periodista se lanza contra Beatito.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2214)
=> El periodista se tropieza otra vez

english/udacity/udacity.md
Include link to Caroline's Page to find her
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2216)
=> Include link to Caroline's page

espanol/maquina/maquina.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2224)
=> agregar autores a español

english/Enter-a-dim-reality/continue-forward/Forward_Stay/forwardStay.md, english/explore-outside/journey-to-flaming-tower/start-running/confront/confront.md, english/grue/grue.md, english/light-fire/graham-crackers/chocolate/make-chocolate/make-chocolate.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2220)
=> feat: Add grue page and linked references

arabic/Job/Job.md, arabic/salamoAlikom.md
=> Get job for AR

english/pick-up-blowtorch/blowtorch.md, english/pick-up-blowtorch/stop-running/apologize.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2227)
=> Add reactions to Stay Puft Marshmallow Man

english/bake-cookies/cookies.md, english/weed/weed.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2215)
=> Add my space cookies story

english/meditate/meditate.md
=> Add content to meditate.md file

english/marshmallow.md, english/play-dota2/play-dota2.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2233)
=> Add 'Play some DotA 2' option in marshmallow.md

english/marshmallow.md, english/watched/watched.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2235)
=> Add watched option to english/marshmallow.md

english/marshmallow.md
=> Mention a fellow named Dave Granger

arabic/salamoAlikom.md
@casey-collab, please review for merge
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2240)
=> Add Nanodegree option to arabic story

english/marshmallow.md
=> feat: Add superman text

english/make_changes_GitHub/clone_source/stuck.md, english/make_changes_GitHub/create_fork/clone_repo.md, english/make_changes_GitHub/create_fork/pull_request/success.md, english/make_changes_GitHub/create_fork/wait/forever_alone.md, english/make_changes_GitHub/google/die.md, english/make_changes_GitHub/make_changes_GitHub.md, english/marshmallow.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2244)
=> Add files for storyline 'make changes to GitHub'

english/forest-canopy/forest-canopy.md, english/macgyver/light-rope-on-fire/wait/wait.md
Please review my added story bits, @casey-collab !
=> Forest adventure

portugues/colabora/colaborar.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2236)
=> feat: Fix typo in colabora.md

portugues/amigo/filosofia/estudar.md, portugues/amigo/tecnologia.md
I added one entry in the Portuguese adventure
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2241)
=> Add Portuguese adventure

english/marshmallow.md, english/young/young.md
I added young/young.md and modified main md file.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2248)
=> Add my story(?)

english/coffee/coffee.md
=> Add option to eat walls after having coffee

english/cycling-backwards/cycling-backwards.md, english/marshmallow.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2257)
=> Cycle backwards

espanol/muralla/abrir/abrir.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2258)
=> Agrega nueva línea a la historia.

english/pinch/magic/harry-potter.md
woot! please auto-merge @casey-collab
=> apparate to hogwarts

english/remember-you-are-superman/remember-you-are-superman.md, english/remember-you-are-superman/zack-snyder-movie/do-you-bleed/do-you-bleed.md, english/remember-you-are-superman/zack-snyder-movie/zack-snyder-movie.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2261)
=> Zack snyder

Italian/scappare/barba/barba.md, Italian/scappare/cercare-uscita.md
added an item (barba/barba.md) to the "scappare" choice file (Italians/scappare/cercare-uscita.md) @andreacat
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2263)
=> Awesome classy move inserted in the Italian experience

english/marshmallow.md
Please review this, @casey-collab. Thanks!
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2272)
=> Add a story link

catala/catala.md, catala/menjar/menjar.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2271)
=> update: Menjar added under subdirectory catala/menjar

english/batman/batman.md
=> Add one line to Batman.md

hungarian/zokni/zokni.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2278)
=> added a link back to a previous level of the story.

english/wake-up/wake-up-again/dream2/dream2.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2252)
=> Add a sentence to the marshmallows life

english/love/love.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2262)
=> Add advise in english/love/love.md

german/Leichen/Leichen.md
I have fixed several typos
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2268)
=> fix: fixed several typos

english/dance/dance.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2270)
=> Add the ape happy dance

espanol/huida/pagar/camino/camino.md, espanol/huida/pagar/pagar.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2288)
=> Add new option in espanol/huida/pagar

espanol/beatito/beatito.md, espanol/canudos.md
Hi, please check this new text lines, @casey-collab
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2283)
=> New Adventure request

english/2spooky/2spooky.md
=> added a sentence

english/batman/batman.md
=> Theme song logic

german/Leichen/Leichen.md
I just added a line to the story 'Leichen' in the german folder.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2291)
=> Add Line for the story - Trying to get back.

english/yoga/mind/yoga_mind.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2301)
=> change to yoga_mind.md

french/sortie/tirer-porte/tirer-porte.md, french/sortie/tirer-porte/traverser-hautes-herbes/traverser-hautes-herbes.md
=> Next outside options for french

english/swami-vivekananda/teachings-of-swami-vivekananda/quotes.md
merge them
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2287)
=> Vivekanand Golden rules added to Quotes

english/watched/watched.md
@casey-collab
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2308)
=> Added an option to bake cookies after staring into abyss

english/virtualreality/voice/strangeVoice.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2314)
=> Add a line to the strange voice in virtual reality

english/licked-cat/vacation.md, english/marshmallow.md
Added link in marshmallow.md to link to vacation.md.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2316)
=> Added the folder licked-cat with file vacation.md

portugues/colabora/comdiferencas/diff/pull/reenvio/watch/divulga/instrutor/instrutor.md
Add options for instrutor.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2307)
=> Add options for instrutor.md

english/watched/watched.md
@casey-collab
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2310)
=> Uncapitalize Bake

english/buy-gameboy/buy-gameboy.md, english/ninja/ninja.md
@casey-collab
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2313)
=> try ninja again

dutch/over-het-hek/sleutel/sleutel.md, dutch/over-het-hek/sleutel/wereld/welkeWereld.md
@casey-collab if don't want to go into the void , make yourself useful and merge this, por favor!
=> Added Wereld subfolder to the Dutch language folder

english/adipose/awake/awake.md
"@casey-collab" please review my pull request
=> Add comforting message to awake.md

english/karaoke/karaoke/girl-is-real/girl-is-real.md, english/karaoke/karaoke/sing.md
=> Temp branch

Italian/finestra/apri.md, Italian/finestra/tour/tour.md
=> Change apri.md and add new story option

Italian/scappare/raccogli/cerotto/cerotto.md, Italian/scappare/raccogli/piangi/piangi.md, Italian/scappare/raccogli/raccogli.md, Italian/scappare/raccogli/resisti/resisti-ancora/resisti-ancora.md, Italian/scappare/raccogli/resisti/resisti.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2334)
=> My changes to italian story

english/jacket/complete-jacket/ad.md
=> Add history of tyres in english/jacket/complete-jacket/ad.md

english/ponder/ponder-some-more/ponder-some-more.md
Add a couple options to a deadend in english/ponder/ponder-some-more/ponder-some-more.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2336)
=> Outcome of thinking

english/marshmallow.md, english/present-tense/present-tense.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2340)
=> Add my story of present-tense

slovak/marsmelaci.md, slovak/zachrana/zachrana-rybky.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2341)
=> Add a new Slovak option and modify marsmelaci.md file

dutch/over-het-hek/flippo/eet/eet.md, dutch/over-het-hek/flippo/flippo.md, dutch/over-het-hek/flippo/scheer/scheer.md, dutch/over-het-hek/hek.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2342)
=> Added few dutch options

english/listen_white_stripes/listen_white_stripes.md, english/marshmallow.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2345)
=> Listen to White stripes options

english/cycling-backwards/cycling-backwards.md
=> feat: Add a note about brown bears.

german/ruderboot.md, german/wegschneiden/ausziehen/ausziehen.md, german/wegschneiden/ausziehen/schwimmen/schwimmen.md, german/wegschneiden/wegschneiden.md
Check this out, @casey-collab
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2349)
=> Added a new Storyline

english/young/young.md
@casey-collab  please add my link
=> added option for Vivaldi

english/go-back-to-sleep/dream-ception/dream-ception.md, english/go-back-to-sleep/go-back-to-sleep.md
=> Dream ception

english/movie-ripoffs/hogwarts/burn-marshmallows, english/pinch/magic/harry-potter-burn-marshmallows/burn-walls.md, english/pinch/magic/harry-potter.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2361)
=> Add option of using Harry Potter spell to light a fire

english/burn-down-the-house/house-burn.md, english/lamping/lamping.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2366)
=> Burn down the house

english/avatar/air.md
"Please review this, @casey-collab
=> Added new scenario to air.md

english/DKER/DKER.md, english/marshmallow.md
=> Add DKER to the story

english/lego-world/lego-world.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2370)
=> added a new line to lego-world

english/lightsoff/lightsoff.md, english/marshmallow.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2375)
=> Add lights off option

english/alchemy/alchemy.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2376)
=> feat: add creation of multiple coins

espanol/heroe/chuky/chuky.md, espanol/heroe/heroe.md
=> Agrego a chuky y lala.

english/alchemy/alchemy.md, english/android-v6/use-android-v6.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2382)
=> feat: add glass droid

english/batman/batman.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2384)
=> Added my own line to Batman.md

english/batman/batman.md
it's the best line in entire film!
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2387)
=> Add Commissioner Gordon's line to batman.md

Italian/scappare/barba/barba.md
=> Add an observation about aftershave

english/exercise/exercise.md, english/marshmallow.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2391)
=> Add a recommendation to exercise

english/exercise/exercise.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2394)
=> Exercise and Diet

espanol/dragon/dragon.md, espanol/dragon/muerte-dragon/muerte-dragon.md
Please, add this part of the story @casey-collab
=> Add muerte-dragon to dragon in espanol

english/selfie/selfie.md
=> Add choice option to cast a spell in selfie

espanol/bruja/bruja.md
=> Completar historia de la bruja

english/yoga/mind/yoga_mind.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2413)
=> Make a change to the story

english/kindness/acts-of-kindness.md, english/marshmallow.md
=> Acts of kindness page.

english/kindness/acts-of-kindness.md
=> Add a second act of kindness

english/exercise/exercise.md, english/exercise/fuck_it/fuck_it.md, english/exercise/seek_veg/seek_veg.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2423)
=> Option added to exercise path

english/marshmallow.md, english/shotgun/shotgun.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2435)
=> My contribution

english/sing-song/sing.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2436)
=> Update sing.md with option for bird is the word!

english/go-back-to-sleep/dream-ception/dream-ception.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2443)
=> Add explanation from Leo.

english/ethical-reason/ethical-reason.md, english/marshmallow.md
=> Add new option to the story

english/eat-rainbows/right/right.md
=> Add how we feel about Safeway cake

espanol/capitan/trueno.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2450)
=> Aparece una bruja en la historia del capitan

espanol/canudos.md, espanol/comida/comida.md, espanol/comida/ogros/ogros.md, espanol/comida/victoria/victoria.md
Review this contribution  @casey-collab
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2451)
=> Añado la historia del vómito

english/bite-the-marshmallow/tasty-marshmallow.md
Add a sentence to say that not going to dentist for root canal actually saves hundreds of bucks
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2452)
=> Add a sentence in the page of biting marshmallow walls

german/Hilfeschrei/Vertrauen/insMaul/reinhauen/reinhauen.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2457)
=> Verwandelt sich in einen Frosch

english/bake-cookies/cookies.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2459)
=> Add new option

english/watch-movie/Up.md
=> add marshmallow watching F-Troop

english/marshmallow.md, english/vegas/fear-loathing-las-vegas.md
=> Add Vegas story.

english/chai/make-marshmallow-masala-chai.md, english/marshmallow.md
=> Marshmallow masala chai

english/marshmallow.md
=> add extra story to marshmallow.md

english/in-matrix/matrix.md, english/marshmallow.md
=> Add new story to marshmallow.md, Necessary directory and files with contents.

english/my-story/my-story.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2472)
=> Add dialog to imagination land

english/make-friends/lol/laugh-out-loud.md
=> Added line to laugh out loud

czech/druhy_bok/spanek.md, czech/kapsy/mince/roztocit.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2476)
=> few new sentences

english/eating-walls/find-a-toilet/door/alien/dont-care/dont-care.md, english/eating-walls/find-a-toilet/door/alien/use-torch.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2477)
=> My addition to the story

english/enjoy-DreamRide/ride.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2471)
=> Add 'have a cup of coffee' link to ride.md

english/make_changes_GitHub/create_fork/pull_request/cooper-station/cooper-station.md, english/make_changes_GitHub/create_fork/pull_request/success.md
Go back to the marshmallow room or go on to a new adventure.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2482)
=> Long for more adventure.

english/copper-plate-man/copper-plate-man.md, english/marshmallow.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2487)
=> Adding copper plate man story

language.md, swahili/marshmallow.md
this starts a swahili version of the story
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2277)
=> start swahili version

english/coffee/coffee.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2317)
=> Add lines and edits to coffee.md

Chinese/大话西游.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2321)
=> Change to English name

english/call-a-doctor/insideTheTardis/insideTheTardis.md, english/call-a-doctor/timelord/timelord.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2327)
=> Adventure story

english/singapore/singapore.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2328)
=> add lines to the go to singapore story

english/marshmallow.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2337)
=> Add Burning Man line

portugues_pt/praias/solemar.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2346)
=> Add Turks and Caicos.

catala/sortir/sortir.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2352)
=> Add a few lines on catala/sortir/sortir.md

english/kicktheman/kicktheman.md, english/lego/lego.md
@casey-collab
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2363)
=> add kicktheman

english/2spooky/2spooky.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2372)
=> Change 2spooky.md

english/explore-outside/journey-to-flaming-tower/walk/portal/wishes/teleport/scream/scream.md, english/explore-outside/journey-to-flaming-tower/walk/portal/wishes/teleport/teleport.md, english/explore-outside/journey-to-flaming-tower/walk/portal/wishes/teleport/wish-hangglider/wish-hangglider.md, english/explore-outside/journey-to-flaming-tower/walk/portal/wishes/teleport/wish-parachute/wish-parachute.md
@casey-collab
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2380)
=> Added options to teleport.md

english/bob-barker/barker.md
final exercise of Udacity Git/Github course
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2392)
=> ADD: Smile of Marshmellows

english/karaoke/karaoke/propose-to-her/propose-to-her.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2397)
=> Proposal response

english/breaking-bad/breaking-bad.md, english/netflix/netflix.md
Added a Breaking Bad link to continue and loop the Netflix branch.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2399)
=> Djcrum1107

catala/cantar/tastar/tastes_sol/tastes_sol.md, catala/catala.md, catala/troll/troll.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2400)
=> català: Create new option with troll story, and fix some errors

english/is-this-a-dream/is-this-a-dream.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2402)
=> Eat that pizza and dive in ..

english/wikipedia/wiki.md
how does it look? Please review this, @casey-collab
=> added calculus to wiki

english/scream/walk/walkwiththought.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2406)
=> Add some lines to the story

english/explore-outside/journey-to-flaming-tower/walk/under_bridge/under_bridge.md, english/explore-outside/journey-to-flaming-tower/walk/walk.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2427)
=> Add troll under bridge

espanol/heroe/aventurero/aventurero.md, espanol/heroe/heroe.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2438)
=> Espanol-heroe-aventurero

czech/kapsy/nuz/bandaz/marsmelak.md, czech/kapsy/nuz/riz.md
I added a link with text to the currently last story setting/decision point. I then created a new folder and created the next story setting..
Thanks for the UDACITY course!
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2439)
=> add bandaz storyline to czech/kapsy/nuz/riz

french/appelle-genie/appelle-genie.md, french/feu-de-camp.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2456)
=> add new story option appelle-genie

english/reddit/ask-reddit.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2464)
=> docs: Add "Consider unsubscribing from r/awww" line

english/explore-outside/investigate-marshmallow-structure/say-hello/say-hello/say-hello.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2489)
=> Add tshirt sentence

arabic/salamoAlikom.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2496)
=> add option to order food online

Polish/przygoda/miesnie/miesnie.md, Polish/przygoda/miesnie/spanie/spanie.md
Please check this @casey-collab
=> Polish change

hindi/art-of-living/art-of-living.md, hindi/bollywood.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2500)
=> Shared details about Art of Living

danish/synging/synging.md, danish/velkommen.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2502)
=> Add lighten the mood option

espanol/canudos.md, espanol/dimension/dimension.md
=> Add a new line at the end of file

english/wikipedia/wiki.md
=> I added a sentence !

english/bite-the-marshmallow/ricky/ricky.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2498)
=> Finished sentence of driver.

english/check-phone/check-phone.md, english/check-phone/delete-message/delete-message.md, english/check-phone/open-message/open-message.md, english/marshmallow.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2491)
=> Add story about mysterious text

english/is-this-a-dream/is-this-a-dream.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2504)
=> added a link back from the is-this-a-dream tangent dead-end.

english/marshmallow.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2505)
=> Add meta story element

english/triathlon/triathlon.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2512)
=> Must have tri-suit!

portugues/titanic/pular/boiar/voce/voce.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2513)
=> Ramiro adventure

english/bite-the-marshmallow/tasty-marshmallow.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2507)
=> add coffee line to story

english/eating-walls/find-a-toilet/door/bear/stand-still.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2508)
=> Add a terrible pun to the bear story

romanian/Beau/Beau_paharul_pana_la_fund.md, romanian/nalba.md
Romanian story one more step.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2510)
=> Fb adventure

english/lightsaber/lightsaber.md, english/marshmallow.md
Lightsaber option for story
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2511)
=> Lightsaber

Thai/Cuisine/TomYumKung.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2517)
=> Add a line of story into Thai food experience story.

english/I'm-batman/batman.md
=> Add link to honest trailer

Italian/scappare/cercare-uscita.md, Italian/scappare/scopri-oggetto/scopri-oggetto.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2522)
=> Add new option to creare-uscita.md (Italian)

english/burn-down-the-house/house-burn.md
=> feat: Add link back to the start

english/better-call-saul/saul.md, english/marshmallow.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2529)
=> feat: Add better caul saul story path

english/ninja/ninja.md
hey, please accept my request, @casey-collab ! thanks!
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2521)
=> Add new link to ninja

english/yoga/benefits/yoga_benefits.md
=> Add benefit to list of yoga benefits

english/code/code.md
=> @casey-collab

english/marshmallow.md, english/play-music/playmusic.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2538)
=> Add entry playmusic

Italian/scappare/scopri-oggetto/esamina-stanza/controlla-stanza/controlla-stanza.md, Italian/scappare/scopri-oggetto/esamina-stanza/esamina-fogli/esamina-fogli.md, Italian/scappare/scopri-oggetto/esamina-stanza/esamina-stanza.md, Italian/scappare/scopri-oggetto/scopri-oggetto.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2540)
=> Add first room inspection after glass bottle found

english/wake-up/wake-up.md
It's not much, but it is mine!
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2542)
=> Added a twist to the story

english/marshmallow.md, english/the-nights/the-nights.md
Thanks
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2543)
=> This is my story. Please update to the original repo

english/netflix/netflix.md
Hey @casey-collab,
I know I changed a line but please fix this typo!
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2530)
=> fix netflix typo

english/marshmallow.md
suggested storyline involving music in croatia building on the latest line in the plot
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2541)
=> Add new croat storyline

english/eat-rainbows/right/right.md
=> Add a line

english/marshmallow.md, english/sounds-familiar/sounds-familiar.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2548)
=> Dan's story

english/132-days-ago/132-days-ago.md, english/marshmallow.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2549)
=> Add chocolate expired on marshmallow.md

french/panique/frapper-le-mur.md
=> Add an alternative to smell flowers

english/happy-robot/happy-robot.md, english/marshmallow.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2556)
=> Add happy robot story

english/heffalump/heffalump.md, english/marshmallow.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2560)
=> Add heffalump storyline

english/super-powers/practice-flying.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2562)
=> added option to summon dragons

english/invite-friends/friends.md
Added breakfast option to friends.md
Please review @casey-collab
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2563)
=> Add breakfast option to friends

english/code/code.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2555)
=> Added sentence to code.md

english/remember-you-are-superman/zack-snyder-movie/do-you-bleed/Batman-vs-superman/Batman-vs-superman.md, english/remember-you-are-superman/zack-snyder-movie/do-you-bleed/Batman-vs-superman/Spoilers/Spoilers.md
Extend Superman story with new Spoiler story page
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2557)
=> Create link in Batman-vs-superman page to extend story

english/batman/batman.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2561)
=> add imdb batman source to english version

english/moving/moving.md
=> Step into the Marshmallow

english/hermione/hermioneHere, english/hermione/hermioneHere.md, english/marshmallow.md
I added some text in english/marshmallow.md and then created a link.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2567)
=> Hermione granger here

english/animal/animal.md, english/marshmallow.md
=> Added a cat adventure.

english/sing/out-of-tune/out-of-tune.md
=> monster retreats

english/marshmallow.md
casey-collab  please review
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2572)
=> Add different days

english/marshmallow.md
@casey-collab please review
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2574)
=> Add Saturday

german/schwimmen/hunger/momentmal/momentmal.md
=> Continue cannibal scene

english/wikipedia/wiki.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2581)
=> Add content to the wiki adventure.

hungarian/malyvacukor.md, hungarian/oxygen/oxygen.md
Please, review my new page and approve @casey-collab
=> Add oxygen page

french/feu-de-camp.md
Please review this, @casey-collab, thanks.
=> Add option to feu-de-camp

english/make_changes_GitHub/make_changes_GitHub.md
=> p-story loop

english/robot-rap-battle/robot-rap-battle.md
Added robot-rap-battle line proving coming singularity.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2578)
=> Add rrb as proof of coming singularity

english/get-out-of-system/get-out-of-system.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2582)
=> Added questions to the story

english/wikipedia/wiki.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2587)
=> Edit the wikipedia story in english stories

english/ghostbusters/ghostbusters.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2595)
=> Add line to ghostbusters.md

language.md, maibrat/tinyi.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2596)
=> Add Mai Brat Language Support

portugues/colaborando.md
Por gentileza, senhor @casey-collab verifique minha edicao
=> add sua imaginacao

english/go-back-to-sleep/go-back-to-sleep.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2597)
=> Update to dreamland

espanol/dimension/dimension.md
=> A few more lines in Spanish

english/marshmallow.md, english/the-slayer/freddie/freddie.md, english/the-slayer/marshmallow-slayer.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2601)
=> Create new action

portugues/colaborando.md, portugues/telefonica/ocupado.md
Faz favor de adicionar @casey-collab
=> add cia telefonica com link e nova pagina

english/132-days-ago/132-days-ago.md
=> add a pack of donuts to 132-days-ago

english/33hours/explore-outside/outside.md, english/33hours/explore-room/look-under-bed/look-under-bed.md, english/33hours/explore-room/room.md, english/33hours/explore-room/use-phone/use-phone.md, english/33hours/wakingup.md, english/marshmallow.md
Added 33Hours story.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2605)
=> Added 33Hours story

english/33hours/explore-outside/outside.md
=> Added action for exploring outside

espanol/canudos.md, espanol/general/general.md
Thank you for the great course!
=> New spanish language history "general"

english/zork/zork.md
=> A contribution to the story

english/explore-outside/explore-outside.md, english/lawn-mower/lawn-mower.md
Added lawn mowing to the explore-outside story
=> Class edit

english/find-bird/bird.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2619)
=> Add option to pinch yourself.

vietnamese/haloi/khongvoiduocdau.md, vietnamese/kechuyen.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2620)
=> Add haloi/khongvoiduocdau.md to vietnamese language folder

english/virtualreality/oculus.md
Add a new piece of story to english/virtualreality/oculus.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2622)
=> Add new piece of story

english/dream/fly/fly.md
When flying during your dream, adds the option to go back inside and wait to wake up. This option points to sleep/marshmallow.md,
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2625)
=> New flying option

espanol/perro/perro.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2630)
=> A Dago le gusta su dueno

espanol/canudos.md, espanol/kraken/kraken.md
=> Added Kraken sentence

english/marshmallow.md, english/tweet-it/tweet-it.md
Added a new section to the story, allowing players to live tweet their bizzare story.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2638)
=> New section "tweet it"

english/go-back-to-sleep/dream-ception/dream-ception.md, english/go-back-to-sleep/dream-ception/shutter-island/shutter-island.md, english/go-back-to-sleep/dream-ception/wolf-of-wall-street/wolf-of-wall-street.md
Leonardo diCaprio story continues!
=> My contributions

german/finger-ins-loch/finger-ins-loch.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2627)
=> Pauls adventure

english/karaoke/karaoke/sandwich/sandwich.md, english/karaoke/karaoke/sing.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2629)
=> Add sandwich option to karaoke branch in english

Italian/aiuto/aiuto.md, Italian/aiuto/chi/chi.md, Italian/aiuto/dove/dove.md, Italian/aiuto/dove/fine/fine.md, Italian/aiuto/fine/fine.md, Italian/aiuto/uscita/uscita.md, Italian/caramelle.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2631)
=> Add Help option

english/marshmallow.md, english/memories/memories.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2633)
=> My own branch

english/my-story/my-story.md, english/other-castle/other-castle.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2643)
=> change my-story to link to new other-castle

english/breakfast/breakfast.md
please review this, @casey-collab
=> added a line to breakfast

english/animal/animal.md
I wish you like it, @casey-collab
=> Paint it black

lithuanian/miegoti/miegas.md, lithuanian/startas.md
=> Adding 'Miegas'

turkce/catalla-kaz/metali-cek/iple-in/iple-in.md, turkce/catalla-kaz/metali-cek/metali-cek.md
=> Change in Turkish version of the story

espanol/cocinero/error/salon/platos/platos.md, espanol/cocinero/error/salon/salon.md
=> Add text and link to salon.md

french/manger/trou/reveille/sirene/crapaud.md, french/manger/trou/reveille/surprise.md, french/manger/trou/reveille/voix-humaines/mystere.md
Please, review this @casey-collab
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2689)
=> Newpart pull request

english/oil-field/oil-field.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2659)
=> Added line to oil-field.md in oil-field directory (english)

english/shrunk/shrunken.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2662)
=> add option to take a pill

english/marshmallow.md, english/poke-the-wall/poke-the-wall.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2664)
=> Add umbrella with chocolate syrup

english/bob-barker/barker.md
@casey-collab
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2671)
=> Added Barket Beauties reference to story.

english/marshmallow.md, english/no-worries/hakuna-matata.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2677)
=> Add mystory to the storyline of create-your-own-adventure

Polish/ptasieMleczko.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2680)
=> changed language.md

english/virtualreality/oculus.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2682)
=> Shake Hansel, shake

english/licked-cat/vacation.md, english/the-slayer/marshmallow-slayer.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2687)
=> edit grammar, word choice

espanol/canudos.md, espanol/cielo/cielo.md, espanol/mujeres/mujeres.md, espanol/soldados/soldados.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2690)
=> Please auto-merge

english/132-days-ago/132-days-ago.md, english/marshmallow.md, english/youre-fine/youre-fine.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2691)
=> Added a new page and directory and linked to it from existing page.

english/few-good-men/fgm.md, english/marshmallow.md
Please add my story to original repository
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2695)
=> My adventure story of few good men

english/marshmallow-wizard/marshmallow-wizard.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2696)
=> add text and link to marshmallow-wizard.md

english/marshmallow.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2697)
=> Add line about "what is a marshmallow anyway?"

english/marshmallow.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2700)
=> Add 'Do you:' to watch the new star wars trailer

english/yoga/yoga.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2703)
=> Add monster to yoga session

english/selfie/selfie.md
add line about fairy godmother
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2705)
=> type: docs

Polish/przygoda/jedzenie/najedzony/najedzony.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2707)
=> zdjecie kurtki

english/check-your-phone/check-your-phone.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2713)
=> Add plan to go to Paris

language.md, norwegian/start.md
Will the automatic @casey-collab merge work this time?
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2714)
=> Add Norwegian to adventure.

english/dream/fly/space/space.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2717)
=> Add line to space.md.

espanol/bailar/bailar.md, espanol/bailar/matar/matar.md
please merge it, @casey-collab !
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2704)
=> Add Beatito's treason and the Consejero's death

english/marshmallow.md, english/references/references.md
Adding this in as part of the final exercise in Udacity's How to Use Git And GitHub course.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2721)
=> Pull Request for References branch

english/marshmallow-wizard/marshmallow-wizard.md, english/marshmallow-wizard/save-the-world/save-the-world.md
=> Save the world

czech/druhy_bok/sen/ve_snu.md, czech/druhy_bok/spanek.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2716)
=> New line in druhy_bok

espanol/canudos.md, espanol/tactica/confesion/confesion.md, espanol/tactica/suicidio/suicidio.md, espanol/tactica/tactica.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2726)
=> New story option for Spanish language ("tactica")

english/ask-on-quora/ask-on-quora.md, english/marshmallow.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2728)
=> Added more radiohead

english/bob-barker/barker.md, english/bob-barker/eat-marshmallow/hot.md
=> Add new choice and page to 'bob-barker'

english/zork/zork.md
=> add halloween reference to zork

english/kindness/acts-of-kindness.md
One good(?) deed begets another.
=> Add an Act of Kindness

english/marshmallow.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2678)
=> Add option to browse reddit to story

english/marshmallow.md
one extra line.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2734)
=> Story continuation, toilet.

english/singapore/singapore.md
Singapore
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2737)
=> It's not that hot.

english/free-lunch/free-lunch.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2741)
=> Further ruminations on TASTAAFL

english/super-powers/practice-flying.md, english/weed/weed.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2731)
=> Shainanigans

english/kindness/acts-of-kindness.md
=> Add 2 sentences to acts-of-kindness.md

english/marshmallow.md, english/or-do-you/or-do-you.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2748)
=> Add "or-do-you" to the story

english/lego/lego.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2750)
=> Add two lines to determine what is a lego

english/kindness/acts-of-kindness.md
@casey-collab please accept this
=> added line to acts of kindness story

espanol/angeles/angeles.md
Just adding simple text the an existing file
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2749)
=> Add a line to the angeles file in the espagnol directory

english/marshmallow.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2754)
=> Added goosebumps line

english/marshmallow.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2753)
=> news story about strange noises

english/coffee/Paris/fly-to-paris.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2751)
=> Change conversation text in paris airport interaction

english/batman/batman.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2752)
=> Added Uncle Ben to Batman (english)

english/batman/batman.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2758)
=> Comment on Uncle Ben

english/coffee/drink-water/Swim/swim.md, english/coffee/drink-water/drink.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2747)
=> Added pre-existing choice point to go for a swim

english/marshmallow.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2757)
=> Added line to Marshmallow.md

espanol/canudos.md, espanol/telefono/telefono.md
Please @casey-collab review this. Regards
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2761)
=> Add Mybranch of /espanol folder

english/be-octodog/octodog.md, english/your-dog/your-dog.md
@casey-collab please, if you would, merge my addition to the story.
Thanks,
John D.
=> Merge of your-dog?

serbian/burekSir/burekSir.md, serbian/burekSir/noz/noz.md, serbian/burekSir/tihaPatnja/tihaPatnja.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2763)
=> Nastavak tuzne mamurne price o pekari u kojoj nema bureka sa sirom.

english/marshmallow.md, english/more_cowbell/more_cowbell.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2771)
=> I got a fever. And the only prescription.....is more cowbell.

english/references/references.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2776)
=> Docs: Add new choice and option to referenses

english/memories/ground-hog/wakeup.md, english/memories/memories.md
Please review this Ground Hogs Day addition @casey-collab
=> Ground control

english/new-years/new-years.md, english/or-do-you/or-do-you.md
=> feat: add new-years continuation to the or-do-you continuation

english/marshmallow.md
=> Add Tim Berners-Lee to the adventure

english/marshmallow.md
Added my story
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2784)
=> Add Anirudha's adventure

english/light-fire/magic-world/back/back.md
=> add question on marshmallow taste

english/happy-robot/happy-robot.md
=> Add a couple lines to happy-robot

english/eating-walls/find-a-toilet/door/open-door.md, english/eating-walls/find-a-toilet/door/pushed/pushed.md
please review, @casey-collab
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2789)
=> added pushed.md & altered open-door.md to reflect

espanol/huida/rechazar/arrastra/arrastra.md, espanol/huida/rechazar/ayuda/ayuda.md, espanol/huida/rechazar/rechazar.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2764)
=> Raqueldata

english/more_cowbell/more_cowbell.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2783)
=> Christopher Walken pocket watch added

english/more_cowbell/more_cowbell.md
My changes to the story
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2793)
=> Weapon of choice

english/marshmallow.md, english/scarab/goddess.md, english/scarab/stack-rocks/stack-rocks.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2782)
=> Add stack rocks option.

english/marshmallow.md
=> English mod

french/appelle-genie/appelle-genie.md
=> Modify the genie story (French)

english/marshmallow.md, english/prostate/prostate.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2685)
=> Add "prostate" story and link to it on marshmallow page.

english/new-years/new-years.md, english/raccoon-corner/raccoon-corner.md
=> Add racoon to new-years

english/sanfran/bikeride/bikeride.md, english/sanfran/sanfran.md
=> Added a bike ride

english/marshmallow.md
Please review this edit to marshmallow.md... Thanks!
=> Add bird question

english/eating-walls/eating-marshmallows.md, english/eating-walls/sound-of-birds/sound-of-birds.md
=> Sound of birds

english/pinch/pinch.md
=> Give more description about feel of jacket.

english/eating-walls/find-a-toilet/door/bear/too-many-marshmallows/get-eaten.md, english/eating-walls/find-a-toilet/door/bear/too-many-marshmallows/too-many-marshmallows.md, english/eating-walls/find-a-toilet/door/bear/too-many-marshmallows/yell-at-bear/get-eaten.md
=> Add get eaten by bear

espanol/dolor/dolor.md
=>  Keeping a Fork Up-To-Date

french/sortie/tirer-porte/traverser-hautes-herbes/frapper-la-chose/frapper-la-chose.md, french/sortie/tirer-porte/traverser-hautes-herbes/traverser-hautes-herbes.md
=> Add option frapper to traverser-hautes-herbes

english/eating-walls/find-a-toilet/door/bear/too-many-marshmallows/too-many-marshmallows.md
=> Add sentence in too-many-marshmallows

english/sanfran/bikeride/bikeride.md, english/sanfran/bikeride/burrito/burrito.md
=> add option to eat a burrito, add burrito.md

english/new-york/new-york.md
=> add option to go from new york to vacation

espanol/canudos.md, espanol/pesadilla/pesadilla.md
=> Add another change in the Spanish version

portugues/amigo/incomodar/aplicativo.md, portugues/amigo/incomodar/desenvolver/aplicativo.md
Please review this, @casey-collab. Thanks.
=> Desenvolver novo aplicativo

romanian/zana_albastra/cum_arata_zana.md
=> Add a second line to the story.

french/manger/trou/reveille/voix-humaines/ecouter/ecouter.md, french/manger/trou/reveille/voix-humaines/mystere.md
=> Add 'ecouter' option to mystere.md in french version

english/marshmallow.md, english/plow/plow.md, english/plow/plow.txt
=> Add plow/plow.txt to english folder

english/marshmallow.md
=> Add recursion to the story

english/scarab/goddess.md
Hope this works @casey-collab!
=> Add disconcerting line to goddess.md

english/marshmallow.md
=> Add some text

english/skydiving/skydiving.md
=> Change on skydiving story.

english/better-call-saul/saul.md
=> add youtube link to saul.md

english/marshmallow.md, english/watch-star-wars/watch-star-wars.md
=> Very much excite about star wars

english/code-my-life/code-my-life.md, english/marshmallow.md
=> Added my line of code to the life story.

english/marshmallow.md, english/say-my-name/heisenberg/heisenberg.md, english/say-my-name/say-my-name.md
=> Heisenberg

english/triathlon/triathlon.md
=> Add budget consideration

english/marshmallow.md
=> Add an option for the second new Star Wars trailer in marshmallow.md

english/skydiving/skydiving.md
=> Add line to end of Skydiving.md

english/animal/animal.md
=> Add line about cat

slovak/flasa/nikdy-viac.md, slovak/marsmelaci.md
=> Enhanced slovak story

english/hammertime/hammertime.md
=> Add funny hammer video

english/justice-league/justice-league.md, english/marshmallow.md
@casey-collab hey bot dude, merge this!
=> update story with new link to the justice league (dc comics)

espanol/canudos.md, espanol/duda/duda.md
=> Add a new adventure

english/justice-league/justice-league.md, english/justice-league/spiderman/spiderman.md
=> You can send distress signal to Spidey!

english/swami-vivekananda/swami-vivekananda.md
=> Add advice line, @casey-collab

english/swami-vivekananda/swami-vivekananda.md
=> Add advice line , @casey-collab

english/TheEpicSax/111_TheEpicSaxGuyArrives.md, english/marshmallow.md
Adde story continuation and the main character: Epic Sax Guy, who arrives to save the day ;)
=> Adding: The story of the Epic Sax Guy who saved the day, link to youtube

german/finger-ins-loch/hoelzernes-Paddel/aufmerksam_machen/ans_Ufer_ziehen/am_Ufer.md
=> add story line

english/sanfran/bikeride/bikeride.md
=> Add third option to bikeride adventure

english/marshmallow.md
=> Add "listen to tales of the inexpressable" option to marshmallow.md

english/soar/fly-to-london/fly-to-london.md
=> Add parliament reference to London

german/Korallen/Hoehle/Meerjungfrau/meerjungfrau.md
Please review this, @casey-collab .
=> Kehre von der Meerjungfrau zurück ins Boot

english/soar/soar.md
=> Add new line to description

english/marshmallow.md, english/travel-destinations/spring/spring.md, english/travel-destinations/travel-destinations.md
@casey-collab, Please review my change to add new story in english for suggesting exciting travel destinations.
I named the branch 'mychanges' but I guess I should have given it a more unique name.. hopefully, that's not a huge deal in reviewing and merging this pull request.
=> Added story for travel destinations

espanol/canudos.md, espanol/explosion/explosion.md
here's my contribution in spanish
=> add my part of story

Polish/przygoda/jedzenie/korwin/korwin.md, Polish/przygoda/jedzenie/korwin/prezent2/krawat.md
Take a look at this @casey-collab
=> Extend korwin story

english/bird-salvation/bird.md, english/eatmarshmallow/eatmarshmallow.md
Please review and (hopefully) merge, @casey-collab
=> merge in add-bird-salvation branch

english/count-the-marshmellows/eat-all-the-marshmellows/pillow-problems/pillow-problems.md
Hey @casey-collab I know you're a bot and probably really busy hobnobbing with Cortana and Siri, but if you could find time in your schedule to slip this masterwork of writing into the repo I would be most appreciative.
=> Add bathtub filled with hot chocolate to pillow-problems

romanian/magazin/oferta-speciala.md, romanian/nalba.md
=> Add "oferta orbit".

english/marshmallow.md, english/star-wars-spoiler/star-wars.md
=> Star wars spoiler

english/weed/weed.md
=> add instructions title

english/coffee/coffee.md
This was a single line with no link or new files.
=> Added a line to coffee.md in the English directory.

english/marshmallow.md, english/play-geometrydash/play-geometrydash.md
Please review this, @casey-collab"
=> Add geometrydash

english/destiny/destiny.md, english/fight-out/fight-out.md, english/marshmallow.md
=> Add another-story

german/Einladen/Schule/schule.md, german/Einladen/einladen.md
=> Erzählfaden "Oktoberfest" erweitern

english/play-geometrydash/conan/conan.md, english/play-geometrydash/play-geometrydash.md, english/play-geometrydash/pretty-girl/pretty-girl.md
=> After geometry

english/lighter/grab-lighter.md
=> Modify story

espanol/pensamiento/guerra.md, espanol/pensamiento/meditacion/meditar.md
This is part of the Udacity course exercise
=> Added my part of story. Spanish

english/marshmallow.md
=> Add Donald Trump's reply

espanol/canudos.md
Please, review this @casey-collab
=> Merge upstream/master into change

espanol/canudos.md
Do you like Pappo, @casey-collab  ?
=> Add Pappo's reference to the original repo

english/light-fire/fire.md
Please have a look at this, @casey-collab
=> Add a line of dialogue for the rat in fire.md

kannada/kannada_kali/kannada_kali.md, kannada/soochike.md
=> Add new folder (kannada_kali) to kannada

english/light-fire/extinguish-fire/extinguish-fire.md
=> Add to extinguish-fire.md

english/poke-the-wall/eat-way-out/eat-way-out.md, english/poke-the-wall/poke-the-wall.md
Please review and add this, @casey-collab
=> Add option to eat the chocolate

english/lightsaber/wampa/wampa.md
=> Add explanation for the roar after leaving the marshmallow house

espanol/torre/alarma/asustado/asustado.md
=> Agregado de info sobre asesinato del alcalde

english/adipose/adipose.md
=> add line to adipose

english/coffee/cookie/Walk/creative-writing/creative-writing.md
Start of a creative writing after a nice walk.
=> Start of a creative story

english/play-dota2/play-dota2.md
Add option to play DOTA song in play-dota2.md
=> Add option to play DOTA song in play-dota2.md

espanol/comandante/almirante/almirante.md
=> Ampliación de la historia del almirante Tiger Woods

french/feu-de-camp.md
=> Add line: "Je parle un peu arabe" in French story

korean/marshmallow.md, korean/yoga/yoga.md
Please review this,@casey-collab
=> added a story

english/nepal/nepal.md
what do you think @casey-collab?
=> found a cat lady in nepal

english/challenge-marshmellow-to-rock-off/castle-route/narnia.md
=> add more detail to ladder vs. stairs decision.

english/marshmallow.md
=> Question about story

english/marshmallow.md
=> This is weird

english/travel-destinations/travel-destinations.md, english/travel-destinations/winter/winter.md
Added link to the winter options and included Glacier National Park as one possible destination.
=> Glacier nps addition

espanol/huida/rechazar/arrastra/arrastra.md
@casey-collab add this please!
=> add: Se agrega a continuár con la huída sin pagar

english/hands/hands.md
=> screaming at my missing fingernails. in hands/hands.md

english/flan/flan.md, english/flann-o-brien/truth-is-odd.md
It should create a new folder and change another part of the story.
It's a terrible addition.
=> added a bit about flan to the story

english/marshmallow.md
Pull request (though I posted a commit to the master of my fork and not a new branch).
=> Add a Star Wars reference, why not

english/marshmallow-attack/marsh-attack.md
=> Add a new option to the marshmellow attack file.

english/new-movie/new-movie.md
=> added more options to run left right or straight

english/boston/boston.md, english/marshmallow.md
@casey-collab wanna add this for me please?
=> added the best city yet

english/chief-history/chief-history.md
=> Chief history name question answered as Bruce Wayne and linked to batman.md

english/marshmallow.md
=> Added Queen's Bohemian Rhapsody reference

english/animal/animal.md
=> Add hot dog to animal.md

english/eating-walls/find-a-toilet/door/run-in/go-sleep/go-sleep.md, english/eating-walls/find-a-toilet/door/run-in/run-into-room.md
Please review this added extra option wait and sleep in the story, @casey-collab
=> Solo survivor

english/lasso-hand/strangle/strangle.md, english/lasso-hand/strangle/torch/torch.md
=> Torch contrib

english/destiny/destiny.md, english/hope/hope.md
=> Add high hopes

Italian/caramelle.md, Italian/colazione/colazione.md
=> added colazione

german/Korallen/Hoehle/Unterwasserstation/Person/Person.md
=> continue story with person in Unterwasserstation

Chinese/DesertHell/NewWorld.md, Chinese/DesertHell/NewWorld.txt, language.md
=> Add a new Story named deserthell

english/go-back-to-sleep/go-back-to-sleep.md
Adds plot to what happens to you after you run into Leonardo di Caprio in go-back-to-sleep.md
=> Request to merge Draw blank

english/warm-up/warm-up.md
Please review this, @casey-collab. Thanks!
=> Add description to warm-up page

english/lisp/lisp.md
=> Change to story

galician/dixital/dixital.md, galician/lua.md
=> Add dixital.md

english/warm-up/warm-up.md
@casey-collab Please review and merge.
=> Brett giles git lesson

english/bite-the-marshmallow/padded-room/escape/escape.md, english/bite-the-marshmallow/padded-room/first-blackout.md
=> Add escape route from padded room

english/bite-the-marshmallow/tasty-marshmallow.md
=> Add line on starbucks

english/magic/magic.md
@casey-collab Please review this (-/\-)
=> Add a jedi element

german/finger-ins-loch/solarbetriebener-Motor/solarbetriebener-Motor.md
=> Add new options for solarbetriebener-Motor

english/marshmallow.md
=> Gamified git

english/lighter/grab-lighter.md
=> Add text about Colorado

english/marshmallow.md
=> Add line to marshmallow

english/marshmallow.md
=> Javarod changes

english/hermione/hermioneHere.md, english/hogsmeade/hogsmeade.md, english/visit-hagrid/visit-hagrid.md
Added two options to Hermione's adventure.
@casey-collab, please do your thing.
=> Nevens mod

english/marshmallow.md, english/powerball/lost/lost.md, english/powerball/powerball.md, english/powerball/won/won.md
=> Add Powerball storyline.

english/destiny/destiny.md
=> Add one more destiny scenario

espanol/canudos.md, espanol/miedo/miedo.md
=> To add miedo.md file and update canudos.md according to the guidelines

english/hungry/hungry.md
@casey-collab, please review my change and merge it with the story.
=> Add suggestion to "hungry" page

german/Sonnenbrand/vor-sonne-schutzen.md
=> An adventure addition

english/dentist/ouch.md
Please merge this, @casey-collab
=> one line added in dentish

espanol/locura/locura.md, espanol/perro/perro.md
=> add new history

english/ghostbusters/ghostbusters.md, english/goosebumps/goosebumps.md
=> Goosebump story

english/exercise/exercise.md
=> add a 'save the world' option

english/DKER/DKER.md
=> Add guess about DKER.

espanol/ejercito/ejercito.md
=> Add sentence to ejercito

english/light-up/grab_tools_and_jump/grab_and_jump.md
=>  add useless police

english/you-are-in-minecraft/dig_down/dig_down.md, english/you-are-in-minecraft/dig_down/dig_down_more/dig_down_more.md
=> Add dig_down_more option

english/forest/shelter/shelter.md
=> added line to shelter.md

espanol/telefono/telefono.md
Just added a Spanish sentence in telefono file.
=> Adding sentence to telefono

english/candyland/diabetes.md, english/candyland/obamacare/signup.md
=> add obamacare option

english/forest/forest.md
=> Embellish forest story

serbian/burekMeso/burekMeso.md, serbian/start.md
=> Dodaj twist plot

serbian/noveIdeje/noveIdeje.md, serbian/noveIdeje/noveIdeje.txt, serbian/start.md
=> Side story

Polish/przygoda/jedzenie/wiedzmin/placki/placki.md, Polish/przygoda/jedzenie/wiedzmin/polska/polska.md, Polish/przygoda/jedzenie/wiedzmin/popus/popus.md, Polish/przygoda/jedzenie/wiedzmin/wiedzmin.md
=> docs: Luti tu był ;)

english/travel-destinations/fall/fall.md, english/travel-destinations/travel-destinations.md
=> Add some travel destinations for fall

german/Leichen/Leichen.md, german/Leichen/Simulation/Simulation.md
=> docs: add text for possible simulation (that's not reality)

english/knit/knit.md
=> fix: fix spelling mistake in knit

english/analyze/analysis.md, english/motor_oil/motor_oil.md
=> Added a motor oil option

english/amnesia/amnesia.md
=> Added single line as part of test

english/forest/fire/fight/fight.md, english/forest/fire/fire.md, english/forest/fire/stay/stay.md, english/forest/fire/woods/woods.md
I don't know if this can auto merge because I changed to forest/fire.md file.
=> add new files fight, stay, and woods to fire

english/2spooky/2spooky.md
=> add 'sup?'

english/build-a-car/build-a-car.md, english/marshmallow.md
=> Add Build a Car

english/private-party-island/island.md
=> Add penguins

english/pokemon/pikachu_wins.md
=> add a refreshing sentence

english/music/add_music.md
=> Add link to the song on youtube

english/light-fire/succumb/game-over.md, english/light-fire/succumb/get-help/help.md
=> Add option to pray for help

english/BayesTheorem/BayesTheorem.md, english/marshmallow.md
=> feat: Add Bayes' Theorem

german/Einladen/Vorstellen/Saarland/aus_dem_Saarland.md, german/Einladen/Vorstellen/vorstellen.md
=> Added new introduction for someone coming from Saarland

english/night-night/tale.md
=> Add line from The Night Before Christmas

english/coffee/coffee.md
Hi @casey-collab 
Please review my change.
=> Add conversation to coffee

Italian/finestra/cadi/tappeto-volante/sopra-t-rex/sopra-t-rex.md
=> Add how to defeat the t-rex

english/keep_looking_for_chocolate/keep_looking_for_chocolate.md, english/search_for_chocolate/search_for_chocolate.md, english/take-malt/take-malt.md, english/use-powers/use-powers.md
Add new option path from search_for_chocolate scene
=> Under tums

english/liquid/liquid.md, english/marshmallow.md
=> added liquid on marshmallow

english/joke/joke.md, english/marshmallow.md
=> Add a joke in story

english/liquid/liquid.md
=> Add line to liquid.md

english/talk_to_neighbour/talk_to_neighbour.md
=> add lines to talk_to_neighbour

english/destiny/destiny.md
=> Add option to open the door to destiny

english/poke-the-wall/choco-power-pill/choco-power-pill.md, english/poke-the-wall/poke-the-wall.md
=> Add option to eat a chocolate power pill.

english/crazy/crazy.md
=> add to crazy

english/turing-test/princessnell/princessnell.md, english/turing-test/turing-test.md
=> Keepersmith changes 101

english/licked-cat/vacation.md
=> Promote Mauritius as a vacation destination

portugues/colaborando.md
De uma olhada por favor, @casey-collab
=> duvida do tijolo

english/marshmallow.md, english/strange-room/room.md
=> Add strange-room/room.md

english/craving/craving.md
=> New line added to craving

german/Alkohol/alkohol.md
=> Fix german - alkohol spelling mistakes, added Bier

german/ruderboot.md
Please check and pull my changes
=> New choice in german/ruderboot.md

english/fortune/fortune.md, english/marshmallow.md
=> Add fortune/fortune.md with link in marshmallow.md

english/light-fire/extinguish-fire/extinguish-fire.md
Kindly review this @casey-collab
=> Add line after "one option left"

english/marshmallow.md, english/think/fire/lightfire.md, english/think/growrich.md, english/think/loveneighbour/neighbour.md
=> Merge my changes to existing code changes

english/marshmallow.md, english/steelers/steelers.md
Join Steeler Nation , @casey-collab ;)
=> Bring some steeler love to udacity!

english/procrastinate/grue/grue.md, english/procrastinate/procrastinate.md
Fixed prior issue so that this will be auto-merged.  Please review, @casey-collab
=> Dvdmon 1.01

english/marshmallow.md
=> link to Marshmallow Overcoat cover of Love song.

english/marshmallow.md, english/mermaid/mermaid.md
=> Added a mermaid

english/love/love.md
=> added a line on pain of love

english/kill-rats/kill-rats.md
=> Add line to killing rats

hindi/bollywood.md, hindi/hrithik/hrithik.md
=> Add hrithik, casey@

english/marshmallow.md, english/mermaid2/mermaid.md
=> Add story about mermaid

english/animal/animal.md
=> Add new line to animal.md

english/watch-movie/Up.md
=> add to english-movie

english/BayesTheorem/BayesTheorem.md
=> Bayes water

english/lightsoff/lightsoff.md
=> Add option to light fire

english/marshmallow.md, english/test-driven-development-rules/AccordingToUncleBob.md
Please review this, @casey-collab ... and Thanks!
=> My story contribution

afrikaans/beskuit/beskuit.md, afrikaans/beskuit/ouma/ouma.md, afrikaans/beskuit/tuisgebakte/tuisgebakte.md, afrikaans/kos.md, language.md
=> Added Afrikaans and inital story stub

english/yoga/benefits/yoga_benefits.md
=> Add meet righteous babes.

english/git/git.md, english/marshmallow.md
=> Add Space to the lines

english/kumar/kumar.md, english/marshmallow.md
=> added new file kumar.md to create your own adventure

english/better-call-saul/saul.md
=> Add more dialog to Better Call Saul page

language.md, telugu/Telugu/Telugu.md
=> Telugu directory and Telugu file added

english/watched/watched.md
=> extend introspective thought in front of the abyss

espanol/canudos.md, espanol/caracteristicas/caracteristicas.md
=> Pull request for spanish history

english/travel-destinations/spectre/spectre.md, english/travel-destinations/travel-destinations.md
=> Page addition

english/scarab/stack-rocks/stack-rocks.md
=> Add secrets of the universe to stacked rocks

english/say-my-name/say-my-name.md
=> add link to youtube video "say my name"

english/divergence/divergence.md
@casey-collab please merge this
=> introduce the starfish

english/love-udacity/love-udacity.md, english/marshmallow.md
=> Add vinceenebuse loves udacity story

french/manger/trou/grimpe/haricot.md, french/manger/trou/grimpe/pencher-bord-nuage/avion.md
=> Add option pencher-bord-nuage

english/free-lunch/free-lunch.md
=> Add new story line to free-lunch

english/mushroom/eat/eat_mushroom.md
=> In eat_mushroom, add option to call Batman

english/Booyah/booyah.md, english/marshmallow.md
=> Adding a new phrase to the story.

english/iot/intro.md, language.md
=> Add intro to IoT

english/talk_to_neighbour/woman/go-with-scully/talk-aside.md, english/talk_to_neighbour/woman/hop-into-car/drive.md, english/talk_to_neighbour/woman/scully.md
=> James change - updated Talk to Neighbor

english/hurdles/hurdles.md, english/marshmallow.md
added line to marshmallow.md that links to hurdles directory and md file
=> added hurdles page

english/marshmallow.md
=> Add story lines to english/marshmallow.md

english/sing/something-else/show-me-what-you-got/smwyg.md, english/sing/something-else/sing-something-else.md
=> Add story "show me what you got" to sing/sing-something-else

english/lunge-for-the-lighter/steep-slope/hallway/hallway.md, english/lunge-for-the-lighter/steep-slope/steep-slope.md, english/lunge-for-the-lighter/steep-slope/stone-tunnel/stone-tunnel.md
Things take a serious turn. #raccoons #dinosaurs
=> Oh the choices

english/marshmallow.md
=> Update the adventure

espanol/muralla/abrir/cerrado/cerrado.md
=> que hace el pueblo tras cerrar las puertas, Please review this, @casey-collab

Philippines/bago/bago.md, Philippines/salamat.md
@casey-collab Please review Thank you.
=> Added few links for PH

portugues/colaborando.md, portugues/udacity/udacity.md
and new conclusion (udacity folder and file)
=> Add new path from portuguese md file (udacity choice) 

english/lego-world/lego-world.md
=> Add chocolate lego platypus

espanol/canudos.md, espanol/curandero/curandero.md
=> Jplp2 version

german/abwarten/abwarten.md, german/ruderboot.md
=> Contribute to German part of the story

english/beer-brewer/beer-brewer.md, english/marshmallow.md
=> adding beer brewing adventure

english/batman/batman.md
Please verify my work, @casey-collab
=> Added alfred to the story

english/quit-your-job/quit-your-job.md
=> Contribute to English story

english/blah-balh/blah-blah.md, english/singing/singing.md
=> Extended /blah-balh

Gibberish/Gibberish.md, language.md
=> Add Gibberish

swedish/titta-ut/titta-ut.md
line added in swedish version with spelling errors
=> add line in swedish titta-ut

french/manger/trou/reveille/sirene/crapaud.md, french/manger/trou/reveille/sirene/et_alors/croisiere.md
=> add croisiere option

english/keep_looking_for_chocolate/keep_looking_for_chocolate.md, english/take-a-nap/take-a-nap.md
=> Add option to take a nap

english/2spooky/2spooky.md, english/combatration/combat_ration.md
=> Liang's combat ration

english/marshmallow.md, english/yellow-baby-buggy-bumpers/yellow-baby-buggy-bumpers.md
=> Added diversion thought for main character

english/say-my-name/say-my-name.md
=> Add pinkman

espanol/comida/comida.md, espanol/comida/guerrero/guerrero.md
Add new file guerrero	new file:   espanol/comida/guerrero/guerrero.md
=> Add new option guerrero,	modified:   espanol/comida/comida.md

Polish/przygoda/przygoda.md
Proszę dodaj tą zmianę @casey-collab
=> Dodano opcja Google w przygodzie !

english/getsLost/getsLost.md, english/getsLost/meetKate/meetKate.md, english/getsLost/runFromSmokeMonster/runFromSmokeMonster.md
=> Myspecialbranch

english/cricket/cricket.md, english/play-some-cricket/playsomecricket.md
=> Add link to Cricinfo

espanol/Mutantes/Mutantes.md, espanol/canudos.md
=> Agregando la era de los mutantes

espanol/Mutantes/Mutantes.md
=> Adiciona continuacion del control mental mutante

english/marshmallow.md
=> Add Indonesian Culture

english/marshmallow.md
=> Add a line to marshmallow

english/marshmallow.md, english/paint-it-black/PaintItBlack.md
=> Adding Story 'Paint It Black Stanza'

english/shotgun/shotgun.md
=> Add line about hot chocolate sea.

english/talk_to_neighbour/man/mulder.md
=> add a link to return to woman

french/sortie/chercher-la-sortie.md, french/sortie/trappe/trappe.md
S'il te plait @casey-collab, ajoute ça.
=> Correction ajout option trappe

english/animal/animal.md
=> add new lines to story

english/sandwich/sandwich.md
=> Finish sandwich

portugues/revisa/cria-proprio-app/cria-proprio-app.md, portugues/revisa/revisar.md
=> Add new step to portuguese version of the story

portugues/amigo/incomodar/reinventar/reinventar-app.md
Some text added. @casey-collab
=> Godofsun changes @casey-collab

english/marshmallow.md, english/rubik-cube/rubik-cube.md
The Guy is gonna play with Rubik's Cube!!
=> Add Rubik's Cube

english/animal/animal.md
=> Added a new line to english/animal/animal.md
