udacity/create-your-own-adventure

- portugues/spray/joaninha/comer/comer.md
- portugues/spray/matainsetos.md
Adicionada a opção "comer a joaninha" na história em português brasileiro.
> Add eat ladybug in portuguese version

- dutch/bos/donker-bos.md
- dutch/bos/struiken/in_de_struiken.md
> Added page

- english/marshmallow.md
- english/this-story-is-about-you/this-story-is-about-you.md
please review this, @casey-collab
> This story is about you

- english/animal/animal.md
> Added a new line to the english/animal/animal.md story.

- english/smores/smores.md
Add option to smores to look up wikipedia.
> Wiki smores

- portugues/titanic/arrumar/arrumar.md
- portugues/titanic/arrumar/middleware/404.md
> Add another option for the titanic story in portuguese

- english/marshmallow.md
> I couldn't really think of anything else to add

- english/rib-eye/rib-eye.md
> Add Camelot as option

- english/marshmallow.md
Please review this, @casey-collab".  I've added a link to a Michael Brecker concert.
> Add a link to a jazz concert

- english/magic/magic2.md
- english/magic2/magic2.md
- english/marshmallow.md
> New branch

- Philippines/salamat.md
> Modify Philippines Salamat.md

- finnish/loyly/loyly.md
- finnish/sauna.md
> add stay in sauna

- english/marshmallow.md
- english/universe-test/blaze_verse.md
@casey-collab how does this look to you?
> Added question "But what universe is this?"

- english/animal/animal.md
> changed animal story.

- english/blah-balh/blah-blah.md
> Add 'say something' option (Robot Chicken video link)

- english/can-i-get-you-a-ladder/can-i-get-you-a-ladder.md
I added a link from the ladder page back to the english marshmallow page
> Jays story addition

- Polish/ubranie/macasz/zupa/karmisz/karmisz.md
- Polish/ubranie/macasz/zupa/moczysz/moczysz.md
- Polish/ubranie/macasz/zupa/zupa.md
Ready to merge!
Calling @casey-collab
> Add story paths to broccoli soup

- english/wake-up/dessert-island/explore-island.md
- english/wake-up/wake-up.md
Add dessert island storyline to the wake-up storyline. Please review this, @casey-collab
> Dessert island

- korean/filibuster/filibuster.md
- korean/marshmallow.md
> Add filibuster in Korean directory

- english/destiny/destiny.md
> Add drink-beer and breakfast to destiny.md

- english/pick-up-blowtorch/stop-running/apologize.md
- english/pick-up-blowtorch/stop-running/eat-all/you-eat.md
- english/pick-up-blowtorch/stop-running/share-some/he-eats.md
> Add a story branch in which you learn the importance of sharing

- espanol/ayudantes/ayudantes.md
- espanol/canudos.md
> Add ayudantes story

- Italian/caramelle.md
- Italian/spuntini/spuntini.md
Hello dear bot Casey. Would you merge this, please?
> Aggiungo la mia storia

- english/advice_from_mother/advice_from_mother.md
> english: add a random line in the advice from mothers

- english/marshmallow.md
> Continue Frozen song

- english/bear/bear.md
> Keeping it punny

- Thai/Cuisine/TomYumKung.md
> I like Thai Green Curry better!

- german/Alkohol/alkohol.md
- german/Alkohol/bierflasche/bierflasche.md
- german/Alkohol/feuerzeug/Prost/Prost.md
- german/Alkohol/feuerzeug/feuerzeug.md
Please add my adventure paths, @casey-collab
> sobering up

- hindi/bollywood.md
- hindi/shraddha/shraddha.md
Adding to hindi dir. must be automatically merged.
> Adding Shraddha to hindi directory.

- Tamil/Thirukural.md
> doc: New Kural - Manly Effort/Aalvinaiyutaimai

- english/marshmallow.md
- english/schrodinger-cat/schrodinger-cat.md
Please review this change @casey-collab
> Add schrodinger's cat to the story

- espanol/canudos.md
- espanol/jordiHurtado/inmortal/inmortal.md
- espanol/jordiHurtado/jordiHurtado.md
- espanol/jordiHurtado/saberYganar/saberYganar.md
> ADD JORDI HURTADO TO THE ADVENTURE

- Gujarati/gujarati.md
> Added extra quotes

- english/liquid/liquid.md
- english/vaporization/vaporization
- english/vaporization/vaporization.md
Added a new file named 'vaporization' and linked it to liquid file.
> Committing my changes - Sithi

- english/poke-the-wall/choco-power-pill/choco-power-pill.md
Hi there!
Just added a quick line to the choco-power-pill.md for some experience going through a pull request!  Thanks for having this project setup!
> More details added to flame throwing arms pill

- english/talk_to_neighbour/man/mulder.md
This adds a connection to english/talk_to_neighbour/woman/scully.md to the man.md file
> Added direction to talk to woman at ../woman/scully.md

- english/amnesia/amnesia.md
> Add line to story

- espanol/ayudantes_accion/ayudantes_accion.md
- espanol/canudos.md
> More on spanish

- english/marshmallow.md
> Add pie chart link

- english/forest/fire/woods/camp/camp.md
- english/forest/fire/woods/follow/follow.md
- english/forest/fire/woods/woods.md
> Extended the forest storyline with two new options

- english/batman/batman.md
you can't deny this, @casey-collab !
> Double confirm Alfred is the Illuminati

- dutch/bos/ontvoering/meehelpen/plassen/lopen/lopen.md
- dutch/bos/ontvoering/meehelpen/plassen/lopen/vastzitten/vastzitten.md
> Change lopen.md and add vastzitten.md

- korean/call-mom/call-mom.md
[처음으로 돌아간다.](../marshmallow.md)
> Korean : back to the start 

- english/climbing/climbing.md
> Add option to dance

- english/ask-to-alice/ask-to-alice.md
> Add option to meditate

- english/marshmallow.md
- english/to-be-a-snowman/to-be-a-snowman.md
Adding a story to be a snowman
> Add: To be a snowman

- english/drink-beer/drink-beer.md
> Add options to english/drink-beer page

- norwegian/start.md
> Add two lines. Introducing me in the story.

- english/experience/blue-tunnel/love/love.md
> Beautiful woman asks question

- english/order-pizza/order-pizza.md
> Adds intriguing details on pizza orders, including tiki drinks.

- english/forest/shelter/shelter.md
> Add details to shelter

- Gujarati/gujarati.md
Extended Gujarati.md by adding a sentence.
> docs: Improved Gujarati.md

- Italian/scappare/scopri-oggetto/esamina-stanza/controlla-stanza/cerca-passaggio/cerca-passaggio.md
- Italian/scappare/scopri-oggetto/esamina-stanza/controlla-stanza/controlla-stanza.md
> Add overthrowing books looking for a secret door.

- french/dormir/reve-etrange.md
> add choice to do nothing in "reve-etrange"

- english/dream/fly/asia/japan/japan.md
- english/dream/fly/asia/japan/train/train.md
Not sure @casey-collab can merge this.  It shows a deletion, but I don't recall making one.
> Add new option to Japan.md, and some story to follow it

- english/get-away/get-away.md
- english/stairs/stairs.md
- english/tunnel/tunnel.md
Please review my additions @casey-collab
> Added two options after crossing the bridge

- english/day-dream/day-dream.md
- english/marshmallow.md
Add day-dream to English story
> Add day-dream to English story

- english/advice_from_mother/advice_from_mother.md
> Add more advice from mothers to the story.

- english/ismail-quora-profile/quora-profile.md
- english/marshmallow.md
> Add link quora

- english/triathlon/triathlon.md
> off to the gym

- Marathi/marathi.md
- Marathi/seattle/seattle.md
> Added a link to a resource for finding other Seattle-kars

- english/dimensions/dimension.md
- english/marshmallow.md
> Added story about dimension, added dimensions/dimension.md

- english/meditate/meditate.md
How does this work @casey-collab
> Add option to bake cookies

- english/marshmallow.md
- english/thunder-carrots/thunder-carrots.md
> Add new thunder carrots page to marshmallow page option

- english/impossible/impossible.md
- english/real-life/real-life.md
> Add "impossible" page

- english/tunnel/blind-search/blind-search.md
- english/tunnel/blind-search/small-hole/small-hole.md
- english/tunnel/continue/continue.md
- english/tunnel/tunnel.md
> Tunnel continue

- english/crazy/crazy.md
- english/ice-cream/ice-cream.md
> Add option to eat ice cream if you think you are going crazy

- english/new-movie/new-movie.md
Please review this, @casey-collab. Add link to official 'Try Everything' song from Zootopia movie
> Add link to official 'Try Everything' song from Zootopia movie

- espanol/canudos.md
- espanol/transcender/transcender.md
Added transcender.md, a new story page file, under the "espanol" folder (in spanish).
Also added respective link in canudos.md (spanish section landing page).
Please review, @casey-collab
> Add "transcender" story page in spanish section

- english/new-movie/new-movie.md
Adding reference to Shakira on the same line. So the merge conflict can be accepted by taking the latest changes as is. It is only addition of few characters.
> Add reference to Shakira for the song Try Everything.

- english/marshmallow.md
- english/submarine/greatDeep.md
> Added submarine joke

- espanol/cuco/cuco.md
- espanol/cucuyachi/cucuyachi.md
Following the guidelines for contributing to the story
a new segment was added. The story of the cucuyachi is
similar to the story of the cuco, but more regional.
> feat: add the story of the cucuyachi to the repo

- espanol/canudos.md
> Add josemcz history fragment

- english/Booyah/booyah.md
- english/call-spirit/call-spirit.md
> Add call a spirit option

- espanol/torre/huida/huida.md
> Add option to espanol/torre/huida

- english/cowboy/cowboy.md
- english/marshmallow.md
> Add Cowboy story

- english/marshmallow.md
> Add I forgot at the end of english/marshmallow

- Italian/colazione/colazione.md
> continue colazione

- ukrainian/look-around/look-around.md
- ukrainian/marshmallow.md
> Just a phrase was added

- Italian/finestra/mangiato/mangiato.md
> Add new ending for the dinosaur story

- english/bamboo/bamboo-shoots.md
- english/marshmallow.md
> updated storyline.... meets a panda!

- portugues_pt/colaborar.md
- portugues_pt/sorvete/sorvete.md
please, aceita ai bot do mal from hell @casey-collab
> minha humilde contribuição

- english/karaoke/karaoke/propose-to-her/propose-to-her.md
Please review, @casey-collab !
> Add some cowboys and make it a dream

- english/the-nights/the-nights.md
- english/the-nights/why/darts.md
> Add a second inspirational quote

- english/marshmallow.md
Added some introduction text to the English story.
> Add introduction to English story.

- Polish/ubranie/kieszen/gwizdek/zbadajgwizdek/zagwizdaj/zagwizdaj.md
- Polish/ubranie/kieszen/gwizdek/zbadajgwizdek/zagwizdaj/zlaka/zlaka.md
Add new option in polish branch - rest for a while
> Add new option - beautiful sight

- portugues/titanic/arrumar/arrumar.md
- portugues/titanic/arrumar/celine-dion/cantar.md
> colocar solucao viavel

- french/manger/continue/allumette/l-extinction.md
- french/manger/continue/continue.md
> Eating does not kill you

- english/bear/bear.md
> add beary good pun

- croatian/sljez.md
> added line to croatian adventure, @casey-collab

- english/dream_in_dream/go_back/drink_me.md
- english/dream_in_dream/inception.md
I am updating the story with a new file.
> updated storyline....inception to drink me

- Polish/przygoda/jedzenie/jedzenie.md
- Polish/przygoda/jedzenie/spanie/spanie.md
> And the story goes on

- english/becomemarshmallow/becomemarshmallow.md
- english/code-my-life/code-my-life.md
@casey-collab Added one line each to the above mentioned files.
> Add to becomemarshmallow.md and code-my-life.md files

- french/dormir/reve-etrange.md
J'ai practiqué mon français parce que je y suis aller tôt
> J'ajoute des plus mots

- english/advice_from_mother/advice_from_mother.md
- english/bear-story/bear-story.md
- english/bear/bear.md
On branch bear-story
Changes to be committed:
new file:   english/bear-story/bear-story.md
modified:   english/bear/bear.md
> Add bear-story and linked to already-existing bear page

- english/dog-sled/dogsled.md
- english/marshmallow.md
> Add option to take dog sled adventure, add new page

- english/shotgun/shotgun.md
> Add vivid description of chocolate sea.

- english/hermione/hermioneHere.md
- english/voldemort/voldemort.md
> Add voldemort branch and story addition

- french/dessine/chocolat/essayer-ouvrir-chocolat.md
> Ajout de l'option du lait

- english/stopbernie/stopbernie.md
> Add relfections regarding taxation and link to wikipedia article.

- english/marshmallow.md
- english/toasted/smores_pie.md
> Add smores files

- english/00-Life-of-this-world/Life of this world.md
> Added a new quote in Life of this world.

- german/Hilfeschrei/Vertrauen/insMaul/android/android.md
- german/Hilfeschrei/Vertrauen/insMaul/ins_maul.md
> add option android to kobold arc

- english/marshmallow.md
- english/new_warriors_record/new_warriors_record.md
> Elie shalhoub own adventure

- english/cowboy/cowboy.md
- english/texas/texas.md
Please review this request @casey-collab issues corrected.
> Reyes story

- english/sandwich/sandwich.md
- english/take-nap/cucumber-induced-nap.md
> Add Nap Option to Sandwich.md

- english/dead-or-alive/dead-or-alive.md
- english/schrodinger-cat/dead-or-alive/dead-or-alive.md
- english/schrodinger-cat/schrodinger-cat.md
> Added dead-or-alive page

- english/interstellar_quote/light.md
- english/marshmallow.md
@casey-collab, I think I accidentally added a new line or white space in the marshmallow.md which makes it a deletion in the file :( Not sure how to fix!
> Added Interstellar Quote

- english/friendly-person/friendly-person.md
- english/marshmallow.md
> Add my adventure

- Polish/przygoda/jedzenie/akap/kto-tam/kto-tam.md
- Polish/przygoda/jedzenie/akap/kto-tam/obrona/obrona.md
> New option in kto-tam.md

- espanol/jordiHurtado/inmortal/inmortal.md
> completed Jordi Hurtado story

- german/Einladen/Vorstellen/Hessen/aus_Hessen.md
- german/Einladen/Vorstellen/vorstellen.md
> Add hessian storyline

- english/Raiders/LetsgoRaiders.md
> Raiders batman

- english/shrooms/never-again.md
Hi @casey-collab
Under this guideline:
> Add a new option to an existing choice point, and link that option to an existing "page".
I added a new option to never-again.md:
[Wake up from this nigthmare?](../wake-up/wake-up.md)
> Add option to shrooms to wake up from nightmare.

- portugues/colaborando.md
- portugues/xvideos/xvideos.md
> Adding a sapeca history

- Gibberish/Gibberish.md
> added some more Gibberish

- dutch/welkom.md
> Change in Welkom text. Error with Iphone. It had no battery.

- portugues_pt/colaborar.md
> Add 'visitar Portugal link'

- english/bamboo/bamboo-shoots.md
> Update story in the file

- espanol/canudos.md
- espanol/realidad/realidad.md
> Agrega la continuación 'realidad'

- english/write-a-hiku/hiku.md
I wrote my very own haiku! Or, should I say, my very own hiku!
> Add a new haiku to /english/write-a-hiku/hiku.md

- german/ruderboot.md
> Add option to go back to language selection

- english/polar-bear-attack/polar-bear-attack.md
- english/polar-bear-attack/polar-bear-attack.md~
> polar bear

- hungarian/zuhanyzas/eves/eves.md
- hungarian/zuhanyzas/zuhanyzas.md
Please review this, @casey-collab". Make sure to leave the comment on the "Conversation" tab of the pull request, not the "Files changed
> Adding substory eves

- Gibberish/Gibberish.md
> made change to gibberish

- english/yoga/benefits/yoga_benefits.md
> I have added a warning to the benefits of yoga, to indicate it is not a panacea.

- english/garden/choose.md
- english/garden/peas/peas.md
> Added peas option to garden directory

- swedish/somna-om/somna-om.md
- swedish/start.md
> add somna-om as an option

- english/friendly-person/charades/charades.md
- english/friendly-person/friendly-person.md
> Add charades option to friendly-person.md and create charades.md file.

- english/marshmallow.md
- english/plugh/plugh.md
> Added Adventure

- english/froboznia/froboznia.md
Add more info regarding froboznia
> Add more info regarding froboznia

- hungarian/zuhanyzas/telefon/felvesz/felvesz.md
> Kutya beszalad a tusolóba

- english/powerball/lost-ticket/lost-ticket.md
- english/powerball/powerball.md
> Add lost ticket option to English/Powerball scenario

- portugues/spray/joaninha/comer/comer.md
- portugues/spray/joaninha/comer/dor-de-barriga/dor-de-barriga.md
> adciciona opçao dor de barriga em comer joaninha

- galician/dixital/dixital.md
- galician/dixital/mortos/mortos.md
> Add mortos to galicium

- english/schrodinger-cat/schrodinger-cat.md
- english/schrodinger-cat/undead/undead.md
> Add option to become an undead by not opening the box

- english/stopbernie/stopbernie.md
Please review my pull request @casey-collab
> Update bernie tax view page

- english/friendly-person/charades/charades-update/charades-update.md
- english/friendly-person/charades/charades.md
> Charades update

- english/disney/disney.md
- english/marshmallow.md
> Add Disney story

- english/friendly-person/friendly-person.md
- english/friendly-person/panic/panic.md
Add a "panic" choice to friendly-person.md
> Panic branch

- pig-latin/arshmallowmay.md
- pig-latin/iceray-ispiekray/iceray-ispiekray.md
Please review @casey-collab . Thanks!
> Addyay iceray ispiekray otay igpay atinlay

- espanol/muralla/apuntalar/abrid_fuego/abrid_fuego.md
- espanol/muralla/apuntalar/alto_al_fuego/alto_al_fuego.md
- espanol/muralla/apuntalar/apuntalar.md
> Continuación de la historia desde 'apuntalar'

- english/marshmallow.md
> add line about Accupunture

- english/friendly-person/wave/pinch/pinch.md
- english/friendly-person/wave/wave.md
> Add pinch option

- german/Hilfeschrei/Hilfeschrei.md
Add option "Aus dem Traum aufwachen und Oktoberfest besuchen" to page Hilfeschrei.md
> Add option

- english/karaoke/karaoke/ask-for-dance/ask-for-dance.md
- english/karaoke/karaoke/sing.md
> askForDance

- romanian/pitigoi/pitigoi.md
> Add the missing final words

- espanol/jordiHurtado/jordiHurtado.md
- espanol/jordiHurtado/muertedejordi/muertedejordi.md
> Mis cambios

- dutch/sms/sms.md
- dutch/welkom.md
add new option sms in welkom and add file sms
> add new option in welkom sms

- english/stopbernie/stopbernie.md
Waiting for upstream/english/[stopbernie](https://github.com/udacity/create-your-own-adventure/blob/master/english/stopbernie/stopbernie.md) to change before submitting to Casey-bot as per [Keeping a Fork Up-To-Date](https://classroom.udacity.com/courses/ud775/lessons/3105028581/concepts/33068495680923)
> added a line of text

- Italian/aiuto/aiuto.md
- Italian/aiuto/ho_fame/ho_fame.md
The user can ask for food to the man under the bed who is offering help
> Add "ho_fame" scenario. 

- espanol/torre/exploradores/estampida/estampida.md
- espanol/torre/exploradores/exploradores.md
I've added a new option to /espanol/torre/exploradores
> Aniadida opcion sobre lo que los exploradores vieron

- norwegian/faller/faller.md
- norwegian/start.md
> Faller i vannet

- english/health/Life-Quotes/life-quotes.md
- english/health/health.md
- english/marshmallow.md
> Health and Life Quotes

- espanol/huida/puerta.md
> Huida mas informacion

- english/art/art.md
> How we will know what time it is?

- english/light-fire/sprinkler/wonka-construction/surfthecrackers/surfthecrackers.md
- english/light-fire/sprinkler/wonka-construction/wonka-construction.md
> Added cracker surfing extension to Wonka Construction option

- english/gameofthrones/characters/shae.md
- english/gameofthrones/tyrion.md
- english/marshmallow.md
> Roolerzz story

- english/Canada/Canada.md
- english/marshmallow.md
- english/stopbernie/stopbernie.md
Added the option to move to Canada!
> Create /Canada/Canada.md, add to stopbernie.md + marshmallow.md

- english/sandwich/sandwich.md
> Add future plans for cucumber sandwiches

- swahili/swahili.md
- swahili/tembelea-jw-nukta-org/tembelea-jw-nukta-org.md
@casey-collab Please merge this.
> Initial commit of tembelea jw nukta org

- english/marshmallow.md
@casey-collab Please merge this.
> Commit marshmallow

- english/end/despair/despair.md
- english/end/end.md
- english/marshmallow.md
> Add initial english option "end"

- english/code/code.md
>  Added my story to code/code.md

- Gibberish/Gibberish.md
> edit: adding gibberish

- english/animal/animal.md
> Add lines about getting a hedgehog

- english/captain/captain.md
- english/ironman/ironman.md
- english/marshmallow.md
@casey-collab Please Check this out
> created new multi choice story.

- english/unicorn/existence/existence.md
- english/unicorn/existence/fakeporridge/descartes.md
- english/unicorn/existence/realporridge/porridge.md
> Extends English Keith line

- swedish/marshmallowen/marshmallowen.md
> Expand marshmallow story

- english/adipose/awake/awake.md
> added a new line

- english/00_8_Agent/The_name_is_Bond_Milton_Bond.md
- english/marshmallow.md
Update to marshmallow.md to include Special Agent link and new 00_8_Agent directory. Please review @casey-collab .
> 00 8 agent

- english/magicaladventure/avada_kedavra/avada_kedavra.md
- english/magicaladventure/decision_time/decision_time.md
- english/magicaladventure/expelliarmus/expelliarmus.md
- english/magicaladventure/surrender/surrender.md
- english/magicaladventure/wingardium_leviosa/wingardium_leviosa.md
- english/marshmallow.md
Hey @casey-collab can you review this new pull request?
> Test pull request 2

- espanol/torre/rey/rey.md
- espanol/torre/torre.md
> Add el rey

- english/swim/swim.md
> expanded swim story

- english/marshmallow.md
- english/vote-the-president/bernie/Bernie.md
> Bernie Sanders wins the presidency

- english/lucidream/luciddream.md
> Add whirling dervish to lucid dream

- espanol/cansancio/cansancio.md
- espanol/canudos.md
Hey @casey-collab, nearly there. Check it out and let me know.
> Add option Spanish

- espanol/transcender/destino.md
- espanol/transcender/destino/destino.md
- espanol/transcender/transcender.md
> jCruz patch 1

- english/crazy/crazy.md
> correct the spelling of krazy

- Thai/Cuisine/TomYumKung.md
- Thai/travel.md
> Add travel

- english/yoga/mind/yoga_mind.md
> Add focusing on breathing

- dutch/over-het-hek/sleutel/wereld/welkeWereld.md
> add to welkeWereld

- english/wake-up/wake-up-again/dream2/dream2.md
> Add more info from marshmallow chief about sticks

- english/unicorn/existence/fakeporridge/descartes.md
> Add sentence to english/unicorn/existence/fakeporridge/descartes.md

- english/quote-of-the-day/life/life.md
Kindly review this, @casey-collab
> Added a spiritual quote

- english/00-Life-of-this-world/Life of this world.md
- english/dimensions/dimension.md
> Add link to chess and bear-story from dimension

- Gujarati/gujarati.md
> Add my favourite Gujarati proverb

- german/Dorf/Haupthaus/haupthaus.md
- german/Dorf/Tempel/tempel.md
- german/Dorf/Werft/werft.md
- german/Dorf/dorf.md
- german/ruderboot.md
ADDs new adventure "Dorf" including 4 files and a solution to get back
Features optional background music
> MODs ruderboot.md to link to the new adventure "Dorf"

- english/love-udacity/love-udacity.md
Remove link (as final page shouldn't have a link) and changed text.
> docs: Add free vs nano

- english/schrodinger-cat/undead/undead.md
Throw this in there @casey-collab
> Add option to change decision to open box

- espanol/torre/rey/dormidos/dormidos.md
- espanol/torre/rey/rey.md
> Agregar la opción de que el ejército estuviera dormido

- english/unicorn/no/no.md
Additional detail about the no-cigarette-for-unicorn scenario.
@casey-collab please review!
> Add detail about decision to deny cigarette to unicorn.

- english/marshmallow.md
> Marcel needs a new pair of shoes

- english/I'm-batman/batman.md
- english/I'm-batman/batmetal/batmetal.md
- english/batmetal/batmetal.md
> Added batmetal option to I'm batman

- english/stopbernie/stopbernie.md
> Add maximum income article link

- english/drink/drink.md
- english/marshmallow.md
> add mystery drink

- english/ghostbusters/ghostbusters.md
> Add experiment plotline

- english/yoga/benefits/yoga_benefits.md
> add to benefits of yoga

- english/love-udacity/love-udacity.md
> Add never stop learning

- english/marshmallow.md
- english/run_out_the_door/run_out_the_door.md
> Added new choice to run out the door in marshmallow

- swedish/marshmallowen/marshmallowen.md
- swedish/titta-ut/macka/macka.md
Added option to eat marshmallow after sandwich @casey-collab
> Added option

- portugues/colaborando.md
- portugues/futebol/futebol.md
> ptbr-futebol

- english/love-udacity/love-udacity.md
- english/quit/quit.md
> new chapter

- english/tunnel/stop/stop.md
- english/tunnel/tunnel.md
> Add an option to stop and meditate to the tunnel storyline

- espanol/noticias/noticias.md
- espanol/noticias/orlando/orlando.md
> Adionar mi historia triste a la aventura.

- Italian/scappare/cercare-uscita.md
- Italian/scappare/riparare/ripari.md
> add option to repare bottle in italian story

- Italian/colazione/colazione.md
> add sleeping pills to Italian/colazione

- english/LifePuzzle/LifePuzzle.md
> Add beer and sing option to life puzzle story

- english/LifePuzzle/LifePuzzle.md
> Remove question mark from Quora option in LifePuzzle

- romanian/nalba.md
- romanian/vrajeala/vrajeala.md
> feat: Intra in scena CRBL cu Petre

- english/LifePuzzle/LifePuzzle.md
> Add Justice League option to LifePuzzle story

- english/computer-window/computer-window.md
- english/marshmallow.md
> Add story about computer looking out of the window

- english/start-dancing/startDancing.md
> Hot fruit option for the party

- arabic/learn/learn.md
Please check this @casey-collab.
> Add Khan Academy link to arabic learn.md

- english/LifePuzzle/LifePuzzle.md
> Add Tweeting functionality to the story

- english/marshmallow.md
- english/meditate/meditate.md
- english/write-a-symphony/symphony.md
add symph branch, links from marsh + meditate
> Beethoven2

- Italian/caramelle.md
- Italian/passeggiare/passeggiare.md
Ho seguito il corso e come richiesto nell'ultima lezione ho creato la mia storia
> Aggiunta la storia Passeggiare in Italiano

- english/bored/bored.md
- english/jazz-guitar/jazz.md
> Add some Jazz to the story

- english/computer-window/computer-window.md
> Add wikipedia option to the computer story

- english/Monty-Python/search.md
Extended the Monty Python story to include the black knight
> Add to monty python tale

- english/dig/dig.md
> Add three sentences to dig.md

- portugues_pt/praias/solemar.md
> New beach Boracay.

- english/Full Metal Alchemist/fma.md
- english/working/working.md
> Add a working option to english story

- german/Fragen/fragen.md
> Add one line

- english/explore-outside/explore-outside.md
> Add smell the roses to explore outside

- hindi/Sunny_Deol/sunny.md
> added URL for Sunny Deol as https://www.google.com

- english/yoga/habit/yoga-habit.md
> Added another tip for developing yoga as a habit.

- english/schrodinger-cat/dead-or-alive/dead-or-alive.md
- english/schrodinger-cat/dead-or-alive/luck/what-is-luck.md
> Lucky or not

- english/cricket-rules/cricket-rule-book.md
- english/cricket/cricket.md
> 2 modified files

- Philippines/movie/movie.md
- Philippines/salamat.md
> Pull request to add new choice in salamat.md

- swedish/midsommar/midsommar.md
- swedish/somna-om/somna-om.md
> Add midsommar story piece and adjust somna-om

- english/coffee/chess/chess.md
- english/coffee/chess/three-dimensional-chess/three-dimensional-chess.md
Add option for three-dimensional-chess to english/coffee/chess/
> Jfc adventure

- english/sing/campfire_songs/rootbeer_song.md
- english/sing/continue/continue-to-sing.md
> Please review my pull request

- english/great-tasmanian-adventure/great-tasmanian-adventure.md
- english/marshmallow.md
> Add Great tasmanian adventure

- Thai/Activities/Hiking.md
- Thai/travel.md
> Dream of hiking in Thailand

- english/vote-the-president/trump/trump-floyd-the-wall/thewall.md
- english/vote-the-president/trump/trump.md
Hello @casey-collab I made an addition to the stoty, hope you like it. Regards.
> ADD Trump-Floyd-The-Wall

- english/vote-the-president/hillary/Hillary.md
> Add #NeverTrump message for Hillary Clinton

- korean/marshmallow.md
- korean/study/study.md
> add study option

- english/chillmusic/chillmusic.md
@casey-collab I know I shouldn't use YouTube links, but I'll try to make another change with my own page.
> Add piano transcription of Blue Danube

- espanol/rezando/plaza/casamiento/casamiento.md
- espanol/rezando/plaza/casamiento/inesperado/inesperado.md
> Añadir sorpresa inesperada para Beatito

- english/132-days-ago/132-days-ago.md
> Just want to get over with this

- english/say-my-name/say-my-name.md
> Add youtube link to Saul Goodman's best line from Breaking Bad

- english/happy-robot/happy-robot.md
> Umvegas changes

- espanol/angeles/angeles.md
> Add changes to angeles link.

- english/mad/mad.md
- english/marshmallow.md
> Buildhope adv

- german/Korallen/Hoehle/Unterwasserstation/Person/GespraechMitHoehlenmann/Gespraech.md
- german/Korallen/Hoehle/Unterwasserstation/Person/Person.md
> Jensbranch

- english/magic/magic.md
> Extend story - english/magic/magic.md

- english/mysterious-pool/glowing-eyes/caught_up/plants.md
- english/mysterious-pool/glowing-eyes/cave/blind.md
- english/mysterious-pool/glowing-eyes/glowing-eyes.md
- english/mysterious-pool/glowing-eyes/tuna/tuna.md
once we spot the glowing eyes underneath the water
> Add continuation to the adventure 

- english/vote-the-president/trump/trump.md
> Add statement to Drumpf option

- english/Happy/happie.md
- english/marshmallow.md
> Happiness in Life

- latvian/grab-lighter/grab-lighter.md
Short update on the Latvian story.
> Latvian story update

- english/iot/intro.md
- english/iot/scan-network/scan-network.md
> Add scan network option to iot story

- english/batman/batman.md
> Update Batman legacy

- english/bamboo/bamboo-shoots.md
Added relevant changes in the bamboo shoot story!
> Line 8 and 10 are added for the chase

- vietnamese/TansStory/mystory.md
- vietnamese/kechuyen.md
Please review my file @casey-collab
> Add my story to the directory

- english/appear-on-falkors-back/falkor.md
> Add story about man on flying carpet

- english/mysterious-pool/giant-bubble/giant-bubble.md
- english/mysterious-pool/giant-bubble/into-the-bubble/breathe-again.md
> Add options to giant bubble branch of story

- english/boston/boston.md
Added an option for the reader to go back to sleep.
> Add back to sleep option

- english/lego/lego.md
> Add Pokemon lego and fix a typo

- portugues/colaborando.md
- portugues/historia/fim.md
Add new link to colaborando.md that leads to historia/fim.md file created
> Add cool ending story

- english/talk_to_neighbour/woman/go-with-scully/hanging-with-scully/hanging-with-scully.md
> Add option to take a plane to Vegas

- finnish/sauna.md
> Add description of enjoying beer outside of sauna.

- espanol/canudos.md
> Agregar opción de desmayo a historia principal

- english/swim/swim.md
@casey-collab please review this
> Added link to superpowers from swim

- portugues/colaborando.md
- portugues/jc/jc.md
> My own adv

- german/schwimmen/hunger/bierkeller/bierkeller.md
- german/schwimmen/hunger/hunger.md
> added Bierkeller story

- english/friendly-person/wave/wave.md
> Add "What will you do next?" to wave.md

- english/the-slayer/freddie/freddie.md
Please review my updated change, @casey-collab.
> docs: "Death of a Marshmallow"

- lithuanian/uzsimerkti/vejas.md
- lithuanian/uzsimerkti/zemuoges.md
- lithuanian/uzsimerkti/zemuoges/zemuoges.md
> Added žemuogės

- french/manger/continue/continue.md
- french/manger/continue/vomis/vomis.md
Hey @casey-collab can you add my contribution to the story
> Change continue.md to add possibility to throw up

- english/forest/fire/fight/fight.md
> Add bee chase and honey gathering to bear fight

- english/doug-adams/doug-adams.md
- english/marshmallow.md
> Add Doug Adams story

- turkce/catalla-kaz/metali-cek/metali-cek.md
> Add recursion to turkish story

- german/Wurstwasser/wurstwasser.md
- german/ruderboot.md
Please review this, @casey-collab I promise it is tasty!
> Wurstwasser

- english/00_8_Agent/The_name_is_Bond_Milton_Bond.md
> forking on Special Agent

- english/marshmallow.md
> Give choice to listen to Too Many Puppies

- french/dessine/caramel/mangez-caramel.md
- french/dessine/porte.md
> La porte de caramel

- english/DC-Comics/Arrow/arrow.md
- english/DC-Comics/epic_DC_Character.md
I added a new vigilante to the DC comics section, Green arrow. Check it out for me and see if it is okay to merge, @casey-collab
> Add Green Arrow for Epic DC; Add relative link

- espanol/muralla/abrir/abrirsoldados/abrirsoldados.md
> Llamar al capitan

- serbian/burekKrem/krem.md
- serbian/start.md
> Burek s's krem

- english/is-this-a-dream/is-this-a-dream.md
- english/pizza/pizza.md
> Create pizza.md file and link from is-this-a-dream

- english/lovecraftian/shoggoth.md
- english/plugh/maze1/maze1.md
> Add new option to plugh maze adventure

- english/batman/batman.md
> Add line to batman.md

- Chinese/A_htx/黄腾霄.md
- Chinese/大话西游.md
> Xinyuehtx patch 2

- catala/panic/panic.md
> Add link to troll from panic page

- Chinese/Donggewudi/Donggeheiheihei.md
> Add a line in 东哥嘿嘿嘿

- english/wikipedia/wiki.md
> Add sentence on creating channel on YouTube

- hindi/Bhagat_Singh/bhagat_singh.md
> Add the Great Bhagat Singh

- Gibberish/Gibberish.md
> Modify Gibbersh Story to create awesomesomeness!

- Italian/antonio_conte/antonio.md
- Italian/caramelle.md
> Antonio conte

- german/schwimmen/insel/fs_innen/service/service.md
> add german drinking line in service.md

- german/Stopfen/stopfen.md
- german/Stopfen/ueberlegen/ueberlegen.md
> Add to stopfen

- Philippines/duterte/duterte.md
- Philippines/salamat.md
> add story to Philippines

- norwegian/faller/faller.md
> Add new line to story.

- Tamil/Thevaram/thevarm.md
- language.md
Could you please merge this content to your master branch.
This branch contains a new page to read about Thevaram a classic Tamil literature
> Adding new page for Thevaram in Tamil

- english/forest/pockets/pocketsagain/pocketsagain.md
The page /master/english/forest/shelter/shelter.md
was linked previously in /master/english/forest/forest.md
> Link to make a shelter from the parachute

- english/starcraft2/starcraft2.md
I extended the Star Craft 2 story by a few lines. Please take a look.
> Add some lines to extend star craft 2 story

- portugues/colaborando.md
- portugues/youtube/minecraft.md
Revise isto, @casey-collab
Alterado colaborando.md
Adicionado /youtube/minecraft.md
> Nova historia

- english/33hours/explore-room/under-carpet/remove-floorboard/remove-floorboard.md
- english/33hours/explore-room/under-carpet/under-carpet.md
Added an option to the carpet path of the 33hours adventure
> Floorboard

- english/breakfast/breakfast.md
> Add trip to the supermarket

- hindi/bollywood.md
> Add Alia Bhatt to Bollywood

- english/00_8_Agent/The_name_is_Bond_Milton_Bond.md
> Add Tiger/Bear option   Please review this, @casey-collab

- english/code/code.md
> add my story in code.md

- english/hold_the_door/hodor.md
- english/marshmallow.md
> Add hold the door

- Philippines/bagong simula/ipis/durog/durog.md
- Philippines/bagong simula/ipis/ipis.md
Pull request for new story, durog. @casey-collab
> Ipis chronicles - New story

- english/forest/forest.md
Please review @casey-collab  (add way to get out of the forest and back to the beginning.)
> New arc - forest

- english/watched/watched.md
> Garamizo patch 1

- english/forest/fire/woods/follow/follow.md
- english/forest/fire/woods/follow/shoreline/shoreline.md
> Add shoreline and edit follow.md

- english/marshmallow.md
- english/philosophy/questions.md
> Add new part to story

- english/eatmarshmallow/marshmallowland/marshmallowland.md
> Add a line to the story.

- english/eating-walls/find-a-toilet/door/shake-hands/shake-hands.md
Is it a ghost? What do you think, @casey-collab ?
> Add ghost-like quality to handless thing

- english/forest/scream/run/run.md
Please check this out and review this, @casey-collab!
> Add new entry with parachute option

- english/forest/drag/drag.md
- english/forest/drag/light/light.md
- english/forest/drag/stay/stay.md
> After life

- english/choose-pill/choose-pill.md
> Add open a pill option

- english/chocopool/bananaboat/bboat.md
- english/chocopool/choco.md
- english/chocopool/hazelnuts/hazel.md
- english/marshmallow.md
Added the chocolate pool story
> Modifiedstory

- english/karaoke/karaoke/drop-mic/drop-the-mic.md
- english/karaoke/karaoke/sing.md
Please review this story choice, @casey-collab
> add drop-the-mic story choice

- romanian/nalba.md
- romanian/panda/marmota.md
> Add marmot

- english/amnesia/amnesia.md
> Add link to ASDREAMS on amnesia.md

- english/revolution/revolution.md
- english/watched/watched.md
> Add revolution option and file

- english/play-gta5/play-gta5.md
> Add line about Franklin

- espanol/jordiHurtado/jordiHurtado.md
I just made this little introduction to the 3 different options
> an introduction to the options

- english/dentist/ouch.md
> Metal teeth

- Gujarati/gujarati.md
> Add mine favourite proverb, Please review this, @casey-collab

- arabic/salamoAlikom.md
> Please review and merge

- english/Monty-Python/search.md
> Add the Knights who say Ni and a shrubbery

- portugues/colaborando.md
> Gus changes

- korean/marshmallow.md
- korean/restroom/restroom.md
> Add restroom

- english/grue/grue.md
> add description of grue stench

- english/glimmering-portal/glimmering-portal.md
- english/impossible-adventure/start/start.md
- english/new-exit/new-exit.md
- english/run_out_the_door/run_out_the_door.md
> Requesting auto-merging

- korean/instagram/insta.md
- korean/marshmallow.md
> Add instagram story

- english/marshmallow.md
- english/walrus/walrus.md
> Added my walrus section

- english/bored/bored.md
- english/learn_japanese/japanese.md
Adding a section in bored that allows you to study Japanese and then
go to Japan where you will then need to use that Japanese.
> feat: adding new path to story

- english/android/marshmallow6.0.md
- english/marshmallow.md
> Add update to Android Marshmallow 6.0

- catala/catala.md
- catala/correr/correr.md
> Add new option 'correr' to catala/catala.md

- english/android-v6/use-android-v6.md
Please give this a once over, @casey-collab.
> Added the quest for the nougat

- Polish/przygoda/jedzenie/korwin/korwin.md
- Polish/przygoda/jedzenie/korwin/prezent3/muszka.md
> Add muszka for korwin option

- german/Fragen/fragen.md
> Add sentence to Fragen

- english/guitar/guitar.md
- english/guitar/shred/shred.md
Please review this, @casey-collab!
> Add option to shred on the guitar

- english/walrus/walrus.md
> Add next lyric for Mr. Walrus

- english/forest/fire/woods/follow/shoreline/river/river.md
- english/forest/fire/woods/follow/shoreline/shoreline.md
- english/forest/fire/woods/follow/shoreline/wait/wait.md
> Jins version

- turkce/catalla-kaz/kus/kus.md
- turkce/catalla-kaz/kus/kusmaya-devam/kusmaya-devam.md
> Kusmaya devam et

- english/marshmallow.md
- english/unnatural_door/unnatual_door.md
- english/unnatural_door/unnatural_door.md
> Unnatural door

- english/Monty-Python/search.md
> Add black knight battle scene from YouTube

- english/marshmallow.md
- english/mean-stack/mean.md
> MEAN stack contribution to the story by DE.

- german/schwimmen/hunger/bierkeller/bierkeller.md
Added a back option if you were stuck in the Bierkeller
> Back bierkeller

- english/marshmallow.md
- english/stargazing/stargazing.md
> Add stargazing story

- english/marshmallow.md
- english/north/north.md
> Mattbranch

- english/music/add_music.md
- espanol/musica/grupo_mariachi.md
> Add link to song 'Soy Colombia' in youtube

- english/steelers/steelers.md
> Add to storyline

- english/concert/concert.md
- english/marshmallow.md
> Find yourself with Rolly Neonic!

- english/enjoysoda/enjoysoda.md
- english/glimmering-portal/glimmering-portal.md
- english/sweat/sweat.md
> New addition to story

- english/iot/scan-network/scan-network.md
> Add 2's complement Raspberry Pi lines to scan-network.md

- english/learn-mandarin/learn-mandarin.md
- english/marshmallow.md
> add learn-mandarin

- Italian/caramelle.md
- Italian/lavorare/cazzeggiare/cazzeggiare.md
- Italian/lavorare/lavorare.md
Please review this lavorare story, @casey-collab
> My own story

- english/marshmallow.md
> Add news to marshmallow.md

- finnish/loyly/loyly.md
Please review this pull request, @casey-collab
thx
> Add a link back to the first page

- english/coffee/bed/bed.md
- english/coffee/coffee.md
> Add Bed path to story

- german/Alkohol/Schatzkarte/Schatzkarte.md
- german/Alkohol/alkohol.md
> Add part of my story

- Gujarati/DhoklaStellarFafda~/CS.md
> Added a line.

- espanol/canudos.md
> Sabores de arepas.

- english/combatration/combat_ration.md
- english/continueded/continueded.md
- english/resurrect/resurrect.md
> Continue 2spooky.

- english/magic/magic.md
> Add story line to magic.md

- english/marshmallow.md
> Add reflection on your Fiat 500

- english/marshmallow.md
- english/meaning-of-life/meaning-of-life.md
> docs: First commit meaning of life

- english/forest/drag/roaming_spirit/beer_sandwich/beer_sandwich.md
- english/forest/drag/roaming_spirit/roaming_spirit.md
> Modify roaming_spirit

- espanol/Mutantes/Mutantes.md
> Continue the mutant story

- english/adipose/adipose.md
> Add-Adipose: Mot waking - Mom's Non Mellow Advice

- espanol/canudos.md
- espanol/inverlandia/castillo.md
- espanol/inverlandia/inverlandia.md
> History collaboration,  by Miguel Fernandez

- portugues_pt/mundo/voltaaomundo.md
> Adicionar ideia a portugues_pt/mundo/voltaaomundo.md

- german/beten/beten.md
- german/ruderboot.md
> add beten option

- russian/garden/garden.md
> Add garden story sentences

- english/marshmallow.md
- english/wand/wand.md
add my story wand @casey-collab
> Title is add my story wand @casey-collab

- portugues/historia/fim.md
> Alterando o fim da história

- english/bake-cookies/cookies.md
> for those who don't know about cookies

- english/sleep/more-sleep/expired-milk/expired-milk.md
> Add run_out_of_door option to expired-milk

- afrikaans/braaivleis/braaivleis.md
- afrikaans/kos.md
Added to the sparse Afrikaans section
> braaivleis added to the afrikaans food list

- catala/aixecar/aixecar.md
- catala/aixecar/menjar/menjar.md
> Add new possible path to catalonian adventure 'aixecar'

- croatian/sljez.md
> Add rain line.

- english/lovecraftian/shoggoth.md
> Added line to end about eyes staring as you get eaten.

- english/lovecraftian/shoggoth.md
> Added this hurts.

- espanol/canudos.md
- espanol/resines/resines.md
> continue my history

- french/dessine/miel/forest/approcher.md
- french/dessine/miel/forest/chantilly/asperge.md
Hope that's ok for bot merging!
> ModifsNicoKiaru-NoDeletions

- english/duck/duck.md
> added stuff to duck.md

- english/necklace/necklace.md
> Add my part to the story

- english/marshmallow.md
- english/time-machine/time-machine.md
> Add time machine travel adventure

- english/marshmallow.md
- english/slapa-da-bass/slapa-da-bass.md
> Add slapa-da-bass option

- english/gtd/gtd.md
> feat: Add link to Back to Work podcast

- language.md
> add C# option

- english/painting/Another_World/another_world.md
- english/painting/painting.md
> Update the story

- Gibberish/BooBahTahTah/BoBah.md
- Gibberish/Gibberish.md
- Gibberish/HorkPorkDork/horky.md
- Gibberish/NiNi-sigh/NiNi.md
Add HorkPork, BooBah, and NiNi options to gibberish.md
It's good stuff.
> Update Gibberish Story

- portugues/cogumelos/cogumelos.md
- portugues/colaborando.md
> Add mushrooms story

- english/chocolateOrSleep/chocolateOrSleep.md
@casey-collab can this be merged?
> add option drive the cat ... to ChocolateOrSleep.md

- Philippines/salamat.md
> Add a line of cebuano text

- english/Soccer/soccer.md
- english/marshmallow.md
> Add new story about soccer by yt

- punjabi/punjabi.md
> Add link to Milkha Singh's wiki page

- serbian/start.md
Continuing Serbian start.md story
> Dosetio se šta bi mu najlbolje prijalo

- english/unicorn/no/no.md
- english/unicorn/no/super-vet/super-vet.md
> Added new option for english/unicorn/no

- english/forest/scream/climb/climb.md
- english/forest/scream/scream.md
> Add /forest/scream/climb storyline

- serbian/start.md
> Odluka je pala

- english/learn-mandarin/learn-mandarin.md
> Added the phrase 'Ni Hao' to the mandarin.md

- espanol/canudos.md
- espanol/libro/libro.md
> feat: Add libro story to spanish version

- english/forest/scream/run/run-again/run-again.md
- english/forest/scream/run/run.md
> Add english/forest/scream/run/run-again/ storyline

- korean/cry/cry.md
Please review this added option @casey-collab
> Add option to sleep in crying state

- french/dessine/miel/forest/fuite/champs-de-fleurs/champs-de-fleurs.md
- french/dessine/miel/forest/fuite/champs/champs-de-fleurs.md
- french/dessine/miel/forest/fuite/fuite.md
> Champs de fleurs

- english/33hours/explore-outside/explore-outside-east/explore-east.md
- english/33hours/explore-outside/outside.md
> Explore more

- german/schwimmen/insel/fs_aussen/fragen/fragen.md
- german/schwimmen/insel/fs_aussen/fs_aussen.md
> Add new part of the story after fs_aussen.

- Italian/caramelle.md
- Italian/luce/luce.md
> feat(italian): add new option

- Philippines/meow/meow.md
- Philippines/salamat.md
Added a branch out story as narrated in cat. Thanks Udacity!
> Meow meow meow!

- english/lawn-mower/lawn-mower.md
> Add new sentence to lawn-mower

- english/marshmallow.md
- english/persistent/persistent.md
> New story merge

- english/time-machine/time-machine.md
> Add a warning line to the time-machine page.

- english/light-fire/fire.md
> I change my_story.

- english/light-fire/fire.md
> I think there is no conflict and now I am able to merge.

- english/time-machine/time-machine.md
> Add time machine narratives.

- english/work-out/run/kuddos-for-trying/kuddos-for-trying.md
- english/work-out/run/marathon/marathon.md
- english/work-out/run/run.md
Add option after selecting "run"
> Merge my-changes

- english/zork/zork.md
> update zork to be udacious

- german/Fragen/fragen.md
> Add new option and link to an existing page.

- german/Hilfeschrei/Vertrauen/insMaul/gloeckchen/klingeln/kreuzfahrt/kreuzfahrt.md
> Add existing option "schwimmen" to page "kreuzfahrt"

- english/unicorn/no/super-vet/read-card/read-card.md
- english/unicorn/no/super-vet/super-vet.md
> Equine aid

- catala/dormir/bufar/bufar_arros.md
> Add line to bufar arros

- english/dog_finger/dog_finger.md
- english/marshmallow.md
Add dog_finger folder and dog_finger.md file in english folder
> Add a sentence, the story the Choking Doberman, to marshmallow.md

- portugues/colaborando.md
- portugues/simpatia/incenso/incenso.md
- portugues/simpatia/resolver/resolver.md
- portugues/simpatia/simpatia.md
\"Revise isto, @casey-collab\"
> incluindo história.

- portugues_pt/colaborar.md
- portugues_pt/italia/italia.md
Please review this, @casey-collab, thanks.
> adding my history 

- english/marshmallow.md
- english/tos/tos.md
> Add Tree of Savior and Ragnarok online description.

- portugues_pt/italia/italia.md
> new place to visit: coliseu

- hindi/art-of-living/art-of-living.md
> Hindi Correction

- english/mysterious-pool/glowing-eyes/caught_up/plants.md
Please give this a look, @casey-collab
> Programming jokes

- english/valarmorghulis/valarmorghulis.md
> docs: The one and only Khaleesi

- english/marshmallow.md
Please add my changes, @casey-collab
> "Add android course to story"

- english/crazy/crazy.md
> Add two lines to crazy.md

- Philippines/bob-ong/bob-ong.md
- Philippines/salamat.md
> My filipino story

- german/Essen/Schokolade/Schokolade.md
- german/Smartphone/Internet/Internet.md
> Add a new story about eating chocolate

- serbian/burekMeso/burekMeso.md
- serbian/burekMeso/istrcao/istrcao.md
- serbian/burekMeso/okrenuo/okrenuo.md
> Add two new choices in burekMeso. Add corresponding pages.

- english/alchemy/alchemy.md
please review this @casey-collab
> Add a twist to the story

- english/marshmallow.md
- english/pictionary/pictionary.md
@casey-collab please review my changes.
> Add teach google pictionary option

- english/madness/writhe/camera/chicken.md
- english/madness/writhe/eat/chicken.md
- english/madness/writhe/writhe.md
Extend the english/madness/writhe story ark
> Writhe modify

- english/marshmallow.md
Add link to a series of video interviews
> Jason Calacanis

- english/hospital_bed/hospital_bed.md
- english/lovecraftian/shoggoth.md
- english/pinch/pinch.md
- english/universe-test/blaze_verse.md
- english/vegas/fear-loathing-las-vegas.md
> Hospital bed

- Italian/caramelle.md
- Italian/smartphone/facebook/facebook.md
- Italian/smartphone/instagram/instagram.md
- Italian/smartphone/smartphone.md
Added a smartphone option, with a couple of child options, in the italian tree.
> Nerd option

- portugues/cogumelos/cogumelos.md
- portugues/colabora/colaborar.md
- portugues/cria/melhor.md
- portugues/cria/muito_melhor/muito_melhor.md
Lines were added to the Portuguese stories. Even though it shows that it has been deleted no deletion has been done to the original files
> Portuguese Adventure add-ons

- english/luke-skywalker/luke-skywalker.md
- english/luke-skywalker/starwars7/duh.md
- english/luke-skywalker/starwars8/Wait-for-8.md
- english/star-wars-spoiler/star-wars.md
Add  Luke Skywalker interview in a post-Force Awakens world.
> Luke-Skywalker

- german/Alkohol/feuerzeug/Prost/Prost.md
> Added a story sentence, hopefully the story makes sense.

- english/talk_to_neighbour/talk_to_neighbour.md
> Add 'what happen to our emotion' before talking to neighbour

- english/lego/lego.md
> Add Harry Potter

- arabic/salamoAlikom.md
> added recela le bamer

- espanol/montanas/montanas.md
> Add sentences about mountain story (espanol)

- espanol/canudos.md
- espanol/maquina/tiempo/maquina_del_tiempo.md
> Add sentences about time machine (espanol)

- english/run_out_the_door/run_out_the_door.md
> added more description to add urgency for escape

- english/Full Metal Alchemist/fma.md
> add one line to fma.md

- english/chillmusic/chillmusic.md
> add Moonlight shadow

- english/swim/swim.md
content: our hero now can swim safely
> Syscero adventure

- english/philosophy/questions.md
> Add an answer to a question

- english/alchemy/alchemy.md
- english/incantation-forrest/incantation-forrest.md
> add option to enter Incantation Forrest

- english/vote-the-president/trump/trump.md
> Added line to trump.md

- Polish/przygoda/jedzenie/biznes/biznes.md
- Polish/przygoda/jedzenie/biznes/cukrzyca/cukrzyca.md
- Polish/przygoda/jedzenie/biznes/podlakorp/podlakorp.md
> smierc totalna

- english/captain/captain.md
after already voting for Captain America.
> Add the ability to change vote to Iron Man from Captain America

- english/captain/captain.md
- english/jacket/marshmallow-jacket.md
> Jacket change

- english/hospital_bed/hospital_bed.md
Plz review this, @casey-collab
> changed existential link description

- english/vacuum/vacuum.md
> Added story about the vacuum of the Universe

- afrikaans/biltong/biltong.md
- afrikaans/koeksisters/koeksisters.md
- afrikaans/kos.md
> biltong and koeksisters added to the afrikaans food list

- english/play-music/colombianMusic/colombianMusic.md
> trying to merge my fork to the master

- english/marshmallow.md
> add pug person type to marshmallow story

- english/magic-device/magic-device.md
- english/prison/prison.md
Added a magic device of yet unknown powers. Please, @casey-collab, have a look and merge it up.
> Magic device

- swahili/marshmallow.md
Nimeongeza sentensi katika hadithi yako. Merge kama umependa vile hadithi itaendelea tafadhali. 👍 
>  Add a sentence to the swahili story

- english/work-out/personal-trainer/personal_trainer.md
- english/work-out/weights/weights.md
- english/work-out/work-out.md
> Add personal trainer story to adventure

- english/forest/eat/eat.md
> Chase the squirrel

- english/schrodinger-cat/dead-or-alive/dead-or-alive.md
- english/schrodinger-cat/dead-or-alive/immanentize-the-eschaton/immanentize-the-eschaton.md
> Feat: Add immanentizing the eschaton.

- english/marshmallow.md
> More junk added

- portugues/colabora/fork/comdiferencas/diff/pull/descobre/descobrir.md
- portugues/colabora/fork/comdiferencas/diff/pull/pull.md
Adding a path to study English using Duolingo, when having a rejecting pull request for a language error
> Adding a path to study English using Duolingo

- korean/instagram/insta.md
> ADD mashmellow to instagram

- english/happy-robot/happy-robot.md
- english/quick_draw/AI_Pictionary.md
- english/quick_draw/AI_Pictionary.txt
> QuickDraw-AI Pictionary

- english/garden/choose.md
- english/garden/jasmine/jasmine.md
> Added jasmine to garden directory

- english/time-machine/time-machine.md
Add time travel option to travel back to colonial America and meet our founding father Alexander Hamilton.  Link takes you to Lin Manuel Miranda performing at the White House.  Please review this, @casey-collab
> time travel to see Hamilton

- english/advice_from_mother/advice_from_mother.md
> Add more to vegetable advice

- Philippines/salamat.md
- Philippines/tara/bintana/bintana.md
- Philippines/tara/gamit/gamit.md
- Philippines/tara/pinto/pinto.md
- Philippines/tara/tara.md
Hey @casey-collab review this.
> New (nonsensical) story

- dutch/watnu/watnu.md
> Add desire for dropjes besides stroopwafels

- english/sleep/crackers/cracker-soldiers-fight/cracker-soldiers-fight.md
- english/sleep/crackers/cracker-soldiers-fight/get-tiny/get-tiny.md
> Add option to get tiny and shoot through gap in soldier's shield

- english/batman/batman.md
> Add realstic fan reaction to John Cena

- english/vote-the-president/trump/trump.md
> Update trump file

- english/tunnel/continue/continue.md
- english/tunnel/continue/tunnel-end/tunnel-end.md
- english/tunnel/continue/tunnel-end/turn-left/turn-left.md
- english/tunnel/continue/tunnel-end/turn-right/turn-right.md
> Continue the tunnel story.

- english/iot/intro.md
> Add another way of finding devices

- english/android/marshmallow6.0.md
> Add a few line

- english/batman/batman.md
> docs: continute story batman by pham0030

- danish/haervejen/bobbob/bob.md
- danish/haervejen/bobbob/stop/stop_i_vejkanten.md
- danish/haervejen/bobbob/vaekke/vaekke_manden.md
- danish/haervejen/bobbob/videre/koer_og_lad_sove.md
modified:   bob.md
new file:   stop/stop_i_vejkanten.md
new file:   vaekke/vaekke_manden.md
new file:   videre/koer_og_lad_sove.md
> Tilføj tre reactioner til bob.md

- english/batman/batman.md
> docs: continue story line of batman pham0030

- english/famous-tv-series/Game-of-thrones/Game-of-thrones.md
- english/famous-tv-series/Game-of-thrones/characters/cersei-lannister/cersei-lannister.md
- english/famous-tv-series/Game-of-thrones/characters/characters.md
- english/famous-tv-series/Game-of-thrones/characters/daenerys-targaryen/daenerys-targaryen.md
- english/famous-tv-series/Game-of-thrones/characters/jon-snow/jon-snow.md
- english/famous-tv-series/Game-of-thrones/characters/tyrion-lannister/tyrion-lannister.md
- english/famous-tv-series/Game-of-thrones/imdb/imdb.md
- english/famous-tv-series/Game-of-thrones/wikipedia/wikipedia.md
- english/famous-tv-series/Sherlock-Holmes/Sherlock-Holmes.md
- english/famous-tv-series/Sherlock-Holmes/characters/characters.md
- english/famous-tv-series/Sherlock-Holmes/characters/doctor-john-watson/doctor-john-watson.md
- english/famous-tv-series/Sherlock-Holmes/characters/sherlock-holmes/sherlock-holmes.md
- english/famous-tv-series/Sherlock-Holmes/imdb/imdb.md
- english/famous-tv-series/Sherlock-Holmes/wikipedia/wikipedia.md
- english/famous-tv-series/famous-tv-series.md
- english/marshmallow.md
please review this , @casey-collab
> Get information on famous tv-series

- Chinese/theforce/theforce.md
- Chinese/大话西游.md
> Add a stroy to my own adventure.

- english/weed/weed.md
@casey-collab please merge my pull request
> Add or in the Netherlands to the weed story

- german/Wurstwasser/luftanhalten/luftanhalten.md
- german/Wurstwasser/schnaeutzen/schnaeutzen.md
- german/Wurstwasser/wurstwasser.md
> Add two options to german - Wurstwasser former dead end

- english/thunder-carrots/thunder-carrots.md
> Added a contribution to this story

- english/batmetal/batmetal.md
- english/batmetal/stagedive/stagedive.md
please add stagedives, @casey-collab
> add more stagedives

- espanol/canudos.md
- espanol/ejercito-invasor/ejercito-invasor.md
continuing with the illogical and crazy history.
> Add my history ejercito-invasor in spanish version.

- english/forest/fire/woods/follow/shoreline/river/boat/boat.md
- english/forest/fire/woods/follow/shoreline/river/river.md
Added a page to swim to the boat if you went down river after meeting
the shawman in the forest
> Added new page and option on previous page

- english/dog-person/dog.md
- english/golden-lab/golden-lab.md
> Add choice to dog-person page linking to golden-lab option

- hindi/bollywood.md
> Add Babita Phogat link

- german/MacGyver/uboot.md
- german/ruderboot.md
> add MacGyver

- english/coffee/Run/run.md
- english/coffee/listen-to-music/listen-to-music.md
> Add to run choice

- french/dessine/porte.md
- french/dessine/porte/ouvrir-porte.md
- french/dessine/porte/repos/sieste.md
Bonne annee 2017 @casey-collab
> Ajout action porte en miel

- english/lisp/lisp.md
> Add a link from 'lego' story to 'lego' story

- romanian/foc/faci-foc.md
> modificari la capitolul foc

- latvian/grab-lighter/es_aizeju/es_aizeju.md
- latvian/grab-lighter/grab-lighter.md
@casey-collab - please review this!
> add  a walk-out option

- english/tiger-attack/tiger-attack.md
- english/zoo/zoo.md
Changes made to zoo story. @casey-collab
> add tiger attach story to extend zoo story

- english/weed/weed.md
> Add blue pill/red pill choices to weed.md

- english/count-the-marshmellows/eat-all-the-marshmellows/get-breakfast/get-breakfast.md
- english/count-the-marshmellows/eat-all-the-marshmellows/get-breakfast/go-to-malo/go-to-malo.md
> Add go to malo concert option and make a link to directory

- german/Stopfen/stopfen.md
Added a sentence too build up just a little more tension.
> feat: Update stopfen.md

- german/Leichen/Leichen.md
- german/Leichen/Superkraefte/Superkraefte.md
> Mein beitrag

- english/hawkstrider/error/error.md
- english/hawkstrider/rude/rude.md
- english/hawkstrider/start.md
- english/hawkstrider/startr/startr.md
- english/hawkstrider/startu/startu.md
Going to try manually breaking my files to get past the bot.
> Hawkstrider attempt 3

- english/dungeons-and-dragons/dungeons-and-dragons.md
- english/marshmallow.md
> Add initial story options for Dungeons & Dragons

- english/london/london.md
> Added some congratulatory messages to the london.md file

- portugues/revisa/tenta-nao-consegue/amigavel/amigavel.md
- portugues/revisa/tenta-nao-consegue/amigavel/tentativa/tentativa.md
> My part of the adventure pparadella

- english/super-man/save-the-word.md
> Add paragraph and link to Superman story

- hindi/joke/joke.md
> Added hyderabadi style hindi joke

- english/cricket/if-you-love-cricket/ifyoulovecricket.md
- english/marshmallow.md
> Add ifyoulovecricket.md

- english/marshmallow.md
- english/passion/passion.md
> Englishpassion

- english/chocolateOrSleep/chocolateOrSleep.md
Please review this, @casey-collab 
modified:   english/chocolateOrSleep/chocolateOrSleep.md
> "Chat with a spirit" option added in chocolateOrSleep story

- french/feu-de-camp.md
- french/soiree/soiree.md
> Add soiree to the french story

- Philippines/kanta/minsan.md
- Philippines/salamat.md
> Add song minsan by eraserheads

- Italian/canto/canto.md
- Italian/caramelle.md
> add canto option

- french/sortie/chercher-la-sortie.md
How do you think about this @casey-collab ?
> Add new option to sortie in the french story

- english/friendly-person/friendly-person.md
- english/friendly-person/lucky/lucky.md
@casey-collab, please review this and see if it makes sense to you as a good option.
> add feeling lucky option and consequence

- korean/filibuster/filibuster.md
i wanna merge my story into udacity's main branch.
> edited filibuster.md for johnpark82 own story

- german/Dorf/Schmiede/schmiede.md
- german/Dorf/dorf.md
> 	docs: Add Schmiede

- english/dance/dance.md
- english/start-dancing/startDancing.md
> Add partner dance option

- portugues/barata/Pedro/pedro.md
- portugues/barata/baratadavizinha.md
> Pedro story

- espanol/blanco/blanco.md
- espanol/canudos.md
> Modificado

- espanol/canudos.md
- espanol/fin/fin.md
Everything has an end (or many). This is one of them!
> Add 'the end' in Spanish

- english/travel-destinations/travel-destinations.md
> Add Germany to travel destinations.

- english/dream/fly/space/space.md
> added iot story to space

- croatian/sljez.md
> Kisa rastapa sljez, trcis van.

- english/time-machine/time-machine.md
> Y2K time-machine prep

- espanol/escapo/escapo.md
> Detalle de gracia.

- english/chillmusic/chillmusic.md
Added a song called (Human - by Rag'n'Bone Man) a true masterpiece :")
> Add a choice to chillmusic

- english/animal/animal.md
> Add new line to english/animal

- catala/catala.md
- catala/stories/app_camera/app_camera.md
- catala/stories/app_camera/pujar_foto/pujar_foto.md
- catala/stories/menjar_movil/menjar_movil.md
- catala/stories/stories.md
Hope you enjoy this super creative additions, looking forward to more catalan readers have this new options
> Experimental

- portugues/telefonica/ocupado.md
- portugues/telefonica/outra/mesma.md
> Nova opção para "telefonica"

- english/magicaladventure/expelliarmus/expelliarmus.md
> Docs: Add the final touch.

- english/invite-friends/friends.md
- english/invite-friends/sleepover/bake-cookies/bake-cookies.md
- english/invite-friends/sleepover/catch-up/catch-up.md
- english/invite-friends/sleepover/dance-party/dance-party.md
- english/invite-friends/sleepover/play-game/play-game.md
- english/invite-friends/sleepover/sleepover.md
- english/invite-friends/sleepover/watch-movie/watch-movie.md
> Add sleepover option to invite friends, along with some options for sleepover activities

- english/marshmallow.md
Please take a look! fixed the formatting of some markdown links in marshmallow.md
> fix: format of markdown link 

- dutch/bos/verlaten-weg/noorden/noorden.md
- dutch/bos/verlaten-weg/verlaten-weg.md
Added option "noorden" in the dutch part of the story.
> Optie noorden toegevoegd

- english/bamboo/bamboo-shoots.md
> defense yourself

- english/dimensions/dimension.md
> Added my own dimension

- german/Stopfen/ueberlegen/ueberlegen.md
Adding to a german page with a great white shark.
@casey-collab
> Feat: Add new lines on this page

- dothraki/dosh-khaleen/dosh-khaleen.md
- dothraki/dothraki_evoli.md
- dothraki/sir-jorah/sir-jorah.md
> Add storylines to dothraki

- portugues/futebol/futebol.md
> Add my change

- Philippines/mulat/mulat.md
- Philippines/salamat.md
> Add message to my fellowmen

- swedish/titta-ut/titta-ut.md
> feat: Add paragraph about hunger.

- english/lazy/lazy.md
> Add company to misery

- english/universe-test/blaze_verse.md
> Add new lines to the story in english/universe-test/blaze_verse.md file

- Polish/ptasieMleczko.md
"/Polish/ptasieMleczko.md"
(they were unreadable)
> Fix the polish characters in file

- english/forest/drag/skull/skull.md
> Added path colours

- hindi/joke/joke.md
> char log kaha hai

- english/bored/bored.md
> Add a line to bored.md

- english/dream/swim/Snake/Hand/hand.md
- english/dream/swim/Snake/snake.md
> Add Hand to deadend Snake directory

- espanol/angeles/angeles.md
Please check this @casey-collab
> Angels are messengers

- bangla/bangla-portals.md
> New portal added.

- english/iot/scan-network/scan-network.md
> I had to do this for a class

- german/ruderboot.md
@Udacity: Please review this story.
> Fix MacGyver link in ruderboot.md

- portugues/titanic/arrumar/imitar/falha.md
> muda falha.md

- english/bamboo/bamboo-shoots.md
Please review this story @casey-collab
> I added the state of Panda running towards me

- french/manger/trou/reveille/voix-humaines/mystere.md
- french/manger/trou/reveille/voix-humaines/traduire/traduire.md
Please review this, @casey-collab. Thank you!
> Add option 'traduire' to ecouter.md

- portugues/colabora/fork/comdiferencas/diff/pull/pull.md
> Add my workflow, @casey-collab

- english/knit/knit.md
> Added a quit option to knit strand

- english/bear/bear.md
Cool! Please review this, @casey-collab
> Add to bear.md

- english/forest/eat/eat.md
> squirrel chatter

- english/talk_to_neighbour/man/mulder.md
Please check this out, @casey-collab
> Make yourself trip when running towards Scully

- portugues/cogumelos/cogumelos.md
> Gnomos a vista

- english/00_8_Agent/The_name_is_Bond_Milton_Bond.md
> Covert operation with Milton.

- english/after-death/after-death.md
- english/marshmallow.md
> add after-death story

- hindi/Mahabharat/mahabharat.md
- hindi/swami-vivekananda/swami-vivekananda.md
> Mahabharat file added under Hindi sub-directory.

- german/ruderboot.md
> Add sentence to ruderboot.md

- english/lazy/lazy.md
> Proof that I'm lazy

- english/earlyBird/content.md
- english/marshmallow.md
- english/nightOwl/content.md
A new version to the existing collection@casey-collab
> My version

- english/2spooky/2spooky.md
> Add "not so nice"

- french/bucheron/apprend-bucheron.md
- french/feu-de-camp.md
My part of the story is under the french files. Please review this @casey-collab
> Add french story part about Lumberjacks

- Polish/przygoda/jedzenie/korwin/prezent/pistolet/pistolet.md
- Polish/przygoda/jedzenie/korwin/prezent/plakat/plakat.md
- Polish/przygoda/jedzenie/korwin/prezent/rewolwer.md
- Polish/przygoda/jedzenie/korwin/prezent/wladza/wladza.md
> Add the continue of the story

- english/marshmallow.md
- english/travel/destinations.md
> adds travel destination feature

- english/showerthoughts/showerthoughts.md
> Adding more reddit

- english/love-udacity/love-udacity.md
Noddy line added for course purposes
> one liner added by PR

- english/marshmallow.md
> added one line to story

- english/Ed-Sheeran-music/Happier/happier-lyric.md
- english/Ed-Sheeran-music/Perfect/perfect-lyric.md
- english/Ed-Sheeran-music/list-song.md
- language.md
Please review me ,@casey-collab
> Ed sheeran music

- english/android-dev/dev.md
- language.md
> Adding Developer link
