udacity/create-your-own-adventure

english/marshmallow.md
english/ponder/ponder-about-life.md

Add ponder choice

---

espanol/muralla/abrir/abrir.md

nueva linea muralla

---

Philippines/salamat.md
language.md

Hi! Here's my adventure (more of a message). 
Thanks!

Philippines

---

english/light-fire/xyzzy/stand-petrified/meet-wizard.md
english/light-fire/xyzzy/xyzzy.md

Extension to light fire, say xyzzy options.

Add wizard & jump to flaming tower

---

english/marshmallow.md
english/you-are-in-minecraft/minecraft.md

Add you-are-in-minecraft directory + minecraft.md file

---

portugues/revisa/tenta-nao-consegue/eh-perseguido/salve-se-quem-puder.md
portugues/revisa/tenta-nao-consegue/tenta-falha.md

Add new story

---

english/mushroom/eat/eat_mushroom.md
english/super-man/save-the-word.md

Are you ready to save the world?

Eat the mushroom, become a superman

---

czech/kapsy/prohledat.md
czech/marsmelouny.md

Add new option for marshmelouny.md and created folder and prohledat.md

---

english/find-exit/leave.md

Added link from go outside to explore outside

---

english/light-fire/sprinkler/basement-swim/basement-swim.md
english/light-fire/sprinkler/basement-swim/lick-chocolate/lick-chocolate.md

Lick chocolate

---

english/meditate/meditate.md
english/run/run.md

Hm changes2

---

english/coffee/another-coffee/another-coffee.md
english/coffee/coffee.md

Added another coffee option to english/coffee/

---

english/jacket/marshmallow-jacket.md
english/marshmallow.md

Marshmallowjacket

---

english/macgyver/cliff/cliffjump.md

Update cliffjump story

---

english/light-fire/eating/stream/go-fish/fish.md
english/light-fire/eating/stream/go-fish/talk-fish/talk.md

Add 'talking to fish' option

---

english/find-exit/into-mountains/upwards/further-upwards/towards-saddle/rush/inspect/burn_aspect/burn_aspect.md
english/find-exit/into-mountains/upwards/further-upwards/towards-saddle/rush/inspect/burn_aspect/continue/continue.md
english/find-exit/into-mountains/upwards/further-upwards/towards-saddle/rush/inspect/inspect.md
english/find-exit/into-mountains/upwards/further-upwards/towards-saddle/rush/inspect/pawn_aspect/pawn_aspect.md
english/find-exit/into-mountains/upwards/further-upwards/towards-saddle/rush/rush.md

Please merge my storyline, @casey-collab !

Bear storyline

---

german/Hilfeschrei/Hilfeschrei.md
german/ruderboot.md

German option1

---

english/invite-friends/friends.md
english/invite-friends/smores/with_friends.md

Another story line in English

---

english/invite-friends/friends.md
english/invite-friends/smores/with_friends.md

Added another branch to the story in English.

---

english/coffee/coffee.md
english/coffee/novel/full-length-novel.md

Add 'novel/full-length-novel' to the /coffee directory

---

english/light-fire/eating/stream/go-fish/fish.md
english/light-fire/eating/stream/go-fish/talk-fish/talk.md

I fixed some typos to my previous automatic pull request. I am not a paying user, so feel free to only update this if you have time and are not busy. I wish I could say I intended for those typos to be there so I could get some practice, but that was not the case :)

Alt boyergv

---

greek/marshmallow.md
language.md

Greek story

---

english/mushroom/call_alan/transported.md
english/mushroom/collect_mushroom.md

Jeff branch

---

english/dance/dance.md

Don't waste those marshmallows!

Add the magic, marshmallow kitchen

---

english/light-fire/run-away/shout/child-wave.md
english/light-fire/run-away/shout/more-info/explain-escape/explain-escape.md
english/light-fire/run-away/shout/more-info/find-dog/find-dog.md
english/light-fire/run-away/shout/more-info/goto-town/goto-town.md
english/light-fire/run-away/shout/more-info/more-info.md

The previous pull request got cluttered with 1000 commits because I had to rebase the branch to correct my email address. Obviously, that did not work out so well as it wanted to submit 1000+ commits. I probably did something wrong. This should be a lot cleaner as there are only 4 commits to be committed. 1 commit for each file (separate story) being added.

More-Info Story Branch

---

english/super-man/practice-flying.md
english/super-man/save-the-word.md
english/super-powers/practice-flying.md

Added option to superman storyline

---

espanol/canudos.md
espanol/rebelion/inicio-rebelion.md

Please merge this, @casey-collab

Add rebelion story into espanol

---

english/count-the-marshmellows/count-again/count-again.md
english/count-the-marshmellows/count-the-marshmellows.md

Add count again option in count the marshmellows

---

english/light-fire/stop-drop-roll/stop-drop-roll.md

Scream if you see fire!

---

english/explore-outside/journey-to-flaming-tower/exit/exit.md
english/explore-outside/journey-to-flaming-tower/journey-to-flaming-tower.md

Added exit story for journey-to-flaming-tower

Add exit out of the Matrix

---

english/lighter/grab-lighter.md

Please enter the commit message for your changes. Lines starting

Tell more about the lighter and pocket

---

Chinese/ZZB/zzb.md
Chinese/大话西游.md

Add new story ZZB under Chinese folder

Add new story ZZB under Chinese folder

---

language.md
latvian/grab-lighter/grab-lighter.md
latvian/zefirs.md

Please review this @casey-collab.

Richard modifications

---

english/sleep/more-sleep/smore-eating/delicious.md

Please review this,@casey-collab

Added Two questions to the story on line 11

---

english/sing/out-of-tune/out-of-tune.md
english/sing/sing.md

Add new lines and options to the story

---

english/coffee/coffee.md

Add coffee description

---

hungarian/malyvacukor.md
hungarian/zokni/zokni.md

Added an option to the Hungarian file.
Please check it out @casey-collab

Zokni option added

---

english/sleep/more-sleep/expired-milk/expired-milk.md
english/sleep/more-sleep/expired-milk/tell-mom/tell-mom.md

Added an option in expired-milk.md to link to tell-mom.md

---

romanian/nalba.md
romanian/padurea_violet/padurea_violet.md

add "padurea violet" story

---

english/light-hand/light-hand.md
english/lighter/grab-lighter.md

Add light hand on fire path to story

---

english/dig/bird/bird.md
english/dig/dig.md

Add scare bird part of the story.

---

english/light-fire/stop-drop-roll/stop-drop-roll.md

Added some more text to better describe getting covered in marshmellowy goo

added more descriptive text.

---

english/dance/dance.md

Add plot twist

---

Italian/caramelle.md
Italian/finestra/apri.md

italian story mod

---

english/sing/lightup/accept/accept.md
english/sing/lightup/lightup-marshmallow.md
english/sing/lightup/reject/reject.md

Add new part of the story after lighting up the monster's face!

---

english/staypuft/ghostbusters/protons/nothing-at-first/dejavu.md
english/staypuft/ghostbusters/protons/reach.md

Travel travel to a familiar place

---

english/explore-outside/call-scotty/call-scotty.md
english/explore-outside/explore-outside.md

Add Beam me up Scotty option

---

english/find-exit/into-forest/all-is-lost/all-is-lost.md
english/find-exit/into-forest/forest.md

All is lost or is it

---

english/find-exit/into-forest/talk-to-cougar/talk-to-cougar.md

Add option to return to forest

---

english/marshmallow.md

Add a couple of lines to marshmallow.md

---

english/marshmallow.md

@casey-collab please merge my changes

Add link for properly cooking marshmallows and eating them

---

dutch/bos/donker-bos.md
dutch/welkom.md
language.md

Adding dutch language option.

---

english/macgyver/ceiling_hole/ceiling_hole_burn.md
english/macgyver/macgyver.md

Macgyver add

---

english/scream/mom/eatwithmom.md

@casey-collab hope this works.

Add that mom doesn't like marshmallows

---

english/dance/dance.md

I added a sentence questioning the protagonist's reality of whether or not there were too many cooks in the kitchen.

Too many cooks in the kitchen or do you have double vision? You have been listening to Foreigner.

---

english/light-hand/light-hand.md
english/light-hand/light-walls/light-walls.md
english/light-hand/reach-arm-in-wall/reach-arm-in-wall.md

Dawgavins story change

---

english/super-man/lex-luther/find-lex-luther.md
english/super-man/save-the-word.md

Lex Luther

---

english/yoga/lifestyle/yoga_lifestyle.md
english/yoga/yoga.md

Changes to yoga 

---

portugues/colabora/comdiferencas/comdiferencas.md
portugues/colabora/comdiferencas/diff/diff.md

Mybranch add comdiferencas.md options and diff.md file

---

english/eating-walls/eating-marshmallows.md

Add 2 sentences to marshmallow story to make it more interesting

---

english/amnesia/amnesia.md

Add what to do when you dont get sleep

---

english/sleep/more-sleep/more-sleep.md

@casey-collab, please merge this.

Add option to do yoga

---

english/invite-friends/camp_fire/abduction/abduction.md
english/invite-friends/camp_fire/eat_marshmallow.md

Add trying to find out how you got there

---

english/marshmallow.md

Trix are for kids - Please review this, @casey-collab

---

english/dance/bake-a-cake/bake-a-cake.md

Ahhhhmeds change

---

english/macgyver/jump-rope/jump-a-rope.md
english/macgyver/macgyver.md

Added option in file macgyver.md to jump a rope, along with a jump-rope directory and jump-a-rope.md

Add jump a rope option to macgyver.md

---

english/pinch/jacket/magicianskills/magicianskills.md

Add lines to magicianskills.md

---

english/find-exit/chococopter/chococopter.md

add escape by Chococopter to submarine

---

english/sleep/make-another-wish/wish.md
english/sleep/marshmallow.md

added a new option in marshmallow: make another wish

---

espanol/canudos.md
espanol/dragon/dragon.md

Added new part to the "espanol" story (the dragon part)

---

portugues/git/oque.md

Add a new link of training for GitHub

---

english/explore-outside/explore-outside.md

Linking coffee option to the existing explore outside option.

---

english/scream/mom/eatwithmom.md

You don't trust mom.

---

french/manger/faim.md
french/manger/trou/trou.md

Ajout possibilité de sortir par le trou
Ça fait du bien de pouvoir respirer le grand air!!!

Ajout possibilité de sortir par le trou

---

english/run/run.md

I am not female or particularly concerned about this issue, just saw an opportunity to be a little more inclusive. Please review this, @casey-collab

Make run.md gender neutral

---

english/ponder/ponder-about-life.md
english/ponder/ponder-some-more/ponder-some-more.md

This adds the "Ponder Some More" story line to the Create Your Own Adventure project. Please review @casey-collab .

Add Ponder Some More

---

english/run/run.md

Added some sentences to the running ending of the story. Hopefully this will allow the next contributor to create some options for this path.
Also, I noticed that @anerlich made some changes that have not yet been approved.

Added some sentences to the run story end.

---

english/coffee/coffee.md

add new option after drinking a coffee

---

english/staypuft/ghostbusters/protons/nothing-at-first/dejavu.md
english/staypuft/ghostbusters/where-is-my-proton-pack.md

I circled the Ghostbusters thread back to the original, adds a Groundhog Day-esque theme to a thread featuring Bill Murray.

Ghostbusters

---

espanol/canudos.md
espanol/hijo/hijo.md

New alternative into the Spanish story about the "Hijo del Consejero".

---

english/pinch/magic/harry-potter.md
english/pinch/pinch.md

Add magical world of harry-potter

---

english/explore-outside/talk-child/talk-child.md

Project Evaluator,
Please review the pull request and merge with main fork master. Let me know if there is any feedback. Thank you,
Meg Storm
meg@sageminds.com
610-984-2439

Add MacGuyver option when talking to child, reword line 2 and fix typo.

---

english/explore-outside/journey-to-flaming-tower/home/home.md

added several new lines to this file about strawberries and G.I. Joe

---

german/Hilfeschrei/Hilfeschrei.md

Hi, consider this @casey-collab

German: Zurück-Option hinzugefügt

---

english/sing-song/edm/edm.md

Here's a comment for @casey-collab

Add drugs to edm.md

---

english/explore-outside/journey-to-flaming-tower/home/home.md

add a line about your happy feelings

---

english/adipose/adipose.md
english/marshmallow.md

Added adipose route

---

english/hide/hide-chk.md
english/marshmallow.md

Added a new option to the beginning of the story and linked it to a file.

Chk branch

---

german/gefasst-bleiben/gefasst-bleiben.md

finger-ins-loch zu gefasst bleiben hinzugefuegt

---

english/eating-walls/eating-marshmallows.md
english/eating-walls/find-a-toilet/find-a-toilet.md

Eating walls, new option when you have to go.

---

english/coffee/another-coffee/another-coffee.md
english/coffee/bagel/eat-a-bagel.md

Introducing a bagel option

---

english/marshmallow.md
english/necklace/necklace.md

Add new necklace story to english/marshmallow

---

english/dig/dig.md
english/dig/sing-greet/sing-greet.md

Please review the sing-greet revision, @casey-collab

Greet version

---

english/experience/blue-tunnel/blue-tunnel.md
english/experience/experience.md
english/experience/golden-halo/golden-halo.md
english/experience/white-star/white-star.md
english/marshmallow.md

Experience the marshmallow

---

english/staypuft/carrot-nose/find-carrot-nose.md
english/staypuft/marshmallowman.md

@casey-collab, please review added option for carrot nose.

Add option for finding carrot nose for snowman.

---

english/light-fire/sprinkler/eating-chocolate.md
english/light-fire/sprinkler/graham-cracker/graham-cracker.md

Story by sia

---

latvian/sniegt_roku/sniegt_roku.md
latvian/zefirs.md

Add a new option ("Sniedz roku Zefīru kungam?") to the existing list of choice points, create a new "page" (./sniegt_roku/sniegt_roku.md) for that option, and add a sentence or two to the new "page" (see new text)

Add a new option ("Sniedz roku Zefīru kungam?") to the existing list and create new page of content

---

english/lighter/roastmaster/comedy-central/comedy-central.md
english/lighter/roastmaster/invoke-roastmaster.md

Add a new option to an existing choice point, create a new "page" for that option, and add a sentence or two to the new "page".

Add change to the story

---

korean/marshmallow.md
korean/sing-a-song/song.md

add a sing-a-song to the korean version

---

english/eating-walls/eating-marshmallows.md

Added a singing clearly option

---

english/coffee/coffee.md

Please check the new merging request regarding some new thoughts about the roasted coffee, @casey-collab

Add thoughts regarding the sharp taste of the roasted coffee

---

english/you-are-in-minecraft/minecraft.md

Add another line of text before the options

---

english/explore-outside/journey-to-flaming-tower/jellybus/ask-person-about-destination/ask-person-about-mission/ask-person-about-mission.md
english/explore-outside/journey-to-flaming-tower/jellybus/ask-person-about-destination/ask-person-about-mission/duel/duel.md

Add duel option

---

english/magic/magic.md
english/marshmallow.md

Kerry's Adventure

---

english/invite-friends/friends.md
english/invite-friends/mosh_pit/mosh_pit.md

Own adventure

---

english/hide/hide-chk.md

"Hello @casey-collab, I added a new line into the hide-chk.md file."

Added a new line to hide-chk.md file

---

Chinese/congrats/congrats.md
Chinese/大话西游.md

modified congrats.md

---

english/explore-outside/call-scotty/call-scotty.md

@casey-collab updating the call scotty story line, but only have the 1 file changed now (not multiple ones like previously).

Changed ending on call-scotty.md for 2nd time.

---

english/experience/blue-tunnel/blue-tunnel.md
english/experience/blue-tunnel/gnome/gnome.md

See a gnome

---

english/explore-outside/talk-child/talk-child.md
english/explore-outside/talk-child/talk-more/indignant-talk/indignant-talk.md
english/explore-outside/talk-child/talk-more/nice-talk/nice-talk.md
english/explore-outside/talk-child/talk-more/nice_talk/nice-talk.md
english/explore-outside/talk-child/talk-more/talk-more.md
english/explore-outside/talk-child/talk-more/threaten-talk/threaten-talk.md

Making a pull request for my changes to talk more with the child

---

english/count-the-marshmellows/eat-all-the-marshmellows/eat-all-the-marshmellows.md
english/watch-alien/watch-alien.md

you watch alien movie after eating all marshmallows and exploding
(feeling like the chestbuster scene in the movie makes you want
to watch that movie)

add watch-alien page

---

french/dormir/reve-etrange.md
french/feu-de-camp.md

Updated french version to prevent sleepy adventurers from getting bored.

loopback tobeginning after waking up (for frenchversion only)

---

turkce/hatmisekeri.md

updated hatmisekeri.md

---

english/dig/bird/bird.md

Post blackbird options

---

english/eating-walls/find-a-toilet/door/bear/stand-still.md
english/eating-walls/find-a-toilet/door/open-door.md

edit open door and next action for and encounter with a bear

---

english/netflix/netflix.md

please review this @casey-collab

Dustin: added story to netflix horror

---

english/lighter/grab-lighter.md

Add an option 'Close eyes?'

---

german/schwimmen/schwimmen.md

Spelling corrections on schwimmen.

---

english/backinstraitjacket/backinstraitjacket.md
english/marshmallow.md

Add 'back in straitjacket' option to marshmallow.md

---

english/wikipedia/wiki.md

Wikipedia update

---

english/adipose/adipose.md

Added sentence to adipose or 'remember that pill you took' story line

---

english/explore-outside/call-scotty/call-scotty.md

call-scotty was a dead end. This will keep the story going. Please review this, @casey-collab

Add link out of call-scotty to experience

---

english/coffee/bagel/eat-a-bagel.md

Add question 'Was it good?'

---

english/explore-outside/journey-to-flaming-tower/towel/towel.md

...You are on your way to the flaming tower but have no towels... You suddenly have a genius idea.

Add line - you suddenly have a genius idea.

---

Polish/ptasieMleczko.md
Polish/ubranie/ubranie.md

Przygoda od mebio

---

english/sleep/make-another-wish/wish.md

add macbook pro

---

english/lego/lego.md

Adds word of caution and option to lego page

---

english/call-a-doctor/doctor.md
english/call-a-doctor/jarjar/jarjar.md

Hiya @casey-collab, could you please review my changes?

Add Jar Jar Binks option to call-a-doctor

---

english/count-the-marshmellows/count-again/count-again.md

Add line. Enter marshmallow tunnel.

---

english/make-friends/make-friends.md
english/marshmallow.md

Make friends

---

english/experience/blue-tunnel/gnome/gnome.md

Gnome is now eerily pointing to his garden.

Add gnome pointing

---

english/amnesia/amnesia.md

Can't sleep. Wishing those marshmallows were vegan...

add vegan line to amnesia

---

german/Einladen/einladen.md
german/Fragen/fragen.md
german/Oktoberfest/oktoberfest.md
german/oktoberfest.md
german/ruderboot.md

Please review this, @casey-collab...:)

Meiner bericht

---

english/light-fire/stop-drop-roll/start-licking-yourself/start-licking-yourself.md
english/light-fire/stop-drop-roll/stop-drop-roll.md

Add option start-licking-yourself (to get rid of marshmallow)

---

english/marshmallow.md
english/pokemon/pikachu_wins.md

Add pokemon option to story

---

english/experience/blue-tunnel/gnome/gnome.md

Add line. You see a mushroom house with chocolate jacuzzi.

---

english/pinch/help/princess/antidote/new-antidote/open.md

Add lines - remembered lighter

---

english/marshmallow.md

Add initial reaction to discovering the lighter, fork and rope

---

english/yoga/stretch/stretch.md

Add lines after yoga pulling muscle. You wake up on a mountain. Panic.

---

espanol/huida/pagar/pagar.md
espanol/huida/puerta.md
espanol/huida/rechazar/rechazar.md

Add new options to 'huida'

---

english/lighter/grab-lighter.md
english/lighter/toke/toke.md

pull toke story line

---

english/staypuft/animate-me/animate-me.md
english/staypuft/marshmallowman.md

Add leather jacket story

---

french/panique/frapper-le-mur.md
french/panique/sentir/fleurs.md

Add flowers

---

english/netflix/netflix.md

Add Netflix movie about Jesus Christ

---

dutch/bos/ontvoering/ontvoering.md

I have added some sentences to the point where the reader of the Dutch storyline is reading about a kidnapping.
Please review/auto-merge this, @casey-collab

Add some sentences to the dutch story

---

espanol/canudos.md
espanol/montanas/montanas.md

Added to the spanish story. It's not much, but it helps. :)

added my part of the story, 'montanas'

---

english/explore-outside/explore-outside.md

Add line describing tower

---

english/marshmallow.md

added a line to marshmallow.md

---

english/find-exit/leave.md

ice-cold water

---

portugues/revisa/tenta-consegue/reproduz.md
portugues/revisa/tenta-consegue/sem-resposta/contato-desenvolvedor.md

Continuação história 'sem-resposta'

---

german/finger-ins-loch/finger-ins-loch.md

@casey-collab, inserted line breaks

add content to dead-end

---

english/coffee/drink-tea/drink-hot-tea.md

Add a piece of chocolate to story.

---

english/marshmallow.md
english/moving/moving.md

Own branch

---

english/interact/bend/bend.md
english/interact/interact.md
english/interact/lighter/lighter.md
english/marshmallow.md

Added an interact option in marshmallow.md

New changes

---

portugues/colabora/semdiferencas/pentefino/pentefino.md
portugues/colabora/semdiferencas/semdiferencas.md

Nopain nogain

---

espanol/canudos.md
espanol/heroe/dragon_aliado/dragon_aliado.md
espanol/heroe/dragon_malvado/dragon_malvado.md
espanol/heroe/heroe.md

My contribution to the story 

---

german/Alkohol/alkohol.md
german/ruderboot.md

Add alcohol story to German

---

english/interact/fork/fork.md
english/interact/interact.md

Add option "Take your fork out" and continue english/interact/fork

---

english/light-hand/reach-arm-in-wall/reach-arm-in-wall.md

Please review this change, @casey-collab.

Add option to dig with fork.

---

english/macgyver/macgyver.md

add a line about macgyver's mullet to the story

macgyver had a sweet mullet

---

english/dream/dream.md

Add a sentence to the dream file

---

language.md
slovak/marshmallow.md
slovak/marsmelaci.md

Slovak story

---

english/coffee/coffee.md

Twist to the basis and reason for yawning.  Gives more validity and poignancy for the following comments.

Yawn is a scream for coffee

---

english/marshmallow.md
english/timeTunnel/timeTunnel.md

added a time tunnel branch to the story

add time tunnel branch to story

---

portugues/revisa/tenta-consegue/reproduz.md
portugues/revisa/tenta-consegue/ti-cruel/coco-na-praia.md

Please @casey-collab try to merge my files. Tks.

Adding the possibility of coconut selling in Portugues section

---

korean/explore-outside/investigate-marshmallow-structure/investigate-marshmallow-structure.md

Modified investigate-marshmallow-structure to include choices

---

english/wikipedia/wiki.md

add link to minecraft from wikipedia

---

english/interact/fork/fork.md

Update fork.md with sleep choice and link

---

english/marshmallow.md
english/use-the-fork-luke/use-the-fork.md

My contribution to the living story.

Use the fork luke

---

english/macgyver/macgyver.md

I modified the text on the MacGyver page for the english version, and fixed some typos along the way.

Expand text on MacGyver page

---

espanol/bruja/bruja.md
espanol/canudos.md

He añadido una bruja a la historia en español
Added a witch to the spanish version of the story

Añadida la bruja

---

english/birdistheword/birdistheword.md
english/marshmallow.md

add bird is the word

---

english/fork-knots/melt-with-fork.md

add two lines and four links to melt-with-fork

---

german/Kopfsprung/Kopfsprung.md
german/Korallen/Korallen.md

Add corals to german story

---

english/dig/uva/uva.md

Please do this, if you can @casey-collab.

Fix first link in uva.md not working because GitHub doesn't understand relative reference-style links.

---

french/manger/trou/trou.md

Add new development when exiting through the hole.

Add a few lines to the French trou adventure

---

english/find-exit/into-forest/forest.md

Point find-exit/into-forest/forest.md to fork-knots/melt-with-fork.md

---

english/watch-alien/watch-alien.md

Add more story lines

---

english/call-these-guys/calltheseguys.md
english/marshmallow.md

Please review this, @casey-collab".

My own adventure

---

english/marshmallow.md
english/play-some-cricket/playsomecricket.md

Please review and merge my changes into master

Add a new file "Play Some Cricket"

---

english/you-are-in-minecraft/dig_down/dig_down.md

@casey-collab please add my lighter flavor text

Lighter flavor text in dig_down.md

---

espanol/rezando/paquete/caballero/caballero.md
espanol/rezando/paquete/caballero/malvado/malvado.md

Black knight evil

---

english/coffee/another-coffee/another-coffee.md

Add option for writing novel after coffee

---

german/schwimmen/gefahr/gefahr.md
german/schwimmen/hunger/hunger.md
german/schwimmen/schwimmen.md

german: continue 'schwimmen'

---

english/indigestion/indigestion.md
english/marshmallow.md

Indigestion

---

english/challenge-marshmellow-to-rock-off/castle-route/narnia.md

Please add these changes to story

Added to story; Stairmaster bronze medallist

---

english/fus-roh-dah/fus-roh-dah.md
english/marshmallow.md

add fus-roh-dah option

---

english/check-your-phone/check-your-phone.md
english/marshmallow.md

Check your phone

---

turkce/duvarlari-ye/duvarlari-ye.md
turkce/duvarlari-ye/yemeye-devam-et/yemeye-devam.md

yeni seçenek ekle: yemeye devam.

---

english/fus-roh-dah/fus-roh-dah.md

Please review this, @casey-collab 
Thanks!

Add story and option to fus-roh-dah

---

english/eating-walls/eating-marshmallows.md

@casey-collab 
Thanks, helpful bot!

Add in some vivid imagery about eating marshmallow walls.

---

english/coffee/another-coffee/another-coffee.md
english/coffee/hollywood/hollywood.md
english/coffee/novel/full-length-novel.md

Added option to sell the book rights.

---

english/lunge-for-the-lighter/lunge-for-the-lighter.md
english/marshmallow.md

Add an option for the reader to lunge for the lighter.

Please review this, @casey-collab

---

english/marshmallow.md
english/nepal/nepal.md

Add Nepal branch

---

dutch/bos/ontvoering/meehelpen/meehelpen.md
dutch/bos/ontvoering/ontvoering.md

Add new change in the story 'meehelpen'.

---

english/experience/black-point/black-point.md
english/experience/experience.md

Add a branch in close eyes

---

english/sleep/more-sleep/more-sleep.md

Add Wikipedia

---

english/use-the-fork-luke/use-the-fork.md

Please review this, @casey-collab .

Add Help Me Obi Won Kenobi Message

---

Chinese/Casey/Casey.md

add something to caesy

---

english/hit-song/hit-song.md
english/pokemon/pikachu_wins.md

My changes

---

english/staypuft/animate-me/animate-me.md

changeing the animate me  for the marshmellow man, review @casey-collab

---

english/invite-friends/camp_fire/abduction/abduction.md
english/invite-friends/camp_fire/abduction/bad_cop/badCop.md
english/invite-friends/camp_fire/abduction/good_cop/goodCop.md

added options for good and bad cops and respective directories

---

english/find-exit/call-work/call-work.md

Add option to shoot flare after calling in to work

---

dutch/over-het-hek/hek.md
dutch/welkom.md

Please add this, @casey-collab

Add extra option to dutch part 'hei'

---

english/staypuft/ghostbusters/billMurrayMovies/billMurrayMovies.md
english/staypuft/ghostbusters/billMurrayMovies/groundhog-day/ned-ryerson.md

Groundhog day

---

english/turing-test/turing-test.md

Add link to Stay Puft from the Turing Test

---

english/sing/continue/continue-to-sing.md

Some amusing banter for committed singers

Add colour to sing/continue

---

english/ask-to-alice/ask-to-alice.md

Add three optional paths, with subtle Jefferson Airplane reference

Open up dead end Ask-to Alice link

---

english/coffee/nude-run/badger/badger.md
english/coffee/nude-run/cold-water/cold-water.md
english/coffee/nude-run/nude-run.md
english/coffee/nude-run/warm-water/warm-water.md

Story changes

---

language.md
portugues_pt/caridade/caridade.md
portugues_pt/colaborar.md
portugues_pt/mundo/voltaaomundo.md
portugues_pt/praias/solemar.md

Portugues pt

---

english/interact/interact.md
english/interact/run-into-wall/run-into-wall.md

Added my part of the story to interact/run-into-wall
Fun project!

add interact/run-into-all

---

check-your-phone.md
english/check-your-phone/check-your-phone.md

You are in Paris

---

english/turing-test/prank/prank.md
english/turing-test/turing-test.md

I added a new option to the turing-test page and wrote a small story for when the option is selected. @casey-collab

add prank option to turing-test

---

english/check-your-phone/check-your-phone.md

Add line about mystery woman to phone check scene

---

espanol/torre/espera/abrir/abrir.md
espanol/torre/espera/cerrada/cerrada.md
espanol/torre/espera/espera.md

Carlos pull

---

english/macgyver/jump-rope/jump-a-rope.md

Add more to leg day option

---

english/dream/dream.md
english/dream/fly/fly.md

Can we add the option to try and fly in the dream?

Try flying to see if it is a dream. Option added to dream.

---

french/manger/continue/continue.md
french/manger/faim.md

Thanks for merging @casey-collab

Add continue option in faim.md file & Add continue.md file

---

english/soar/fly-to-london/fly-to-london.md
english/soar/fly-to-paris/fly-to-paris.md
english/soar/soar.md

Add soaring options

---

english/turing-test/dragonball/dragonball.md
english/turing-test/turing-test.md

Story change

---

english/hulk/smash.md
english/marshmallow.md

Please accept my pull request

---

english/lighter/roastmaster/comedy-central/comedy-central.md

Add turtles to the story.

---

english/dig/dig.md
english/dig/worship/worship.md

added story

---

english/macgyver/light-rope-on-fire/extinguish/extinguish.md
english/macgyver/light-rope-on-fire/light-rope-on-fire.md
english/macgyver/light-rope-on-fire/wait/wait.md

Add options to the light-rope-on-fire storyline

---

english/fus-roh-dah/fus-roh-dah.md

add line for deadra lord

---

english/dance/dance.md

Add a dance practice

---

french/feu-de-camp.md
french/telephone/prof_musique.md

Add french - telephone story

---

english/lego/lego.md

@casey-collab please commit this

adds to lego story

---

english/lego/lego.md

Add a line to the lego-story

---

english/getsLost/getsLost.md

Small change

---

english/macgyver/macgyver.md

Add flamethrower build line

---

english/humbleservant/humbleservant.md
english/marshmallow.md

Add humble servant option

---

english/explore-outside/journey-to-flaming-tower/towel/towel.md

Add the following: 
Maybe you should just go home, take your magic towel out of the laundry, and fly to the tower.
If all goes well, you should be at the tower within five minutes.
There's just one thing wrong with this new idea...

Add lines about going home to retrieve towel

---

english/marshmallow.md
english/snuffbox/snuffbox.md

Add snuffbox

---

espanol/noticias/pregunta-periodista/curar-heridos/curar-heridos.md
espanol/noticias/pregunta-periodista/pregunta-periodista.md

My adventure

---

english/turing-test/eliza/ask_eliza.md
english/turing-test/turing-test.md

added Ask ELIZA option to turing-test, including new folder and initial markdown file.

New option in turing-test: Ask ELIZA.

---

english/quote-of-the-day/inspiration/inspiration.md
english/quote-of-the-day/quote.md

Add new adventure to quote of the day folder

---

english/yoga/benefits/yoga_benefits.md

I added a new benefit to the benefits file in the yoga folder.
Please review!

Add benefit for practicing yoga

---

english/staypuft/carrot-nose/find-carrot-nose.md
english/staypuft/carrot-nose/give-up/give-up.md
english/staypuft/carrot-nose/pointy-rock/pointy-rock.md

Jessica story

---

english/bake-cookies/cookies.md

Added coffee option in cookies file

---

english/yoga/breathe/breathe.md
english/yoga/yoga.md

Add breathing option to yoga story

---

espanol/torre/exploradores/exploradores.md
espanol/torre/torre.md

agrega historia a espanol/torres/exploradores

---

english/marshmallow.md
english/yuha/yuha.md

Add Yuha folder and link to it in marshmallow

---

english/marshmallow.md

Made changes to the main story

---

english/count-the-marshmellows/eat-all-the-marshmellows/get-breakfast/get-breakfast.md
english/count-the-marshmellows/eat-all-the-marshmellows/get-breakfast/go-to-marsh/go-to-marsh.md

Marsh mystery

---

english/adipose/adipose.md

Chuang Tzu contributes

---

english/explore-outside/talk-child/silent-approach/silent-approach.md
english/explore-outside/talk-child/talk-child.md

Add silent approach the child to 'explore-outside/talk-child' storyline

---

english/soar/fly-to-london/fly-to-london.md

Add options to london visit.

---

english/enjoy-DreamRide/jump-off/jump.md
english/enjoy-DreamRide/ride.md

Add new option to ride.md and add jump.md

---

english/soar/fly-to-paris/fly-to-paris.md

Please add the options in the fly-to-paris.md file.

Add Eiffel Tower Pondering Options

---

english/candyland/diabetes.md
english/candyland/rainbow/rainbow.md
english/candyland/swim/swim.md

Pull story additions to candyland

---

english/experience/experience.md

Added text to experience about the black point

---

english/marshmallow.md
english/polar-bear/polar-bear.md

Changes for polar-bear entry

---

portugues_pt/mundo/voltaaomundo.md

Add trip to North America in "mundo".

---

english/eating-walls/eating-marshmallows.md

Add option to light a fire

---

french/feu-de-camp.md

Changed feu-de-camp.md

---

english/marshmallow.md
english/pork/roast.md

Please review this, @casey-collab"

Pork roast

---

espanol/muralla/abrir/abrirsoldados/abrirsoldados.md
espanol/muralla/abrir/abrirsoldados/cerrad/cerrad.md

Cerrando el portón

---

english/yuha/yuha.md

Let's not end the fun so quickly!

Yuha story add

---

espanol/rezando/enano/enano.md
espanol/rezando/enano/ombligo/ombligo.md

"Please review this, @casey-collab

Conversacion enano

---

english/macgyver/light-rope-on-fire/wait/wait.md

Add links to lead from dead-end back to other parts of the story

---

english/light-up/grab_tools_and_jump/grab_and_jump.md
english/light-up/grab_tools_and_jump/tool_box/tool_box.md
english/light-up/light-up.md

Bill's first pull request.

---

english/light-fire/eating/stream/go-fish/talk-fish/talk.md
english/light-fire/eating/stream/go-fish/talk-fish/weather/weather.md

Add conversation option for talking to fish

Conversation with Fish

---

german/finger-ins-loch/solarbetriebener-Motor/solarbetriebener-Motor.md

Add some lines to solar-betriebenes Motorbot

---

english/you-are-in-minecraft/dig_down/goright/goright.md

Add stuff to the story

---

english/punch/punch.md

add a new line in punch/punch.md

---

english/hide/fork/fork-stab.md
english/hide/hide-chk.md
english/hide/rope/rope-burn.md

Includes two new files to go with the new links in a fork and rope directory.

Added a line to the hide directory and added 2 links.

---

english/marshmallow.md

Own up to occasional intoxicant use.

---

espanol/cocinero/cocinero.md
espanol/cocinero/error/error.md

Add new page in cocinero called "error"

---

german/Hilfeschrei/Vertrauen/Vertrauen-zum-Blauwal.md
german/Hilfeschrei/Vertrauen/insMaul/ins_maul.md

Added new option after meeting the whale [GERMAN]

---

english/marshmallow-taffy/start-conversation/conversation.md

Add to marshmallow-taffy / conversation

---

dutch/bos/donker-bos.md

Add more content to donker-bos.md file

---

english/social-media/social-media.md

please review this @casey-collab

Add new line to social media

---

english/slap-it-hard/flee/flee.md
english/slap-it-hard/teach-it-a-lesson.md

Hello,
I added the option to flee in the english->slap it hard story.
Modified the teach-it-a-lesson.md file and added the flee folder which contains the flee.md file.

Added flee option with own folder

---

english/light-fire/fire.md
english/light-fire/run-away/shout/more-info/goto-town/boy-info/boy-info.md
english/light-fire/run-away/shout/more-info/goto-town/goto-town.md

add to light-fire asking a question to the boy

---

dutch/bos/ontvoering/meehelpen/klus/geld-verdienen.md
dutch/bos/ontvoering/meehelpen/meehelpen.md

Add story change, you are an experienced criminal!

---

english/explore-outside/journey-to-flaming-tower/walk/portal/wishes/eagle/eagle.md
english/explore-outside/journey-to-flaming-tower/walk/portal/wishes/eagle/wishes.md
english/explore-outside/journey-to-flaming-tower/walk/portal/wishes/wishes.md

Hello!
Thank you very much for the course, it was really instructive :)
I've added a new line to the story!
Cheers :D

Add option to wish for an eagle

---

english/dream/dream.md

add [dance] in dream.md [2]

---

german/finger-ins-loch/hoelzernes-Paddel/sicherer_Entfernung/gruessen_freundlich/gruessen_freundlich.md
german/finger-ins-loch/hoelzernes-Paddel/sicherer_Entfernung/sicherer_Entfernung.md

My contribution to the German story.

KHerb's contribution

---

catala/catala.md
catala/pessigar-se/pessigar-se.md

please review this, @cassey-collab

nova pg en cat

---

english/blah-balh/blah-blah.md
english/marshmallow.md

Add blah-blah

---

english/coffee/coffee.md

Add question about caffeine to the story

---

german/finger-ins-loch/hoelzernes-Paddel/aufmerksam_machen/ans_Ufer_ziehen/am_Ufer.md
german/finger-ins-loch/hoelzernes-Paddel/aufmerksam_machen/aufmerksam_machen.md

Add non-deadly end

---

english/malaria/malaria.md

Add line to malaria.md

---

Polish/przygoda/jedzenie/jedzenie.md
Polish/przygoda/jedzenie/najedzony/najedzony.md

Add story 'najedzony'

---

french/feu-de-camp.md

The first file in the french repository has bad display of accentuated Fench characters, this should correct it.

French modifications

---

english/lunge-for-the-lighter/lunge-for-the-lighter.md

Please review and merge this, @casey-collab

Add choice of room exits

---

espanol/torre/espera/espera.md
espanol/torre/espera/vladimir/vladimir.md

Añade un dragon a la historia en español

---

espanol/canudos.md
espanol/ritual/ritual.md

Add Ritual to the story

---

english/invite-friends/friends.md
english/karaoke/karaoke/sing.md
english/karaoke/nope.md

add karaoke

---

english/be-octodog/octodog.md
english/marshmallow.md

Hi, 
I've added my adventure about how to become an octoDog
Please review this, @casey-collab 
Thanks, 
@laurauzcategui

Changed by @laurauzcategui become an Octodog

---

espanol/dragon/dragon.md

Credit to b'ger at http://www.chris.com/ascii/index.php?art=creatures/dragons

Add dragon ascii art

---

english/eating-walls/eating-marshmallows.md

Please review this, @casey-collab (but you probably can't)

Move external link in eating-marshmallows.md to last position.

---

english/pinch/jacket/eatit/eatit.md

Please review this spelling correction @casey-collab

Fixed spelling error in eatit.md

---

english/super-man/lex-luther/find-lex-luther.md

Go find batman in lex-luther story.

---

english/macgyver/cliff/cliffjump.md
english/macgyver/cliff/fall/fall.md
english/macgyver/cliff/rescued/rescued.md

@casey-collab please review this.

Story pages added to MacGyver jump off a cliff

---

Chinese/YW/yw.md

Add last time

---

english/marshmallow.md

pls review this, @casey-collab

add sound of a torrent to the adventure.

---

english/marshmallow.md

Pls have a look on this as well, @casey-collab

add ease of mind to adventure.

---

Chinese/YW/yw.md

intentiaonal conflict

---

english/selfie/selfie.md

To whom it may concern,
I have attached a change to selfie.md.  I am started this class on its own but have since signed up for the nanodegree program.  Thanks!
Nick

add to selfie.md

---

english/dig/bird/run/run.md

Add text to run.md

---

english/jumpsuit/jumpsuit-review.md

Add a line to the story

---

english/coffee/coffee.md

Add missing link to drink-tea

---

english/turing-test/bucket/water.md
english/turing-test/turing-test.md

Add water bucket option.

---

english/virtualreality/problems/realproblems.md

Add one more line to allow more development of the story

---

english/light-fire/graham-crackers/graham-crackers.md
english/light-fire/graham-crackers/refuge/build-refuge.md

Add graham cracker refuge

---

english/yoga/breathe/breathe.md

add option and flavor text to breate.md

---

english/turing-test/eliza/ask_eliza.md

Added more lines to story.

---

english/yoga/yoga.md

Add types of yoga

---

english/marshmallow.md

Add new sentence

---

english/becomemarshmallow/becomemarshmallow.md
english/marshmallow.md

Added new option to main English page.

Added new option to become marshmallow.

---

catala/aixecar/aixecar.md
catala/catala.md

Aixecarse del llit

---

german/Alkohol/alkohol.md

Add a sentence

---

english/scream/remove/removemarshmallow.md
english/scream/scream.md

My suggested changes

---

english/polar-bear/polar-bear.md

Add selfie and dance options to polar-bear.

---

portugues/colabora/comdiferencas/diff/pull/pull.md

Add deny of pull request

---

english/fizzbin/explain-fizzbin.md
english/marshmallow.md

Add explaining Fizzbin to the marshmallow hand to the story.

Add Explain Fizzbin

---

english/magic/magic.md

added a line to the story of magic

Mother of dragons addded to the story

---

english/marshmallow.md

Add wand fashioning & alohomora

---

english/turing-test/ring/one_ring.md

Hello, 
I've added a line of text to one_ring.md
Thank you

Add text indicating cracks form a doorway.

---

english/lego-world/lego-world.md
english/marshmallow.md

Add Willy Wonka Lego-World option

---

english/ask-to-alice/ask-to-alice.md

Just add a line to show instructions for picking the choices.

Add choices instruction

---

english/light-fire/extinguish-fire/extinguish-fire.md
english/light-fire/fire.md

Added extinguish fire option to light fire

---

english/coffee/hollywood/hollywood.md

[Sleep till morning](../../marshmallow.md)

Add hollywood pitch

---

english/lego-world/lego-world.md

Add Lego World Everything is Awesome video link

---

english/invite-friends/mosh_pit/mosh_pit.md

Fix typo and add a line to the story.

---

english/marshmallow.md
english/mspa/mspa.md

Add mspaintadventures option

---

english/coffee/nude-run/nude-run.md
english/coffee/nude-run/silent/silent.md

Add silent option to nude-run

---

english/marshmallow.md
english/world-war-marshmallows/break-through-door/break-through-door.md
english/world-war-marshmallows/hope-help-comes/hope-help-comes.md
english/world-war-marshmallows/world-war-marshmallows.md

Add world-war-marshmallows ending

---

english/dream/dream.md
english/karaoke/nope.md

Please review this, @casey-collab! All dreams should have karaoke!

Add option for karaoke to "dream"

---

russian/zefir.md

Change story

---

english/marshmallow.md

Add apparition spell

---

english/turing-test/ring/one_ring.md

Add shrill sound coming from doorway

---

espanol/canudos.md
espanol/maquina/maquina.md

Add a new story on spanish (espanol) folder.

Reconfigurar maquina del tiempo

---

english/virtualreality/problems/realproblems.md
english/virtualreality/voice/strangeVoice.md

Add to virtualreality story

---

english/world-war-marshmallows/hope-help-comes/eat-your-hands/eat-your-hands.md
english/world-war-marshmallows/hope-help-comes/hope-help-comes.md
english/world-war-marshmallows/hope-help-comes/remember-periscope/remember-periscope.md

add additional story options to hoping help comes

---

english/coffee/nude-run/cold-water/run-away/heaven/heaven.md
english/coffee/nude-run/cold-water/run-away/run-away.md

Made heaven option on run away.

---

english/explore-outside/journey-to-flaming-tower/start-running/keep-running/keep-running.md
english/explore-outside/journey-to-flaming-tower/start-running/keep-running/search-and-rescue/search-and-rescue.md

Search and rescue

---

espanol/torre/estrategia/estrategia.md
espanol/torre/torre.md

I want you to check this please, @casey-collab

Adding my aport to this story!

---

hungarian/malyvacukor.md
hungarian/zuhanyzas/zuhanyzas.md

Add zuhanyzas option to the story

---

german/Kopfsprung/Kopfsprung.md

Machen die Fische gefährlich.

---

espanol/bailar/abucheo/abucheo.md
espanol/bailar/bailar.md
espanol/canudos.md

Please review this, its really nice @casey-collab

Added new adventure twists

---

english/warriors-game/watch-warriors.md

Add Michael Jordan to list of great things from the 90s

---

english/marshmallow.md

Add a page for making s'mores

---

english/netflix/netflix.md

Add Breaking Bad option to netflix.md file

---

english/pinch/help/faint/faint.md

Add an option to go back to the beginning

---

english/lucidream/luciddream.md
english/marshmallow.md

let me know if i miss understood and i should have done everyting on the master, and fell free to edit the text if somthing is wrong in any range. amaizing course btw!

Muffasa story

---

english/eating-walls/find-a-toilet/door/run-in/push-lever/bear.md
english/eating-walls/find-a-toilet/door/run-in/run-into-room.md
english/eating-walls/find-a-toilet/door/run-in/take-ladder/open-sky.md

Created two options for the room. One for the ladder, and another for the lever.

Add two options

---

english/virtualreality/voice/strangeVoice.md

Added lines to strangeVoice.md

---

english/moving/moving.md

Add option with link to eat marshmallow after throwing rock in moving.md

---

english/coffee/starbucks/starbucks-coffee.md

added option to continue writing essay and having some more coffee

added option to continue to write essay and have some more coffee

---

espanol/maquina/maquina.md

Make change to story

---

english/virtualreality/voice/strangeVoice.md

Please review this, @casey-collab added 5 new lines to the bottom.

Updated strangeVoice.md

---

english/wikipedia/wiki.md

Add line to wiki.md

---

catala/cantar/cantar.md
catala/cantar/tastar/tastar.md

He afegit una nova opció accessible des de l'opció "cantar", i la corresponent carpeta amb el nou arxiu .md
La nova opció és "tastar"

Afegir opció dins de 'cantar'

---

english/explore-outside/investigate-marshmallow-structure/investigate-marshmallow-structure.md
english/explore-outside/investigate-marshmallow-structure/scare-green/scare-green.md

Added a new option to the investigation to scare the green people.
added option to investigate-marshmallow-structure.md with relative link
new dir scare-green
new scare-green.md

Scaring the green people at the marshmallow palace

---

portugues_pt/colaborar.md
portugues_pt/componentes/componentes.md

New line and option.

---

espanol/canudos.md
espanol/perro/perro.md

Akbal branch

---

english/cry-out-for-mommy/oh_mommy.md
english/marshmallow.md

@casey-collab  The story need a dimension of fear. Steven King won't be jealous.

add a new dimension of fear to the story

---

english/cry-out-for-daddy/oh_daddy.md
english/cry-out-for-mommy/oh_daddy.md
english/cry-out-for-mommy/oh_mommy.md

Added file

---

english/marshmallow.md
english/red-pill/red-pill.md

Add red pill option to Marshmallow.md and red-pill dir and file.

---

english/marshmallow.md
english/night-night/tale.md

Please review my changes, @casey-collab

Add a Christmas story to the bucket

---

english/super-powers/practice-flying.md

@casey-collab Let me know if it can't be merged!

Add gliding birds

---

english/red-pill/red-pill.md

Correct spelling in red-pil/red-pill.md

---

english/sleep/sit-down-to-meditate/sit-down-to-meditate.md

Add a line to story

---

english/fork-jam/choco-chalice/choco-chalice.md
english/fork-jam/choco-chalice/find-stick/find-stick.md

Added find-stick option to choco-chalice

---

english/virtualreality/oculus.md

Please review & pull this change, @casey-collab

Add a sentence about Kafka's world and Murakami's redesign

---

german/Einladen/Vorstellen/vorstellen.md
german/Einladen/einladen.md

Oktoberfest drink ext

---

english/marshmallow.md
english/reddit/ask-reddit.md

Please review and add please, @casey-collab

Add reddit story line.

---

espanol/calcetines/calcetines.md
espanol/canudos.md

Agrega Calcetines a la historia

---

english/karaoke/karaoke/propose-to-her/propose-to-her.md
english/karaoke/karaoke/puke-on-the-mike/puke-on-the-mike.md
english/karaoke/karaoke/sing.md

Add options in singing karaoke

---

espanol/torre/espera/vladimir/vladimir.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1615)

Lo que paso con el ejercito despues del ataque.

---

english/cry-out-for-mommy/oh_mommy.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1614)

Added Bohemmian Rhapsody reference to 'cry-out-for-mommy'

---

english/lucidream/luciddream.md
english/wake-up/wake-up.md

Added wake-up option to lucid-dreaming.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1619)

add wake-up option

---

espanol/maquina/maquina.md

Add Garth death and capture of Dante

---

english/sleep/marshmallow.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1622)

you need something to eat with the marshmallow

---

german/schwimmen/insel/insel.md
german/schwimmen/schwimmen.md

It is nice to be able to walk around a newly discovered island!
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1629)

Add option to explore the island in the german version.

---

english/reddit/ask-reddit.md
english/reddit/outside_subreddit/r_outside.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1624)

Add r/outside quest option to reddit

---

portugues/revisa/tenta-consegue/ti-cruel/desenvolve-app/angrycocos/angrycocos.md
portugues/revisa/tenta-consegue/ti-cruel/desenvolve-app/coco-app.md
portugues/revisa/tenta-consegue/ti-cruel/desenvolve-app/instacocos/instacocos.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1628)

Add options on developing coconut app

---

english/interact/run-into-wall/run-into-wall.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1633)

Add URL link to run-into-wall.md

---

english/movie-ripoffs/zoolander/zoolander.md

Add one more choice before leaving the young man

---

english/coffee/elephant-poop/coffee.md
english/coffee/starbucks/starbucks-coffee.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1647)

add coffee story option

---

english/light-fire/magic-world/follow/dream/fight/fight.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1648)

Add sentence

---

romanian/nalba.md

Add question for Ginel.

---

english/amnesia/amnesia.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1651)

Add two lines to the amnesia rhyme

---

hungarian/malyvacukor.md
hungarian/reggeli/reggeli.md
language.md

Fix hungarian accents
Add option: breakfast
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1640)

Fix hungarian accents

---

english/find-exit/into-forest/talk-to-cougar/press-for-answer/press-for-answer.md
english/find-exit/into-forest/talk-to-cougar/talk-to-cougar.md

Ask sara anyway

---

english/run/run.md

Changes run

---

english/experience/black-point/black-point.md

Please review and merge if it's all good @casey-collab
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1658)

Expand on black point

---

english/run/run.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1659)

Add lyric from the selfie song.

---

hungarian/zuhanyzas/telefon/telefon.md
hungarian/zuhanyzas/torulkozo/torulkozo.md
hungarian/zuhanyzas/zuhanyzas.md

Zuhany mod to hungarian

---

english/eat-panipuri/eat-panipuri.md
english/eating-walls/eating-marshmallows.md

@casey-collab,Please review my change to create-your-own-adventure repository.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1649)

Add a link for eat-panipuri

---

english/bake-cookies/cookies.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1662)

I added some more verbiage around the feelings around baking cookies.

---

english/marshmallow.md
english/oil-field/oil-field.md

Just adding a random choice about an oil field problem.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1663)

Add oil field option

---

czech/marsmelouny.md
czech/zrejme/udelas.md

Added option to the czech language

---

english/coffee/another-coffee/another-coffee.md

add line to english story

---

english/becomemarshmallow/becomemarshmallow.md

add sentence to marshmallow.md'

---

english/wake-up/wake-up.md

added a line to english/wake-up/wake-up.md

---

czech/kapsy/mince/roztocit.md
czech/kapsy/nuz/riz.md
czech/kapsy/prohledat.md

Sorry for deleted line, it looks same as added one. Probably Windows/Linux eoln issue.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1681)

Czech story. 

---

portugues/revisa/tenta-consegue/sem-resposta/coco/muito-quente.md
portugues/revisa/tenta-consegue/sem-resposta/contato-desenvolvedor.md
portugues/revisa/tenta-consegue/sem-resposta/procura-novo-desenvolvedor/novo-desenvolvedor.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1682)

Add new story after knowing about new developer.

---

english/adipose/adipose.md

Change adipose story

---

portugues/colaborando.md
portugues/cria/melhor.md

Please Review and mege to the master
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1680)

Add Criar um Applicativo melhor

---

galician/lua.md
language.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1686)

Add galician language and begin a new story with Lúa, the cat

---

english/timeTunnel/timeTunnel.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1697)

Add new story line to time tunnel adventure

---

english/advice_from_mother/advice_from_mother.md
english/eating-walls/eating-marshmallows.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1685)

Advice from mother

---

english/forest/scream/dead/dead.md
english/forest/scream/scream.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1689)

added a new branch to scream.md called dead

---

english/water-dreams/pig-farm/hate-bacon/hate-bacon.md
english/water-dreams/pig-farm/love-bacon/love-bacon.md
english/water-dreams/pig-farm/pig-farm.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1693)

Added some bacon humor to pig farm story

---

english/make-friends/make-friends.md

Add option to drink coffee

---

english/yuha/yolo/yolo.md
english/yuha/yuha.md

add yolo to story

---

english/appear-on-falkors-back/falkor.md
english/marshmallow.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1710)

Added appear-on-falkors-back to the story

---

Italian/caramelle.md
Italian/verifica/verifica.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1708)

Add new option to Italian

---

english/marshmallow.md
english/open-door/open-door.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1715)

Added option to open the door to open the door to marshmallow.md

---

english/coffee/drink-tea/alice/alice-in-wonderland.md
english/coffee/drink-tea/drink-hot-tea.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1720)

Add Alice in Wonderland to the coffee branch of the story.

---

espanol/canudos.md
espanol/rodar/rodar.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1722)

Collaborate

---

english/light-fire/xyzzy/xyzzy.md

Adding to the adventure story for Udacity Git class. Thx robot. =P
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1727)

Add option to speak magic words

---

english/warriors-game/watch-warriors.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1717)

Add to story after the NBA Finals 2015

---

english/coffee/cookie/Walk/creative-writing/creative-writing.md
english/coffee/cookie/Walk/walk.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1719)

Added a new option after walking to start creative writing

---

english/can-i-get-you-a-ladder/can-i-get-you-a-ladder.md
english/marshmallow.md

Add the "Can I get you a ladder..." option to the marshmallow story

---

english/marshmallow.md
english/thesituation/situation.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1725)

Kanes Contribution

---

english/marshmallow.md

added a marshmellow video

---

english/yuha/yolo/yolo.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1733)

Add Dim_reality.md link to yolo.md

---

albanian/avion/avion.md
albanian/hyrje.md
albanian/tren/tren.md
language.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1735)

Start Albanian version of the story.

---

english/batman/batman.md
english/marshmallow.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1738)

New story added

---

hungarian/zuhanyzas/telefon/felvesz/felvesz.md
hungarian/zuhanyzas/telefon/telefon.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1740)

Continuing the hungarian story

---

english/coffee/Paris/fly-to-paris.md
english/coffee/coffee.md

Add a new folder Paris and a new file under it fly-to-paris.md

Add an option to coffee.md - Flying to Paris

---

english/forest/fire/fire.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1742)

Add some more story to forest

---

english/bob-barker/barker.md

Add an option to get coffee when talking to Bob Barker

---

english/coffee/Run/run.md
english/coffee/coffee.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1752)

Add Go-for-a-run option to coffee.md

---

english/check-your-phone/check-your-phone.md

Please review this, @casey-collab .

Add a new line

---

danish/snitting/snitting.md

I have updated the Danish storyline - will you merge?
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1731)

Drudeh updates

---

french/feu-de-camp.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1737)

Extra sentence in french

---

english/lucidream/luciddream.md
english/lucidream/potato/potato.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1747)

Add option to turn into a potato in lucid dream

---

english/coffee/drink-water/bathroom/bathroom.md
english/coffee/drink-water/drink.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1748)

Extend drink water scenario

---

english/eating-walls/find-a-toilet/door/open-door.md

Add a freaky line on open-door, please check it @casey-collab ! :P

My own u adventure

---

basque/alde-egin/alde-egin.md
basque/alde-egin/oihu/oihu.md
basque/alde-egin/zaldi/zaldi.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1756)

basque new story

---

german/Hilfeschrei/Hilfeschrei.md

Add a describing sentence

---

english/eating-walls/find-a-toilet/door/run-in/run-into-room.md

Please check it @casey-collab !
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1757)

Add dark to a line on run-into-room

---

english/turing-test/eliza/ask_eliza.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1758)

Add response from Eliza & question for next response

---

english/marshmallow.md
english/pipboy/lockpick/lockpick_100.md
english/pipboy/pipboy.md

Let's go, pal. @casey-collab
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1765)

Let's go, pal.

---

english/pokemon/pikachu_wins.md

Add hint to pikachu story

---

english/bake-cookies/cookies.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1767)

Add breathe link

---

english/marshmallow.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1768)

Add lines to english/marshmallow.md

---

english/eating-walls/find-a-toilet/door/run-in/break-window/coldroom.md
english/eating-walls/find-a-toilet/door/run-in/run-into-room.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1761)

Add break the window and story of cold room

---

language.md
punjabi/ajit/ajitnews.md
punjabi/pollywood/movies.md
punjabi/punjabi.md

Please review and add Punjabi language pack. Thanks!
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1764)

Add punjabi files

---

english/I'm-batman/batman.md
english/marshmallow.md

added the "I'm Batman" story.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1759)

I'm Batman

---

english/experience/black-point/concentrate/stargaze.md

Added more story narrative to the concentrating on the "Black Point" event.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1769)

Add additional story to the black point concentration event

---

espanol/historieta/dago.md
espanol/perro/perro.md

pull request!
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1772)

Nueva historia de Dago, en espanol

---

english/marshmallow.md

Add ethical rationale for feeling anxious wearing leather

---

english/ask-on-quora/ask-on-quora.md
english/marshmallow.md
english/question_on_quora.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1776)

Ask on quora

---

english/candyland/swim/horizon/milkshake_everywhere.md
english/candyland/swim/horizon/ship/its-a-ship.md
english/candyland/swim/swim.md
english/candyland/swim/wall/queen_portrait.md

Milkshake sea story branches

---

english/coffee/Paris/city-train/city-train.md
english/coffee/Paris/fly-to-paris.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1786)

Create a new option from your flight to Paris

---

english/coffee/Run/run.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1787)

Go for a running in the Green Park

---

english/marshmallow.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1788)

added latest wand story line

---

english/wikipedia/wiki.md

Please review this, @casey-collab ! :D

Add Skyrim link in wiki page

---

english/timeTunnel/timeTunnel.md

Please check this out @casey-collab ~
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1800)

Add door path to timetunnel page

---

english/marshmallow.md

added one line

---

english/marshmallow.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1780)

Add Extreme to marshmallow.md

---

english/triathlon/triathlon.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1781)

Change 'my' to 'by' to fix typo

---

english/dig/cup-cocoa/cup-cocoa.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1782)

Add link back to initial story in cup-cocoa storyline

---

english/magic/magic.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1785)

Add smores knowledge

---

english/lighter/toke/toke.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1791)

You fight fatigue as the marhmellow is in fear

---

english/movie-ripoffs/matrix/matrix.md
english/movie-ripoffs/selfaware/selfaware.md

Please pull this branch @casey-collab

Added section on destroying Morpheus but becoming the One

---

czech/druhy_bok/spanek.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1812)

Pokračování spánku

---

language.md
lithuanian/rekti/niekas.md
lithuanian/startas.md
lithuanian/uzsimerkti/vejas.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1813)

Lithuanian edition

---

english/light-fire/magic-world/follow/dream/fight/fight.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1816)

Are my pillows marshmallows

---

english/reddit/outside_subreddit/r_outside.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1817)

Almost done

---

czech/druhy_bok/spanek.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1822)

Add lucid dreaming line

---

english/sing/continue/continue-to-sing.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1823)

Add sentence to continue-to-sing

---

english/bake-cookies/cookies.md

Add a line about a place to buy cookies

---

english/commit-suicide/suicide.md
english/marshmallow.md

If you've had enough of your life.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1825)

Commit suicide

---

portugues/colabora/comdiferencas/diff/pull/reenvio/reenviar.md
portugues/colabora/comdiferencas/diff/pull/reenvio/star/star.md
portugues/colabora/comdiferencas/diff/pull/reenvio/watch/watch.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1833)

Add reasons for others to collaborate with the open source community

---

english/marshmallow.md
english/robot-rap-battle/robot-rap-battle.md

Added the option to create an artificial intelligence to the main story.

---

english/apj/apj.md
english/apj/quotes/quotes.md
english/marshmallow.md

Add story of APJ

---

english/warriors-game/watch-warriors.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1839)

Add Dwyane Wade's satisfaction

---

english/sleep/marshmallow.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1845)

after sleeping, add a happy dance option

---

english/quote-of-the-day/life/life.md

Add another quote

---

english/you-are-in-minecraft/gather_wood/focus_on_gathering_wood/focus_on_gathering_wood.md
english/you-are-in-minecraft/gather_wood/gather_wood.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1847)

Add minecraft gather wood option

---

english/glowing-pants/glowing-pants.md
english/marshmallow.md

Add glowing pants adventure

---

catala/aixecar/aixecar.md

Add line in 'aixecar'

---

english/macgyver/stickfork/stickforkinwall.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1851)

Added climbing-rope

---

german/Stopfen/entspannen/entspannen.md
german/Stopfen/stopfen.md

Change something

---

english/light-fire/magic-world/follow/dream/fight/fight.md
english/light-fire/magic-world/follow/dream/fight/sword/sword.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1857)

Add pick up sword in fight

---

english/coffee/drink-tea/drink-hot-tea.md
english/shrunk/shrunken.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1858)

Added shrunken option after drinking tea

---

german/Leichen/Leichen.md
german/ruderboot.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1852)

Add german story twist 'Leichen'

---

english/eating-walls/find-a-toilet/door/bear/too-many-marshmallows/too-many-marshmallows.md

Complete too-many-marshmallows.md

---

romanian/ceai_de_nalbe/ceai_de_nalbe.md
romanian/nalba.md

Add new lines to the story and a new file

---

english/macgyver/macgyver.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1870)

add new line to macgyver story

---

espanol/torre/huida/huida.md
espanol/torre/torre.md

Check it out :)
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1863)

New Torre story "Huida" in spanish section

---

espanol/torre/estrategia/estrategia.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1866)

Fix some misspelling in the spanish version

---

dutch/over-het-hek/sleutel/sleutel.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1869)

Delete repeated word

---

english/wikipedia/wiki.md

add my line to wikipedia story 

---

english/macgyver/macgyver.md

I added a line, @casey-collab !

Added line to Macgiver story

---

english/ask-to-alice/ask-to-alice.md
english/scarab/goddess.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1875)

Planetsumsiu update

---

english/free-lunch/free-lunch.md
english/marshmallow.md

Add a free-lunch story

---

english/marshmallow.md
english/untrustworthy/untrustworthy.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1878)

I don't like marshmallows too much

---

english/coffee/coffee.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1882)

Add a sentence about coffee

---

english/thesituation/situation.md

Hope this works!
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1879)

make tiny change to test things out

---

english/marshmallow.md
english/play-with-dog/dog.md

You can now play with a dog! Beware of it's stare...
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1881)

Play with dog

---

english/movie-ripoffs/matrix/matrix.md
english/use-the-fork-luke/use-the-fork.md
english/valarmorghulis.md
english/valarmorghulis/valarmorghulis.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1885)

Add Valar Morghulis

---

kurdish/faith-in-humanity/mrov.md
kurdish/kurdi.md
language.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1886)

Add the Kurdish language

---

english/open-door/open-door.md

Add sentence on being crushed by a giant corn!

---

english/avatar/air.md

Add sentence about Fire Lord Ozai

---

english/love/love.md
english/marshmallow.md

Add new story for the english readers

---

english/eating-walls/find-a-toilet/door/alien/use-torch.md
english/eating-walls/find-a-toilet/door/open-door.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1891)

Add new option to open door page

---

english/adipose/awake/awake.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1889)

Added death to the dream.

---

english/marshmallow.md
english/singapore/singapore.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1898)

Add Singapore Story

---

english/marshmallow.md
english/talk-to-finn/finn.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1900)

add finn story

---

english/bob-barker/barker.md

Please review this, @casey-collab.  Added a line to barker.md.

Add line to barker.md

---

portugues/amigo/incomodar/aplicativo.md
portugues/amigo/incomodar/aprender/aprender.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1903)

Adiciona aprender

---

english/marshmallow.md
english/pick-up-blowtorch/blowtorch.md

adding some blowtorch fun to the english story. Please review this, @casey-collab.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1905)

Engish edition

---

english/guitar/guitar.md
english/marshmallow.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1914)

Add guitar.md and link in main marshamllow.md

---

romanian/nalba.md
romanian/potiune_fermecata/potiune.md
romanian/zana_albastra/cum_arata_zana.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1918)

Apare zana albastra

---

english/birdistheword/birdistheword.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1919)

Added new line about hope

---

Chinese/Cinderella/Cinderella.md

Add a line to Cinderella

---

portugues/amigo/incomodar/aprender/aprender.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1904)

Corrige enter

---

language.md
serbian/burekMeso/burekMeso.md
serbian/burekSir/burekMeso.md
serbian/burekSir/burekSir.md
serbian/start.md

Please, include my little contribution to overall adventure. Start of this story is promising.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1915)

Hodanje contrib

---

english/yoga/mind/yoga_mind.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1926)

Add option to view lifestyle

---

english/macgyver/jump-rope/jump-a-rope.md

feat: added options for dealing with a hungry marshmallow

---

english/I'm-batman/batman.md

Fixed typos and added lines to the batman.md file.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1920)

Cagrosso story

---

english/coffee/Run/run.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1921)

Stop running

---

english/coffee/another-coffee/another-coffee.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1922)

Add a silly poem about coffee

---

english/play-gta5/play-gta5.md

Changed story.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1924)

Play gta story

---

portugues_pt/colaborar.md

Add one more line for Portuguese people

---

english/dysentry/dysentry.md
english/marshmallow.md

@casey-collab @cbuckey-uda  Updated pull request. Now page reachable from the rest of the story. Thanks for the feedback.

Added Oregon Trail

---

english/yoga/goals/goals_of_yoga.md

Add line of perfect harmony to goals_of_yoga.md

---

english/wake-up/wake-up-again/wake-up-again.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1937)

add new line to story

---

espanol/canudos.md
espanol/exageracion/exageracion.md

Change canudos.md history that is present in espanol/canudos.md adding exageracion/exageracion.md in canudos file and creating the folder and the file in espanol folder.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1938)

Adding espanol/exageracion/exageracion.md continuing the history from rodar/rodar.md

---

english/macgyver/jump-rope/jump-a-rope.md

feat: added a few lines to practice updating a cross repository pull

---

korean/marshmallow.md
korean/read/read.md

Add story in Korean, read

---

english/buy-gameboy/buy-gameboy.md
english/pokemon/pikachu_wins.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1936)

Danny story

---

german/Oktoberfest/oktoberfest.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1939)

Fix some spelling errors.

---

english/interact/fork/follow/follow.md
english/interact/fork/follow/ponder/ponder-the-hole.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1946)

add pondering track to the hole in marshmallow

---

language.md
urdu/urdu-news.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1947)

Add Urdu language story

---

english/plummet/plummet.md

Add plummet options

---

espanol/perro/perro.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1950)

Add line to perro

---

french/panique/sentir/fleurs.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1954)

Added a continuation to the story

---

english/batman/batman.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1955)

add google link in modified branch

---

espanol/hijo/hijo.md
espanol/hijo/mazmorra/mazmorra.md
espanol/hijo/preparar/preparar.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1948)

Aniadir ordenes al hijo

---

english/bob-barker/barker.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1951)

Add sentence to bob barker story

---

english/2spooky/2spooky.md
english/marshmallow.md

Bobs world

---

english/lisp/lisp.md

Add more to the intro.

---

english/light-fire/xyzzy/stand-petrified/meet-wizard.md

Adding a bit to set up any decision tree for next pages..
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1962)

Add how do you choose?

---

english/matrix/matrix2inception/jonsnow/jon.md
english/matrix/matrix2inception/matrix2inception.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1961)

Add new story branch to matrix

---

english/forest/forest.md
english/forest/shelter/shelter.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1963)

New Shelter option on Forest story

---

english/call-a-doctor/hungry/hungry.md

Added 2 new lines to file hungry.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1968)

Added few lines to hungry file

---

german/Hilfeschrei/Vertrauen/Vertrauen-zum-Blauwal.md

@casey-collab pls check this out

add option to the german story line: neue option beim Blauwahl

---

french/manger/trou/reveille/surprise.md
french/manger/trou/trou.md

Add a new option "reveille" to "trou.md"
Add the directory "reveille" with a short description of what happens in the file "surprise.md"
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1971)

Add a new option "reveille" to "trou.md"

---

english/choose-pill/choose-pill.md

Added morpheus' words.  No deletions/ modifications.  Looks like the diff shows an end of file character change.
thanks,
noSinging.

Add further advise about choosing a pill

---

english/eating-walls/find-a-toilet/door/alien/use-torch.md

Let the alien escape

---

english/marshmallow.md

Add my sentence about chocolate Tim Tams

---

english/coffee/coffee.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1982)

Add 'silent' to scream for coffee

---

german/Stopfen/entspannen/entspannen.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1986)

Add new question to german story.

---

english/mirror/enter-mirror.md
english/mirror/insist/insist.md

Adds option to insist that the mirror is truly a mirror via  '../mirror/enter-mirror.md'. Creates '../mirror/insist/insist.md'. Insist.md loops back to '../../marshmellow.md'.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1991)

Mirror Insistence

---

espanol/noticias/burla-periodista/burla-periodista.md
espanol/noticias/burla-periodista/leones/leones.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1976)

agregar el consejero suelta a los leones

---

espanol/muralla/abrir/abrirsoldados/cerrad/cerrad.md
espanol/muralla/abrir/abrirsoldados/cerrad/rocas/rocas.md

Add change to the story; rocas (in spanish)

---

english/mushroom/eat/eat_mushroom.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1997)

Add bizarre anthropological musings to mushroom situation

---

english/play-with-dog/dog.md

added a dog option

---

english/warriors-game/watch-warriors.md

dropped some nba knowledge

---

english/hammertime/hammertime.md
english/marshmallow.md

Add hammertime to marshmallow.md

---

bite-the-marshmallow/tasty-marshmallow.md
english/bite-the-marshmallow/tasty-marshmallow.md
english/marshmallow.md

Added option to eat the marshmallow wall to see some interesting things happen, please review @casey-collab
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2008)

Liams adventure

---

english/virtualreality/oculus.md

@casey-collab please see if this can be added to the story
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2010)

Add Groundhog day context

---

english/marshmallow.md
english/unending-story/unending-story.md

Add my 2 cents to the story

---

Polish/ubranie/kieszen/gwizdek/zbadajgwizdek/gwizdekdokieszeni/gwizdekdokieszeni.md
Polish/ubranie/kieszen/gwizdek/zbadajgwizdek/zagwizdaj/zagwizdaj.md
Polish/ubranie/kieszen/gwizdek/zbadajgwizdek/zbadajgwizdek.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/1993)

added next part of the story

---

espanol/hijo/hijo.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2018)

Añadida la frase "No sabía muy bien qué hacer, finalmente..."

---

espanol/pensamiento/estoicismo/estoicisimo.md
espanol/pensamiento/estoicismo/estoicismo.md
espanol/pensamiento/guerra.md

Added side story
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2019)

Estoicismo

---

catala/aixecar/aixecar.md
catala/cantar/cantar.md
catala/cantar/sortir_tenda/sortir_tenda.md
catala/pessigar-se/pessigar-se.md
catala/sortir/sortir.md

my little part of adventure

---

english/plummet/plummet.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2028)

Add to superman's befuddlement.

---

language.md
vietnamese/kechuyen.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2029)

Add vietnamese version

---

english/bob-barker/barker.md

Can you merge my pull request? thank you
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2023)

Added spay phrase for Bob Barker, he always must say that as his last line.

---

portugues_pt/mundo/inventar/inventar.md
portugues_pt/mundo/voltaaomundo.md

Change history!

---

english/mirror/enter-mirror.md
english/quit-your-job/quit-your-job.md

This is a good option to add @casey-collab
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2034)

add option to quit job

---

hungarian/alvas/alom.md
hungarian/alvas/megnezem.md
hungarian/alvas/megnezem/megnezem.md

Continue the story alvas with a new option.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2030)

Alvas-megnezem

---

portugues/colabora/comdiferencas/diff/pull/reenvio/watch/divulga/divulga.md
portugues/colabora/comdiferencas/diff/pull/reenvio/watch/emprego/emprego.md
portugues/colabora/comdiferencas/diff/pull/reenvio/watch/watch.md

Add watch choices in portuguese folder
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2036)

Add watch choices in portuguese folder

---

portugues/revisa/desiste/desistir.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2038)

add new line on desistir

---

espanol/muralla/abrir/abrirsoldados/abrirsoldados.md

Intended for automatic merge by @casey-collab

Adicionar exclamacion de Beatito

---

english/pick-up-blowtorch/blowtorch.md

Giant Coming

---

english/marshmallow.md
english/watch-barca/watch-barca.md

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2048)

Added watch Barcelona game option

---

english/breakfast/breakfast.md

Added a line

---

turkce/catalla-kaz/catalla-kaz.md
turkce/catalla-kaz/metali-cek/metali-cek.md

Add new option: Metali Çek

---

english/forest/pockets/pockets.md

It is to making the beginning more smooth.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/udacity/create-your-own-adventure/2052)

added new sentence on the beginning

---

english/scream/mom/eatwithmom.md

Please take a look, @casey-collab

oh mother oh mother
